\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/CS327.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.88\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.72
  }
  system-system-spacing = #'((basic-distance . 12.41) (minimum-distance . 12.41) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "主阿，我愛你"
  subtitle = "愛慕耶穌"
  opus = "Cs327"
}

global = {
  \key f \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  a'8([^\markup { \italic \bold "(吉他: Capo 3)" } bes'8)] | c''4. b'8 d''4 | c''2 a'8([ g'8)] | f'4. e'8 g'4 | f'2 f'4 | bes'4. bes'8 bes'4 | d''4 c''4 c''4 | g'2.~ \break | g'2 a'8[ bes'8] | c''4. b'8 d''4 | c''2 a'8[ g'8] | f'4. e'8 g'4 | f'2 g'8([ a'8)] | bes'4. c''8 bes'4 | a'4 e'4 g'4 | f'2.~ \break | f'2 f'4 | bes'4. f'8 bes'8[ c''8] | d''2 d''8[ d''8] | c''4. c''8 d''8[ c''8] | g'2 g'4 | a'4. a'8 a'4 | a'4 g'4 f'4 | c''2. \break | g'2 a'8[ bes'8] | c''4. b'8 d''4 | c''2 a'8[ g'8] | f'4. e'8 g'4 \break | f'2 g'8[ a'8] | bes'4. c''8 bes'4 | a'4 e'4 g'4 | f'2.~ | f'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 | s4. s8 s4 | d2:7 s8 s8 | g4. s8 s4 | s2 s4 | e4.:m s8 s4 | g4 s4 s4 | a2. | a2:7 s8 s8 | d4. s8 s4 | s2 s8 s8 | g4. s8 s4 | s2 s8 s8 | e4.:m s8 s4 | a4:7 s4 s4 | g2. | d2 d4:7 | g4. s8 s8 s8 | a2:7 s8 s8 | d4. s8 g8 s8 | a2 s4 | b4.:m s8 s4 | d4 s4 s4 | e2.:m7 | a2:7 s8 s8 | d4. s8 s4 | d2:7 s8 s8 | g4. s8 s4 | g2 s8 s8 | g4.:m s8 s4 | a4:7 s4 s4 | g2. | d2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "主" _ "阿！" "我" "愛" "你，" "我" _ "實" "在" "深" "愛" "你，" "無" "你" "活" "著" "枉" "然、" "失" _ "意。" "你" "是" "富" "有" "吸" "引，" "極" "其" "引" "人" "著" "迷，" _ "你" "的" "豐" "富" "追" "測" "不" _ "盡。" "我" "主" "名" "何" "甜" "蜜，" "呼" "求" "叫" "人" "滿" "意，" "主，" "你" "屬" "我；" "主，" "我" "也" "屬" "你。" "聯" "結" "調" "和" "於" "你，" "神" "人" "合" "併" "為" "一，" "豫" "嘗" "新" "耶" "路" "撒" "冷" "實" "際。" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

