\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/CS463.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 9.02\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.93
  }
  system-system-spacing = #'((basic-distance . 15.20) (minimum-distance . 15.20) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "成為聖別"
  subtitle = "追求與長進"
  opus = "Cs463"
}

global = {
  \key e \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  \tuplet 3/2 { e'4^\markup { \italic \bold "(吉他: Capo 2)" } dis'4 e'4 } b2 | \tuplet 3/2 { e'4 dis'4 e'4 } fis'4 e'8[ fis'8] | \tuplet 3/2 { gis'4 gis'4 gis'4 } \tuplet 3/2 { a'4 gis'4 fis'4 } | \tuplet 3/2 { e'4 e'4 gis'4 } fis'2 \break | \tuplet 3/2 { e'4 b4 gis4 } a2 | \tuplet 3/2 { e'4 b4 e'4 } fis'4 e'8[ fis'8] | \tuplet 3/2 { gis'4 gis'4 gis'4 } \tuplet 3/2 { a'4 gis'4 fis'4 } | \tuplet 3/2 { e'4 e'4 dis'4 } e'2 \break | \tuplet 3/2 { e'4 dis'4 e'4 } b'4. gis'8 | \tuplet 3/2 { a'4 gis'4 a'4 } fis'4 gis'8[ fis'8] | \tuplet 3/2 { e'4 dis'4 e'4 } b'4 gis'8[ b'8] | \tuplet 3/2 { cis''4 b'4 gis'4 } fis'2 \break | \tuplet 3/2 { cis''4 cis''4 dis''4 } e''4 dis''8[ cis''8] | \tuplet 3/2 { b'4 gis'4 fis'4 } e'4 e'8[ dis'8] | \tuplet 3/2 { cis'4 a'4 gis'4 } \tuplet 3/2 { fis'4 e'4 dis'4 } | e'1 \bar "|."
}

harmonies = \chordmode {
  \global
  \tuplet 3/2 { d4 s4 s4 } fis2:m | \tuplet 3/2 { b4:m s4 s4 } a4 s8 s8 | \tuplet 3/2 { d4 s4 s4 } \tuplet 3/2 { g4 s4 s4 } | \tuplet 3/2 { s4 s4 s4 } a2 | \tuplet 3/2 { d4 s4 s4 } g2 | \tuplet 3/2 { d4 s4 s4 } a4 s8 s8 | \tuplet 3/2 { b4:m s4 s4 } \tuplet 3/2 { e4:m s4 s4 } | \tuplet 3/2 { a4 s4 s4 } d2 | \tuplet 3/2 { d4 s4 s4 } fis4.:m s8 | \tuplet 3/2 { g4 s4 s4 } a4 s8 s8 | \tuplet 3/2 { b4:m s4 s4 } fis4:m s8 s8 | \tuplet 3/2 { g4 s4 s4 } a2 | \tuplet 3/2 { b4:m s4 s4 } s4 s8 s8 | \tuplet 3/2 { d4 s4 s4 } b4:m s8 s8 | \tuplet 3/2 { g4 s4 s4 } \tuplet 3/2 { a4:7 s4 s4 } | d1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "創" "世" "之" "前，" "蒙" "神" "揀" "選，" "在" "你" "愛" "裏，" "在" "你" "面" "前" "成" "為" "聖" "別。" "雖" "然" "我" "們" "常" "是" "善" "變，" "但" "你" "憐" "憫" "和" "恩" "典" "卻" "仍" "然" "眷" "憐。" "心" "清、" "心" "輭、" "心" "愛" "與" "心" "安，" "我" "要" "運" "用" "我" "靈，" "照" "著" "你" "的" "心" "意，" "心" "得" "堅" "固，" "使" "我" "活" "你" "面" "前，" "全" "然" "聖" "別，" "得" "以" "完" "全。" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "我們蒙召，雖然年幼，" "卻受吸引，願在你前成為聖別。" "信心工作、愛心勞苦" "並盼望忍耐，是我們屬靈特質。" "我主，我靈、我心、我全人，" "全然傾倒你前，竭力操練敬虔，" "靠你寶血，使我履敗履站，" "勝過肉體，全然聖別。" } }
    } \hspace #1.1 }
    \null
  }
}
