\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/CS807.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.94
  }
  system-system-spacing = #'((basic-distance . 13.19) (minimum-distance . 13.19) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "新局面出現"
  subtitle = "事奉與福音"
  opus = "Cs807"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c''4^\markup { \italic \bold "(吉他: Capo 3)" } | a'4 a'4~ a'4 a'4 | a'2. a'4 | bes'4 bes'4 bes'4 bes'4 \break | bes'2. bes'4 | a'4 a'4 a'4 a'4 | c''4 c''4 c''4 c''4 | g'1~ \break | g'2 c''4 bes'4 | a'4 a'4 a'4 a'4 | a'2 g'4 a'4 | bes'4 bes'4 bes'4 bes'4 \break | bes'2 c''4 bes'4 | a'4 a'4~ a'4 f'4 | g'4 g'4~ g'4 e'4 | f'1~ | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 | s4 s4 s4 s4 | b2.:m s4 | e4:m s4 s4 s4 | a2.:7 s4 | d4 s4 s4 s4 | b4:m s4 s4 s4 | e1:m | a2:7 s4 s4 | d4 s4 s4 s4 | d2:7 s4 s4 | g4 s4 s4 s4 | e2:m s4 s4 | d4 s4 s4 s4 | a4:7 s4 s4 s4 | d2 g2 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "新" "局" "面" _ "出" "現，" "眾" "聖" "徒" "正" "往" "前，" "看！" "神" "的" "榮" "耀" "在" "地" "上" "彰" "顯！" _ "召" "會" "復" "興" "的" "徵" "象，" "前" "後" "左" "右" "皆" "可" "見，" "阿" "利" "路" "亞，" _ "新" "局" "面" _ "出" "現。" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

