\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/CS816.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.97\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 12.32) (minimum-distance . 12.32) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.02) (minimum-distance . 15.02) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "你為何被造"
  subtitle = "事奉與福音"
  opus = "Cs816"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  a'8[^\markup { \italic \bold "(吉他: Capo 3)" } bes'8] | c''2~ c''8[ a'8 g'8 a'8] | f'4 c'2 a'8[ a'8] | g'8([ f'8)] d'4~ d'4 a'8[ a'8] \break | g'2. a'8[ bes'8] | c''2~ c''8[ a'8 g'8 a'8] | f'4 c'2 a'8[ a'8] | g'8([ f'8)] d'4~ d'4 a'8[ a'8] | g'2. r4 \break | c''4 c''4 c''4 d''4 | g'8.[ g'16 g'8 g'8] g'4. a'8 | g'8.[ g'16 g'8 g'8] g'4. a'8 | f'8.[ f'16 f'8 f'8] f'2 \break | c''4 c''4 c''4 d''4 | g'8.[ g'16 g'8 g'8] g'4. a'8 | g'8.[ g'16 g'8 g'8] g'4 a'4 | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 | g2 s8 s8 s8 s8 | d4 s2 s8 s8 | e8:m s8 s4 s4 s8 s8 | a2 a4:7 s8 s8 | d2 a8:7 s8 s8 s8 | d4 s4 b4:m s8 s8 | e8:m s8 s4 e4:m7 s8 s8 | a2:sus4 a4:7 s4 | d4 s4 s4 s4 | e8.:m s16 s8 s8 s4. s8 | a8. s16 s8 s8 a4.:7 s8 | d8. s16 s8 s8 g2 | d4 s4 s4 s4 | e8.:m s16 s8 s8 s4. s8 | a8. s16 s8 s8 a4:7 s4 | d4 g2 d4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "你" "知" "道" _ "你" "為" "何" "被" "造？" "有" "否" "想" _ "過" _ "這" "問" "題？" "你" "的" "生" _ "存" "有" "何" "目" "的？" "你" "今" "活" _ "著" _ "何" "意" "義！" "你" "知" "道" "神" "願" "作" "你" "生" "命？" "祂" "願" "作" "你" "生" "命，" "祂" "願" "作" "你" "生" "命！" "你" "乃" "是" "祂" "所" "造" "的" "器" "皿，" "為" "了" "裝" "祂，" "將" "祂" "表" "明。"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "你有靈，在你最深處，" "比你的心更深入；" "你的心裝許多事物，" "但你的靈仍缺如！" "多少年來，你虛空度日；" "雖然到處嘗試，" "總是不得滿足。" "你的深處豈不覺渴慕；" "願意敞開，嘗嘗耶穌？" } }
      \vspace #0.88
      \line { \bold "3." \column { "不管你的看法如何，" "在神面前誰無過？" "主耶穌已為你流血，" "使你過錯得解決。" "救主耶穌已成全一切，" "不需你再努力─" "功過全無差別；" "祂乃是靈，你接受就行，" "祂願進來作你生命。" } }
      \vspace #0.88
      \line { \bold "4." \column { "猶如你外面的身子，" "容納自己正合式，" "你的靈─在你的深處，" "乃是專為容納主。" "何不現在從深處敞開，" "現在讓主進來，" "充滿你的心懷；" "何不現在從深處敞開，" "呼喊主名，祂必進來。" } }
    } \hspace #1.1 }
    \null
  }
}
