\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/CS874.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.16
  }
  system-system-spacing = #'((basic-distance . 13.10) (minimum-distance . 13.10) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.96) (minimum-distance . 14.96) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "等候耶和華，重新得力"
  subtitle = "事奉與福音"
  opus = "Cs874"
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  e'4^\markup { \italic \bold "(吉他)" } e'8[ g'8] a'4 a'8[ c''8] | b'4 b'8([ g'8)] e'2 | e'4 g'8[ e'8] d'4 g'8[ e'8] | d'4. a8 d'2 \break | e'4 e'8[ g'8] a'4 a'8[ c''8] | b'4 b'8([ g'8)] e'2 | e'4 g'8[ e'8] d'4 g'8[ e'8] | d'4. a8 c'2 \break | r4 c'4 e'4 g'4 | b'8 a'4.~ a'4 c''4 | b'4( a'4) e'8 g'4. | r4 e'4 e'4 g'4 | g'8 d'4.~ d'4 g'4 | a'4( g'4) e'8 g'4. \break | r4 c'4 e'4 g'4 | b'8 a'4.~ a'4 c''4 | b'4( a'4) e'8 g'4. | r4 e'4 e'4 g'4 | a'8 a'4.~ a'4 a'4 | b'4 c''4 d''2 | r1 \break | c''2^\markup { \box \bold "副" } d''2 | e''8 b'4.~ b'2 | a'2 b'2 | c''8 g'4.~ g'2 | r4 g'4 e'4 g'4 | a'1 | r4 a'4 b'4 c''4 | d''4. c''8 c''2~ | c''1 \bar "|."
}

harmonies = \chordmode {
  \global
  e4:m s8 s8 a4:m s8 s8 | e4:m s8 s8 c2 | s4 s8 s8 g4 s8 s8 | d4.:m s8 s2 | e4:m s8 s8 f4 s8 s8 | e4:m s8 s8 s2 | c4 s8 s8 g4 s8 s8 | d4.:m s8 c2 | c4 s4 s4 s4 | f8 s4. s4 s4 | s4 s4 e8:m s4. | s4 s4 s4 s4 | d8:m s4. s4 s4 | g4 s4 c8 s4. | c4 s4 s4 s4 | f8 s4. s4 s4 | s4 s4 e8:m s4. | s4 s4 s4 s4 | f8 s4. s4 s4 | s4 s4 g2 | s1 | c2 s2 | e8:m s4. s2 | f2 s2 | c8 s4. s2 | s4 s4 s4 s4 | f1 | s4 s4 s4 s4 | g4.:7 s8 c2 | s1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "等" "候" "耶" "和" "華，" "重" "新" "得" _ "力；" "必" "如" "鷹" "展" "翅，" "上" "騰" "離" "地。" "憑" "復" "活" "大" "能，" "翱" "翔" "天" _ "際；" "奔" "跑" "不" "困" "倦，" "行" "走" "不" "疲。" "飛" "向" "蔚" "藍" "天，" _ "遠" "離" _ "家" "鄉；" "脫" "世" "俗" "羈" "絆，" _ "去" "地" _ "捆" "綁。" "願" "受" "主" "差" "遣，" _ "同" "祂" _ "前" "往；" "將" "國" "度" "福" "音，" _ "帶" "給" "萬" "邦。" "神" "的" "飛" "鷹，" _ "展" "翅" "翱" "翔，" _ "直" "到" "錫" "安，" "永" "遠" "同" "主" "作" "王。" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "顧到神權益，不為自己；" "使我被取代，讓主頂替。" "與主成為一，有如飛鷹；" "成為得勝者，擊拜仇敵。" "往普天下去，傳揚福音；" "栽種召會樹，開展移民。" "作耶穌見證，跟隨七靈；" "金燈台照亮，國度降臨。" } }
    } \hspace #1.1 }
    \null
  }
}
