\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/CS878.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.97\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.82
  }
  system-system-spacing = #'((basic-distance . 13.27) (minimum-distance . 13.27) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.97) (minimum-distance . 14.97) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "祂來過"
  subtitle = "事奉與福音"
  opus = "Cs878"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  f'4^\markup { \italic \bold "(吉他)" } f'8[ e'8] f'4 f'8[ g'8] | a'2. g'8[ a'8] | f'4 e'4 d'4 c'4 | a1 \break | f'4 f'8[ e'8] f'4 f'8[ g'8] | a'2. g'8[ a'8] | f'4 e'4 d'4 c'4 | d'1 \break | g'8[ g'8~ g'8 f'8] g'4 f'8[ g'8] | a'2. g'8[ a'8] | c''4 a'4 f'4 d'4 | c'2. f'8[ g'8] \break | a'4 c''4 a'4 c''4 | d''2. d''8[ c''8] | a'4 f'4 f'4 g'4 | f'1 \break | c''8[^\markup { \box \bold "副" } a'8 a'8 g'8] f'4 g'8[ a'8] | f'4 d'4 f'2 | f'8[ f'8~ f'8 g'8] a'4 g'8[ a'8] | c''1 \break | c''8[ a'8~ a'8 g'8] f'2 | a'8[ g'8~ g'8 f'8] d'2 | a'8[ g'8 f'8 d'8] c'4 f'8([ g'8)] | f'1 \bar "|."
}

harmonies = \chordmode {
  \global
  d4:m s8 s8 s4 s8 s8 | s2. s8 s8 | bes4 s4 s4 s4 | a1:m | d4:m s8 s8 s4 s8 s8 | s2. s8 s8 | bes4 s4 a4:m s4 | d1:m | g8:m s8 s8 s8 s4 s8 s8 | f2. s8 s8 | a4:m s4 bes4 s4 | c2.:7 s8 s8 | f4 s4 s4 s4 | d2.:m s8 s8 | bes4 s4 c4:7 s4 | f1 | f8 s8 s8 s8 s4 s8 s8 | d4:m s4 f2 | s8 s8 s8 s8 bes4 s8 s8 | c1:7 | f8 s8 s8 s8 s2 | d8:m s8 s8 s8 s2 | bes8 s8 s8 s8 c4:7 s8 s8 | f1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "人" "生" "不" "定" "無" "長" "久，" "我" "的" "所" "有" "遭" "剝" "奪，" "無" "奈" "承" "受" "痛" "與" "羞，" "獨" "自" "絕" "望" "中" "倒" "臥，" "深" "深" _ "苦" "情" "無" "人" "憐，" "重" "重" "患" "難" "誰" "來" "遣，" "以" "為" "生" "命" "即" "消" "散，" "祂" "竟" "出" "現" "在" "眼" "前。" "今" "生" "今" "世" "我" "口" "最" "愛" "提" "說，" "就" "是" _ "我" "主" "祂" "來" "過，" "驅" "走" _ "黑" "暗，" "擔" "我" _ "輭" "弱，" "作" "我" "平" "安" "永" "穩" _ "妥。"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "祂用油酒來敷裹，" "我心傷痛與坎坷，" "懷我、肩我、扶助我，" "那有一點我配得，" "我這纔知何為愛，" "竟然施與我無賴，" "為使一生都開懷，" "接我到神家裏來。" } }
      \vspace #0.88
      \line { \bold "3." \column { "別看今我有何長，" "若非主我早崩潰，" "我命、我愛、我力量，" "全都屬祂不別歸，" "喜樂、盼望真顯明，" "救恩全備又有能，" "我口頌讚心感銘，" "一生因祂樂歡騰。" \translate #'(3.25 . -1.50) "我心歌唱主愛高深長濶，" \translate #'(3.25 . -1.50) "祂必永不離開我，" \translate #'(3.25 . -1.50) "作我生命，與我同活，" \translate #'(3.25 . -1.50) "伴我此生共度過。" } }
    } \hspace #1.1 }
    \null
  }
}
