\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1013.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.86
  }
  system-system-spacing = #'((basic-distance . 13.38) (minimum-distance . 13.38) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "What can keep the wanderers from going"
  subtitle = "Gospel — Love"
  opus = "1013"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  a'8.[ a'16 a'8. g'16] f'8.[ f'16 f'8. e'16] | d'16 e'8. f'8.[ d'16] c'4( f'4) | g'16 g'8. g'8.[ g'16] f'4 g'4 | a'2 c''2 \break | a'8.[ a'16 a'8. g'16] f'8.[ f'16 f'8. e'16] | d'8.[ e'16 f'8. g'16] a'2 | bes'16 bes'8. a'8.[ g'16] c''4 a'4 | g'2 f'2 \break | c''8.[ b'16^\markup { \box \bold "Chorus" } c''8. b'16] c''4 bes'4 | a'8.[ gis'16 a'8. gis'16] a'2 | bes'8.[ a'16 bes'8. a'16] bes'4 g'4 | a'8.[ a'16 b'8. b'16] c''4( bes'4) \break | a'8.[ a'16 a'8. bes'16] c''4 a'4 | g'8.[ g'16 a'8. a'16] bes'2 | c''8.[ c''16 c''8. d''16] c''4 a'4 | g'2 f'2 \bar "|."
}

harmonies = \chordmode {
  \global
  d8. s16 s8. s16 s8. s16 s8. s16 | g16 s8. s8. s16 d4 s4 | s16 s8. s8. s16 s4 s4 | a2 a2:7 | d8. s16 s8. s16 s8. s16 s8. s16 | g8. s16 s8. s16 d2 | g16 s8. s8. s16 d4 s4 | a2:7 d2 | d8. s16 s8. s16 s4 s4 | s8. s16 s8. s16 s2 | a8. s16 s8. s16 a4:7 s4 | d8. s16 e8.:7 s16 a4:7 s4 | d8. s16 s8. s16 d4:7 s4 | g8. s16 s8. s16 s2 | d8. s16 s8. s16 s4 s4 | a2:7 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "What" "can" "keep" "the" "wan" -- "der" -- "ers" "from" "go" -- "ing" "all" "as" -- "tray?" _ "Noth" -- "ing" "but" "the" "love" "of" "Je" -- "sus!" "What" "can" "turn" "the" "fall" -- "en" "peo" -- "ple" "from" "their" "sin" -- "ful" "way?" "Noth" -- "ing" "but" "the" "love" "of" "Je" -- "sus!" \set stanza = "(C)" "Noth" -- "ing" "but" "the" "love" "of" "Je" -- "sus" "can" "con" -- "strain!" "Noth" -- "ing" "but" "the" "love" "of" "Je" -- "sus" "can" "sus" -- "tain!" _ "Noth" -- "ing" "both" "in" "heav’n" "and" "earth" "can" "sin" -- "ners" "gain," "Noth" -- "ing" "but" "the" "love" "of" "Je" -- "sus!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "What can chase the bitterness from all" "the suffering ones?" "Nothing but the love of Jesus!" "What can wipe away the tears of all" "the weeping ones?" "Nothing but the love of Jesus!" } }
      \vspace #0.88
      \line { \bold "3." \column { "What as ointment to the wound can heal" "the wounded hearts?" "Nothing but the love of Jesus!" "What as showers to the drought can cheer" "despairing hearts?" "Nothing but the love of Jesus!" } }
      \vspace #0.88
      \line { \bold "4." \column { "What can satisfy the human life" "of vanity?" "Nothing but the love of Jesus!" "What can swallow up the taste of" "all mortality?" "Nothing but the love of Jesus!" } }
    } \hspace #1.1 }
    \null
  }
}
