\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1028.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.86
  }
  system-system-spacing = #'((basic-distance . 12.68) (minimum-distance . 12.68) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.92) (minimum-distance . 14.92) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Jesus is tenderly calling thee home"
  subtitle = "Gospel — The Lord’s Calling"
  opus = "1028"
}

global = {
  \key bes \major
  \time 6/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  f'4 f'4 f'4 f'4 d'4 ees'4 | f'4 g'4 a'4 bes'2. | bes'4 a'4 g'4 a'2. | g'4 f'4 e'4 f'2. \break | f'4 f'4 f'4 f'4 d'4 ees'4 | f'4 g'4 a'4 bes'2. | a'4 g'4 a'4 c''4 bes'4 g'4 | f'2.~ f'2 r4 \break | bes'2.~^\markup { \box \bold "Chorus" } bes'4 a'4 g'4 | a'2.~ a'2 r4 | c''2.~ c''4 bes'4 a'4 | bes'2.~ bes'2 r4 \break | d''2.~ d''4 c''4 bes'4 | bes'2.~ bes'4 a'4 g'4 | f'4. f'8 f'4 f'4 g'4 a'4 | bes'2.~ bes'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 s4 s4 s4 s4 s4 | s4 s4 s4 s2. | d4 s4 s4 d2.:7 | g4 s4 s4 s2. | g4 s4 s4 s4 s4 s4 | s4 s4 s4 s2. | d4 s4 s4 a4:7 s4 s4 | d2. d2:7 s4 | g2. s4 s4 s4 | a2.:m s2 s4 | d2. d4:7 s4 s4 | g2. c2 s4 | g2. g4:7 s4 s4 | c2. a4:7 s4 s4 | g4. s8 s4 d4:7 s4 s4 | g2 c4 g2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Je" -- "sus" "is" "ten" -- "der" -- "ly" "call" -- "ing" "thee" "home—" "Call" -- "ing" "to" -- "day," "call" -- "ing" "to" -- "day!" "Why" "from" "the" "sun" -- "shine" "of" "love" "wilt" "thou" "roam," "Far" -- "ther" "and" "far" -- "ther" "a" -- "way?" _ \set stanza = "(C)" "Call" -- _ "ing" "to" -- "day!" _ "call" -- _ "ing" "to" -- "day!" _ "Je" -- _ "sus" "is" "call" -- _ "ing," "is" "ten" -- "der" -- "ly" "call" -- "ing" "to" -- "day!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Jesus is calling the weary to rest," "Calling today! calling today!" "Bring Him thy burden and thou shalt be blest:" "He will not turn thee away." } }
      \vspace #0.88
      \line { \bold "3." \column { "Jesus is waiting, O come to Him now!" "Waiting today! waiting today!" "Come with thy sins, at His feet lowly bow;" "Come, and no longer delay." } }
      \vspace #0.88
      \line { \bold "4." \column { "Jesus is pleading, O list to His voice!" "Hear Him today! hear Him today!" "They who believe on His name shall rejoice:" "Quickly arise, come away!" } }
    } \hspace #1.1 }
    \null
  }
}
