\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1124.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.89
  }
  system-system-spacing = #'((basic-distance . 12.00) (minimum-distance . 12.00) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "What! Not sing of blood divine"
  subtitle = "Assurance and Joy of Salvation — Redeemed by the Blood"
  opus = "1124"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  a'4. g'8 f'4 bes'4 | a'4. g'8 f'2 | g'4. f'8 e'4 d''4 | c''4. bes'8 a'2 \break | a'4. g'8 f'4 bes'4 | a'4. g'8 f'4 f'8[ f'8] | g'4 bes'4 a'4 g'4 | f'1 \bar "|."
}

harmonies = \chordmode {
  \global
  d4. s8 s4 s4 | s4. s8 s2 | a4. s8 s4 s4 | a4.:7 s8 d2 | d4. s8 s4 s4 | s4. s8 s4 s8 s8 | a4 s4 s4 s4 | d4 g4 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "What!" "Not" "sing" "of" "blood" "di" -- "vine?" "What!" "Not" "tell" "to" "all" "man" -- "kind?" "What!" "Not" "speak" "to" "hearts" "un" -- "clean" "Of" "the" "pre" -- "cious" "liv" -- "ing" "stream."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "By this blood, God’s life released," "Blood surpassing any beast’s;" "Perfect, spotless Lamb of God," "Incorruptible His blood." } }
      \vspace #0.88
      \line { \bold "3." \column { "Voice it has, this holy blood;" "Pow’r possessed to speak with God;" "Speaks it for us at the throne" "With its glorious virtue shown." } }
      \vspace #0.88
      \line { \bold "4." \column { "Failure on our conscience is—" "Conscience means a “knowing this”—" "Causing us much grief and pain," "Telling us of every stain." } }
      \vspace #0.88
      \line { \bold "5." \column { "All the while we’re unaware" "Of the blood’s effectual prayer." "Jesus’ blood speaks of our case," "That we might receive His grace!" } }
      \vspace #0.88
      \line { \bold "6." \column { "We need not dead works to bring," "Nor another offering." "Nothing else could please our God," "Heav’n is listening for His blood." } }
      \vspace #0.88
      \line { \bold "7." \column { "In His blood forgiveness shines;" "Oh, ’tis glorious to find!" "Israel just atonement knew," "We have that and cleansing too." } }
      \vspace #0.88
      \line { \bold "8." \column { "Heart and mind are now at peace" "Rest! Our conscience has been reached." "Never more we blush in shame," "We are washed from every stain." } }
      \vspace #0.88
      \line { \bold "9." \column { "Hallelujah! Fathomless!" "All that’s in His blood for us!" "Sing we will, and sing we must;" "In His blood is all our trust!" } }
    } \hspace #1.1 }
    \null
  }
}
