\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1142.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.50) (minimum-distance . 12.50) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.89) (minimum-distance . 14.89) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Jesus is the living Spirit"
  subtitle = "Experience of Christ — As the Spirit"
  opus = "1142"
}

global = {
  \key c \major
  \time 2/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'8.[ a'16] g'8[ e'8] | c''8.[ d''16] c''8[ a'8] | g'8.[ a'16] g'8[ e'8] | d'4 r4 \break | g'8.[ a'16] g'8[ e'8] | c''8.[ d''16] c''8[ a'8] | b'8.[ c''16] b'8[ a'8] | g'2 \break | c''8.[^\markup { \box \bold "Chorus" } c''16] c''8[ c''8] | c''8[ g'8] e'8[ g'8] | a'8.[ a'16] a'8[ c''8] | b'4. r8 \break | c''8.[ c''16] c''8[ c''8] | d''8[ c''8] b'8[ a'8] | g'8[ g'8] a'8.[ b'16] | c''4. r8 \bar "|."
}

harmonies = \chordmode {
  \global
  c8. s16 s8 s8 | f8. s16 s8 s8 | c8. s16 s8 s8 | g4 g4:7 | c8. s16 s8 s8 | f8. s16 s8 s8 | d8. s16 d8:7 s8 | g2:7 | c8. s16 s8 s8 | s8 s8 s8 s8 | f8. s16 s8 s8 | g4. s8 | c8. s16 c8:7 s8 | f8 s8 s8 s8 | g8 s8 g8.:7 s16 | c4. s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Je" -- "sus" "is" "the" "liv" -- "ing" "Spir" -- "it," "Our" "re" -- "al" -- "i" -- "ty;" "We" "en" -- "joy" "Him" "just" "by" "call" -- "ing" "In" "sim" -- "pli" -- "ci" -- "ty." \set stanza = "(C)" "Je" -- "sus" "is" "the" "liv" -- "ing" "Spir" -- "it," "We" "must" "now" "pro" -- "claim;" "He" "is" "rich" "un" -- "to" "all" "men" "That" "call" "up" -- "on" "His" "name."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "He is living now within us," "Giving liberty;" "He is good and He is gracious" "As we taste and see." } }
      \vspace #0.88
      \line { \bold "3." \column { "Jesus is the living Spirit" "And the living Word;" "When we touch Him by pray-reading" "We receive this Lord." } }
      \vspace #0.88
      \line { \bold "4." \column { "Jesus is the living Spirit" "Who among us flows;" "Fellowship of life in spirit" "Unity bestows." } }
      \vspace #0.88
      \line { \bold "5." \column { "Jesus is the living Spirit," "He is our rich feast;" "As the Body now enjoys Him," "Praises are released." } }
    } \hspace #1.1 }
    \null
  }
}
