\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1146.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.03
  }
  system-system-spacing = #'((basic-distance . 12.46) (minimum-distance . 12.46) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.84) (minimum-distance . 14.84) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Let us eat Jesus every day"
  subtitle = "Experience of Christ — As Food and Drink"
  opus = "1146"
}

global = {
  \key g \major
  \time 6/8
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  d'8.[ d'16 d'8] d'4 e'8 | g'4 g'8 g'4. | a'8.[ a'16 a'8] a'4 c''8 | b'4 b'8 b'4. \break | d''8.[ d''16 d''8] d''4 c''8 | b'4 b'8 b'4. | a'8.[ b'16 c''8] b'4 a'8 | g'4 fis'8 g'4. \break | b'4.^\markup { \box \bold "Chorus" } d'8.[ e'16 d'8] | g'4. g'4. | a'4. a'8.[ b'16 c''8] | b'4. b'4. \break | d''8.[ d''16 d''8] d''4 c''8 | b'4 b'8 b'4. | a'8.[ b'16 c''8] b'4 a'8 | g'4 fis'8 g'4. \bar "|."
}

harmonies = \chordmode {
  \global
  g8. s16 s8 c4 s8 | g4 s8 s4. | d8. s16 s8 s4 s8 | g4 s8 d4. | g8. s16 s8 d4:7 s8 | g4 s8 e4.:m | a8.:m s16 s8 g4 a8:m | g4 d8:7 g4. | g4. d8.:7 s16 s8 | g4. s4. | d4. s8. s16 s8 | g4. c4. | g8. s16 s8 d4 s8 | g4 s8 e4.:m | c8. s16 s8 g4 c8 | g4 d8:7 g4. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Let" "us" "eat" "Je" -- "sus" "ev" -- "ery" "day," "Eat" -- "ing" "His" "flesh" "in" "such" "a" "way" "That" "in" "the" "tri" -- "als" "great" "or" "small" "He" "as" "a" "Man" "will" "be" "our" "all." \set stanza = "(C)" "Eat," "eat" "more" "of" "Je" -- "sus!" "Eat," "eat" "more" "of" "Je" -- "sus!" "Why" "should" "we" "un" -- "der" -- "nou" -- "rished" "be" "When" "we" "have" "His" "hu" -- "man" -- "i" -- "ty?"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Let us drink Jesus till we see" "That we are human, Jesusly!" "Till rivers flood the barren ground" "And quench the thirst of all around." \translate #'(3.24 . -2.00) "Drink, drink more of Jesus!" \translate #'(3.24 . -2.00) "Drink, drink more of Jesus!" \translate #'(3.24 . -2.00) "Why should we ever thirsty be" \translate #'(3.24 . -2.00) "When we have His humanity?" } }
      \vspace #0.88
      \line { \bold "3." \column { "We must eat Jesus till God can" "Have the fulfillment of His plan—" "One man expressed for all to see," "One church in each locality." \translate #'(3.24 . -2.00) "We’ll masticate Jesus!" \translate #'(3.24 . -2.00) "We’ll masticate Jesus!" \translate #'(3.24 . -2.00) "Then to the tent of meeting bring" \translate #'(3.24 . -2.00) "Jesus, our real meal offering." } }
    } \hspace #1.1 }
    \null
  }
}
