\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1277.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 12.12) (minimum-distance . 12.12) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Now in all the churches flowing"
  subtitle = "The Church — Philadelphia"
  opus = "1277"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  f'4. e'8 d'4 f'4 | g'4. f'8 e'4 c'4 | d'2 e'4. e'8 | f'2. r4 \break | f'4. e'8 d'4 f'4 | g'4. f'8 e'4 c'4 | d'2 e'4. e'8 | f'2. r4 \break | bes'4 a'4 bes'4 c''4 | d''4 c''4 bes'4 a'4 | bes'4. a'8 g'4 f'4 | a'4 g'4 f'4 e'4 \break | f'4. e'8 d'4 f'4 | g'4. f'8 e'4 c'4 | d'2 e'4. e'8 | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d4. s8 g4 s4 | s4. s8 a4 s4 | g2 a4.:7 s8 | d4 g2 d4 | d4. s8 g4 s4 | s4. s8 a4 s4 | g2 a4.:7 s8 | d4 g2 d4 | g4 s4 s4 s4 | s4 s4 s4 s4 | s4. s8 s4 s4 | a4 s4 a4:7 s4 | d4. s8 g4 s4 | s4. s8 a4 s4 | g2 a4.:7 s8 | d4 g2 d4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Now" "in" "all" "the" "church" -- "es" "flow" -- "ing," "Broth" -- "er" -- "ly" "love." "Light" "and" "life" "and" "love" "be" -- "stow" -- "ing," "Broth" -- "er" -- "ly" "love." "In" "the" "one" -- "ness" "all" "be" -- "liev" -- "ing," "Fel" -- "low" -- "ship" "with" "all" "re" -- "ceiv" -- "ing," "Nev" -- "er" -- "more" "the" "Spir" -- "it" "griev" -- "ing," "Broth" -- "er" -- "ly" "love."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "To maintain the sweet communion," "Brotherly love;" "Fellowship and healing union," "Brotherly love." "Love believing for the brothers," "Hoping all things for the others," "Suffering all with one another," "Brotherly love." } }
      \vspace #0.88
      \line { \bold "3." \column { "For the issue of fruit bearing," "Brotherly love." "Fellowship in oneness sharing," "Brotherly love." "Here our soul life we’re forsaking," "And the Spirit’s way we’re taking," "Now from death to life we’re breaking," "Brotherly love." } }
    }
    \left-column {
      \line { \bold "4." \column { "Oh, this perfect way of gladness," "Brotherly love!" "No more fear, imparting sadness," "Brotherly love!" "Now is our sure affirmation," "Life and Spirit our foundation," "Building up, the consummation—" "Brotherly love." } }
      \vspace #0.88
      \line { \bold "5." \column { "Seed of life within us growing," "Brotherly love." "Philadelphia now is flowing," "Brotherly love." "To this love God has restored us;" "Everything will fall before us;" "Love is over all victorious," "Brotherly love!" } }
    }
  }
}
