\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1281.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.86
  }
  system-system-spacing = #'((basic-distance . 12.00) (minimum-distance . 12.00) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "All the meetings Christ appointed"
  subtitle = "Meetings — In Resurrection"
  opus = "1281"
}

global = {
  \key ees \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  ees'8[ f'8] | g'4 ees'4 f'8[ aes'8] | g'4 ees'4 g'8[ g'8] | aes'4 c''4 bes'8[ g'8] \break | f'2 g'8[ aes'8] | bes'4 ees''4 d''8[ c''8] | c''4 bes'4 ees'8[ f'8] | g'4 bes'4 aes'8[ f'8] \break | ees'2 bes'8[ bes'8] | ees''4. bes'8 c''8[ bes'8] | bes'4 g'4 bes'8[ ees''8] | d''4. bes'8 d''8[ c''8] \break | bes'2 ees'8[ g'8] | bes'4. bes'8 c''8[ bes'8] | bes'4 g'4 ees'8[ f'8] | g'8[ aes'8] g'4 f'4 | ees'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  a8 s8 | d4 s4 a8:7 s8 | d4 s4 s8 s8 | e4:m s4 s8 s8 | a2 a8:7 s8 | d4 s4 g8 s8 | fis4:m s4 b8:m s8 | g4 s4 a8:7 s8 | d2 a8:7 s8 | d4. s8 g8 s8 | d4 s4 s8 s8 | a4. s8 e8:7 s8 | a2 a8:7 s8 | d4. s8 a8:7 s8 | d4 s4 g8 s8 | d8 s8 s4 a4:7 | g4 d4 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "All" "the" "meet" -- "ings" "Christ" "ap" -- "point" -- "ed" "And" "at" -- "tend" -- "ed" "here" "on" "earth" "Were" "a" -- "part" "from" "all" "re" -- "li" -- "gion," "All" "its" "ri" -- "tuals," "forms," "and" "dearth." "Re" -- "sur" -- "rec" -- "tion," "not" "re" -- "li" -- "gion," "Must" "be" "our" "re" -- "al" -- "i" -- "ty;" "Let" "us" "meet" "in" "re" -- "sur" -- "rec" -- "tion," "From" "all" "dead" "re" -- "li" -- "gion" "free."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "When the Lord was resurrected," "All religious things were through;" "Christ is now our living temple," "Christ is all our offerings too." "With our Lord in resurrection," "Hallelujah, we’re released!" "Pity all the old religion—" "All our meetings are a feast!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Yet religion—oh, how subtle—" "In our blood is hiding out;" "God must give us revelation," "All that unseen monster rout." "Lord, we still are too religious—" "Down with our religious soul!" "We would all release our spirit," "Let each meeting reach the goal." } }
    }
    \left-column {
      \line { \bold "4." \column { "In the meetings, in the meetings," "On the mountain, at the shore," "Jesus, Jesus, living Jesus," "He is here—what want we more?" "Bury all the old religion," "Even Christianity—" "Jesus, Jesus, we have Jesus," "He is our reality!" } }
    }
  }
}
