\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E1308.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.66) (minimum-distance . 12.66) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "We have oil in our lamps—we are burning"
  subtitle = "Hope of Glory — Preparing for Christ’s Return"
  opus = "1308"
}

global = {
  \key ees \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  bes'8[ bes'8] | bes'4 g'8[ f'8] ees'4 f'8[ ees'8] | c'8 ees'4.~ ees'4 bes'8[ bes'8] | bes'4 g'8[ f'8] ees'4 g'4 \break | f'2. bes'8[ bes'8] | bes'4 g'8[ f'8] ees'4 f'8[ ees'8] | c'8 ees'4.~ ees'4 ees'8[ f'8] | g'8[ bes'8 bes'8 aes'8] g'4 f'4 | ees'1 \break | bes'4. g'8 ees'4 bes'4 | c''4. aes'8 f'4 c''4 | d''4. c''8 bes'8[ aes'8 g'8 f'8] | ees'4 c''4 bes'2 \break | bes'4. g'8 ees'4 bes'4 | c''4. aes'8 f'4 c''4 | d''4. c''8 bes'8[ aes'8 g'8 f'8] | ees'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 | s4 s8 s8 d4:7 s8 s8 | g8 s4. s4 s8 s8 | d4 s8 s8 s4 s4 | a2.:7 s8 s8 | d4 s8 s8 d4:7 s8 s8 | g8 s4. s4 s8 s8 | d8 s8 s8 s8 a4:7 s4 | d1 | d4. s8 d4:7 s4 | g4. s8 s4 s4 | a4. s8 a8:7 s8 s8 s8 | d4 s4 a2:7 | d4. s8 d4:7 s4 | g4. s8 s4 s4 | a4. s8 a8:7 s8 s8 s8 | d4 g2 d4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "We" "have" "oil" "in" "our" "lamps—" "we" "are" "burn" -- "ing!" _ "We" "have" "oil" "in" "our" "lamps" "to" -- "day!" "To" "the" "spir" -- "it," "O" "Lord," "keep" "us" "turn" -- "ing," _ "Keep" "us" "turn" -- "ing," "turn" -- "ing" "all" "the" "way!" "O" "Lord!" "A" -- "men!" "Hal" -- "le" -- "lu" -- "jah!" "We" "are" "burn" -- "ing," "burn" -- "ing" "ev" -- "ery" "day!" "O" "Lord!" "A" -- "men!" "Hal" -- "le" -- "lu" -- "jah!" "Turn" -- "ing," "turn" -- "ing" "all" "the" "way!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "But our vessels need oil for Thy coming;" "We must gain a reserve supply." "So our vessels we give for the filling" "That our lamps may never, never die." \translate #'(3.25 . -2.00) "Fill us, Jesus! Fill us, Jesus!" \translate #'(3.25 . -2.00) "Every moment give us more of Thee!" \translate #'(3.25 . -2.00) "Fill us, Jesus! Fill us, Jesus!" \translate #'(3.25 . -2.00) "Fill us with reality!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Then we’ll burn till the Lord comes to meet us," "Then we’ll burn till He comes that day." "Then we’ll go in with Him to the wedding" "And be brightly burning all the way." \translate #'(3.25 . -2.00) "Come, Lord Jesus! Come, Lord Jesus!" \translate #'(3.25 . -2.00) "Come and find us filled and burning bright!" \translate #'(3.25 . -2.00) "Come, Lord Jesus! Come, Lord Jesus!" \translate #'(3.25 . -2.00) "Come and in Thy Bride delight." } }
    } \hspace #1.1 }
    \null
  }
}
