\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E191.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 12.34) (minimum-distance . 12.34) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Lord, Thou art the Seed of woman"
  subtitle = "Praise of the Lord — His All-Inclusiveness"
  opus = "191"
}

global = {
  \key aes \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  aes'4. aes'8 aes'4 aes'4 | c''4. bes'8 bes'8([ aes'8)] aes'4 | bes'4. bes'8 bes'4 bes'4 | des''4. c''8 c''4( bes'4) \break | aes'4. aes'8 aes'4 aes'4 | c''4. bes'8 bes'8([ aes'8)] aes'4 | bes'4 bes'4 bes'8([ des''8) c''8( bes'8)] | aes'4 g'4 aes'2 \break | bes'4. bes'8 bes'4 bes'4 | bes'4. aes'8 aes'8([ g'8)] g'4 | c''4. c''8 c''4 c''4 | des''4. c''8 c''4( bes'4) \break | aes'4. aes'8 aes'4 aes'4 | c''4. bes'8 bes'8([ aes'8)] aes'4 | bes'4 bes'4 bes'8([ des''8) c''8( bes'8)] | aes'4 g'4 aes'2 \bar "|."
}

harmonies = \chordmode {
  \global
  g4. s8 s4 s4 | s4. s8 s8 s8 s4 | d4. s8 s4 s4 | d4.:7 s8 s4 s4 | g4. s8 s4 s4 | s4. s8 s8 s8 s4 | d4 s4 s8 s8 s8 s8 | g4 d4:7 g2 | d4. s8 s4 s4 | d4.:7 s8 s8 s8 s4 | g4. s8 s4 s4 | c4. s8 d4 s4 | g4. s8 s4 s4 | s4. s8 s8 s8 s4 | d4 s4 s8 s8 s8 s8 | g4 d4:7 g2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Lord," "Thou" "art" "the" "“Seed" "of" "wo" -- _ "man,”" "Born" "to" "bruise" "the" -- "e" -- "ne" -- "my;" _ "Thou" "didst" "take" "the" "hu" -- "man" "na" -- _ "ture," "Die" "to" "win" _ "the" _ "vic" -- "to" -- "ry." "As" "the" "ve" -- "ry" "God" "in" -- "car" -- _ "nate," "Flesh" "and" "blood" "Thou" "didst" "par" -- "take;" _ "Thou" "thru" "death" "hast" "crushed" "the" "de" -- _ "vil" "And" "his" _ "pow’r" "of" _ "death" "didst" "break."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "“Seed of Abraham,” Thou art, Lord," "By God’s promise Thou hast come," "That the blessing He hath promised" "On all people thus might come." "Abraham Thou hast preceded," "For Thou art the great “I AM,”" "Yet Thou cam’st to be his offspring" "And become God’s promised “Lamb.”" } }
      \vspace #0.88
      \line { \bold "3." \column { "Lord, Thou art the “Seed of David,”" "For the kingdom Thou wast raised;" "For God’s glory and His building" "On the throne Thou hast been placed." "Truly Thou art “David’s offspring,”" "Yet “my Lord” he calleth Thee," "For Thou art his “root” and fountain," "“Lord of all” eternally." } }
    }
    \left-column {
      \line { \bold "4." \column { "Though “a child” born with our nature," "Thou the “Mighty God” art called;" "Thou, “a son” to us art given," "“Everlasting Father” called." "All the blessings God hath promised," "With our faith on Thee depend;" "Thou art “Yea” and “Amen” for them," "All the content and the end!" } }
    }
  }
}
