\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E226.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 12.21) (minimum-distance . 12.21) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "For the bread and for the wine"
  subtitle = "Praise of the Lord — Remembrance of Him"
  opus = "226"
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  b'4. b'8 b'4 b'4 | d''4 c''4 b'2 | a'4. a'8 a'4 a'4 | c''4 b'4 a'2 \break | g'4. g'8 a'4 a'4 | b'4. a'8 g'2 | a'2 e'4 fis'4 | a'4. g'8 g'2 \bar "|."
}

harmonies = \chordmode {
  \global
  g4. s8 s4 s4 | s4 d4:7 g2 | a4.:m s8 s4 s4 | d4:7 g4 d2 | e4.:m s8 c4 s4 | b4.:7 s8 e2:m | a2:m s4 s4 | d4.:7 s8 g2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "For" "the" "bread" "and" "for" "the" "wine," "For" "the" "pledge" "that" "seals" "Him" "mine," "For" "the" "words" "of" "love" "di" -- "vine," "We" "give" "Thee" "thanks," "O" "Lord."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Only bread and only wine," "Yet to faith, the solemn sign" "Of the heav’nly and divine!" "We give Thee thanks, O Lord." } }
      \vspace #0.88
      \line { \bold "3." \column { "For the words that turn our eye" "To the cross of Calvary," "Bidding us in faith draw nigh," "We give Thee thanks, O Lord." } }
      \vspace #0.88
      \line { \bold "4." \column { "For the words that fragrance breathe" "These plain symbols underneath," "Words that His own peace bequeath," "We give Thee thanks, O Lord." } }
      \vspace #0.88
      \line { \bold "5." \column { "For Thy words in Spirit, shown," "For Thy will to us made known," "“Do ye this until I come,”" "We give Thee thanks, O Lord." } }
      \vspace #0.88
      \line { \bold "6." \column { "Till He come we take the bread," "Type of Him on whom we feed," "Him who liveth and was dead!" "We give Thee thanks, O Lord." } }
      \vspace #0.88
      \line { \bold "7." \column { "Till He come we take the cup;" "As we at His table sup," "Eye and heart are lifted up!" "We give Thee thanks, O Lord." } }
      \vspace #0.88
      \line { \bold "8." \column { "For that coming, here foreshown," "For that day to man unknown," "For the glory and the throne," "We give Thee thanks, O Lord." } }
    } \hspace #1.1 }
    \null
  }
}
