\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E29.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.01
  }
  system-system-spacing = #'((basic-distance . 12.46) (minimum-distance . 12.46) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "What was it, blessed God"
  subtitle = "Worship of the Father — His Love"
  opus = "29"
}

global = {
  \key g \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  d'4 | g'2 b'4 | a'4( b'4) c''4 | b'2.~ | b'2 g'4 | e'4( fis'4) g'4 | c''2 b'4 | b'2.( \break | a'2) d'4 | d'4( e'4) fis'4 | g'4( a'4) b'4 | c''2.~ | c''2 a'4 | b'2 g'4 | a'4( g'4) fis'4 | g'2.~ \break | g'2 b'8([ a'8)] | g'2 g'4 | g'4( fis'4) e'4 | e'2 d'4 | d'2 b'8([ a'8)] | g'2 g'4 | g'4( fis'4) e'4 | e'2 d'4 | d'2 b'4 \break | c''2 a'4 | b'2 g'4 | a'4( g'4) fis'4 | g'2.~ | g'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 | s2 s4 | d4 s4 s4 | e2.:m | g2 s4 | c4 s4 s4 | a2:m s4 | g2. | d2 s4 | s4 s4 s4 | e4:m s4 s4 | a2.:m | s2 s4 | g2 s4 | d4:7 s4 s4 | g2 c4 | g2 s8 s8 | s2 s4 | c4 s4 s4 | g2 s4 | s2 s8 s8 | s2 s4 | c4 s4 s4 | g2 s4 | e2:m s4 | a2:m s4 | g2 s4 | c4 s4 d4 | g2 c4 | g2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "What" "was" "it," "bless" -- _ "ed" "God," _ "Led" "Thee" _ "to" "give" "Thy" "Son," _ "To" "yield" _ "Thy" "Well-" -- _ "be" -- "loved" _ "For" "us" "by" "sin" _ "un" -- "done?" _ _ "’Twas" "love" "un" -- _ "bound" -- "ed" "led" "Thee" "thus," _ "’Twas" "love" "un" -- _ "bound" -- "ed" "led" "Thee" "thus," "To" "give" "Thy" "Well-" -- "be" -- "loved" _ "for" "us." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "What led Thy Son, O God," "To leave Thy throne on high," "To shed His precious blood," "To suffer and to die?" "’Twas love—unbounded love to us," "’Twas love—unbounded love to us" "Led Him to die and suffer thus." } }
      \vspace #0.88
      \line { \bold "3." \column { "What moved Thee to impart" "Thy Spirit from above," "Therewith to fill our heart" "With heavenly peace and love?" "’Twas love—unbounded love to us," "’Twas love—unbounded love to us" "Moved Thee to give Thy Spirit thus." } }
      \vspace #0.88
      \line { \bold "4." \column { "What love to Thee we owe," "Our God, for all Thy grace!" "Our hearts may well o’erflow" "In everlasting praise!" "Make us, O God, to praise Thee thus," "Make us, O God, to praise Thee thus" "For all Thy boundless love to us." } }
    } \hspace #1.1 }
    \null
  }
}
