\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E398.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.02
  }
  system-system-spacing = #'((basic-distance . 14.09) (minimum-distance . 14.09) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.89) (minimum-distance . 14.89) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "O to be like Thee"
  subtitle = "Longings — For Likeness to Christ"
  opus = "398"
}

global = {
  \key c \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  \tuplet 3/2 { c'8[ e'8 g'8] } | g'4 g'4 \tuplet 3/2 { a'8[ b'8 c''8] } | g'4 e'4 \tuplet 3/2 { c'8[ e'8 g'8] } | g'4 e'4 \tuplet 3/2 { e'8[ f'8 e'8] } \break | d'2 \tuplet 3/2 { c'8[ e'8 g'8] } | g'4 g'4 \tuplet 3/2 { a'8[ b'8 c''8] } | g'4 e'4 \tuplet 3/2 { g'8[ f'8 e'8] } | d'4 c''4 \tuplet 3/2 { c''8[ b'8 a'8] } \break | g'2^\fermata \tuplet 3/2 { g'8[ fis'8^\markup { \box \bold "Chorus" } g'8] } | a'4 f'4 \tuplet 3/2 { c''8[ b'8 a'8] } | a'4 g'4 \tuplet 3/2 { g'8[ f'8 e'8] } | f'4 f'4 \tuplet 3/2 { a'8[ g'8 f'8] } \break | e'2 \tuplet 3/2 { g'8[ fis'8 g'8] } | a'4 f'4 \tuplet 3/2 { c''8[ b'8 a'8] } | a'4 g'4 \tuplet 3/2 { c'8[ e'8 g'8] } | g'4 e'4 \tuplet 3/2 { e'8[ c'8 d'8] } | c'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  \tuplet 3/2 { c8 s8 s8 } | s4 s4 \tuplet 3/2 { f8 s8 s8 } | c4 s4 \tuplet 3/2 { s8 s8 s8 } | s4 s4 \tuplet 3/2 { s8 s8 s8 } | g2 \tuplet 3/2 { s8 s8 s8 } | c4 s4 \tuplet 3/2 { f8 s8 s8 } | c4 s4 \tuplet 3/2 { s8 s8 s8 } | d4:7 s4 \tuplet 3/2 { s8 s8 s8 } | g2 \tuplet 3/2 { c8 s8 s8 } | f4 s4 \tuplet 3/2 { s8 s8 s8 } | c4 s4 \tuplet 3/2 { s8 s8 s8 } | g4 s4 \tuplet 3/2 { g8:7 s8 s8 } | c2 \tuplet 3/2 { c8:7 s8 s8 } | f4 s4 \tuplet 3/2 { s8 s8 s8 } | c4 s4 \tuplet 3/2 { s8 s8 s8 } | s4 s4 \tuplet 3/2 { g8:7 s8 s8 } | c2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "O" "to" "be" "like" "Thee!" "bless" -- "ed" "Re" -- "deem" -- "er;" "This" "is" "my" "con" -- "stant" "long" -- "ing" "and" "prayer;" "Glad" -- "ly" "I’ll" "for" -- "feit" "all" "of" "earth’s" "trea" -- "sures," "Je" -- "sus," "Thy" "per" -- "fect" "like" -- "ness" "to" "wear." \set stanza = "(C)" "O" "to" "be" "like" "Thee!" "O" "to" "be" "like" "Thee!" "Bless" -- "ed" "Re" -- "deem" -- "er," "pure" "as" "Thou" "art;" "Come" "in" "Thy" "sweet" -- "ness," "come" "in" "Thy" "full" -- "ness;" "Stamp" "Thine" "own" "i" -- "mage" "deep" "on" "my" "heart."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "O to be like Thee! full of compassion," "Loving, forgiving, tender and kind," "Helping the helpless, cheering the fainting," "Seeking the wand’ring sinners to find." } }
      \vspace #0.88
      \line { \bold "3." \column { "O to be like Thee! lowly in spirit," "Holy and harmless, patient and brave;" "Meekly enduring cruel reproaches," "Willing to suffer, others to save." } }
      \vspace #0.88
      \line { \bold "4." \column { "O to be like Thee! Lord, I am coming," "Now to receive th’ anointing divine;" "All that I am and have I am bringing;" "Lord, from this moment all shall be Thine." } }
      \vspace #0.88
      \line { \bold "5." \column { "O to be like Thee! While I am pleading" "Pour out Thy Spirit, fill with Thy love." "Make me a temple meet for Thy dwelling," "Fit for a life which Thou wouldst approve." } }
    } \hspace #1.1 }
    \null
  }
}
