\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E43.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.94) (minimum-distance . 12.94) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Abba, Father, we approach Thee"
  subtitle = "Worship of the Father — His Redemption"
  opus = "43"
}

global = {
  \key ees \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  ees'4. f'8 g'4 f'4 | aes'4 g'4 f'8([ d'8)] ees'4 | c''4 bes'4 aes'4 g'4 | f'4 g'8([ ees'8)] bes'2 \break | ees'4. f'8 g'4 f'4 | aes'4 g'4 f'8([ d'8)] ees'4 | c''4 bes'4 aes'4 g'4 | f'4 g'8([ ees'8)] bes'2 \break | f'4 g'4 f'8([ d'8)] bes4 | aes'4 g'4 f'8([ d'8)] bes4 | bes'4 aes'4 g'4. g'8 | a'4. a'8 bes'2 \break | ees''4. d''8 c''4 bes'4 | c''4. bes'8 bes'8([ aes'8)] g'4 | f'4 g'8([ aes'8)] bes'8([ c''8) aes'8( f'8)] | ees'4 g'8([ f'8)] ees'2 \bar "|."
}

harmonies = \chordmode {
  \global
  d4. s8 s4 s4 | g4 s4 a8 s8 d4 | g4 s4 s4 s4 | e4:7 s8 s8 a2 | d4. s8 s4 s4 | g4 s4 a8 s8 d4 | g4 s4 s4 s4 | e4:7 s8 s8 a2 | a4 s4 s8 s8 s4 | s4 s4 s8 s8 s4 | d4 s4 s4. s8 | e4.:7 s8 a2 | d4. s8 s4 s4 | g4. s8 d8 s8 s4 | a4 s8 s8 d8 s8 s8 s8 | a4 a8:7 s8 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "“Ab" -- "ba," "Fa" -- "ther,”" "we" "ap" -- _ "proach" "Thee" "In" "our" "Sav" -- "ior’s" "pre" -- _ "cious" "name." "We," "Thy" "child" -- "ren," "here" "as" -- "sem" -- _ "bling," "Now" "the" "prom" -- "ised" "bless" -- "ing" _ "claim." "From" "our" "guilt" _ "His" "blood" "has" _ "washed" "us," "’Tis" "through" "Him" "our" "souls" "draw" "nigh," "And" "Thy" "Spir" -- "it" "too" "has" _ "taught" "us" "“Ab" -- "ba," _ "Fa" -- _ _ "ther,”" "thus" "to" _ "cry."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Once as prodigals we wandered," "In our folly, far from Thee;" "But Thy grace, o’er sin abounding," "Rescued us from misery." "Clothed in garments of salvation" "At Thy table is our place;" "We rejoice, and Thou rejoicest," "In the riches of Thy grace." } }
      \vspace #0.88
      \line { \bold "3." \column { "Thou the prodigal hast pardoned," "“Kissed us” with a Father’s love;" "“Killed the fatted calf,” and made us" "Fit Thy purpose to approve." "“It is meet,” we hear Thee saying," "“We should merry be and glad;" "I have found My once-lost children," "Now they live who once were dead.”" } }
    }
    \left-column {
      \line { \bold "4." \column { "“Abba, Father,” we adore Thee," "While the hosts in heaven above" "E’en in us now learn the wonders" "Of Thy wisdom, grace, and love." "Soon before Thy throne assembled," "All Thy children shall proclaim" "Abba’s love shown in redemption," "And how full is Abba’s name!" } }
    }
  }
}
