\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E523.svg

#(set-global-staff-size 14.500)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.37\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 13.06) (minimum-distance . 13.06) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.97) (minimum-distance . 14.97) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I have come to the Fountain of Life"
  subtitle = "Experience of Christ — As Everything"
  opus = "523"
}

global = {
  \key c \major
  \time 6/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'8[ d'8] | e'4 f'4 e'4 d'4 e'4 d'4 | c'2.~ c'2 g'4 | a'4 g'4 g'4 c''4 e'4 fis'4 \break | g'2.~ g'2 g'8[ f'8] | e'4 f'4 e'4 d'4 e'4 d'4 | c'2.( g'2) f'4 | e'4 e'4 f'4 g'4 c'4 d'4 \break | c'2.~ c'2 g'8[ g'8] | a'4 a'4 a'4 c''4. b'8 a'4 | g'2.( c''4) c''4 c''4 | d''4 c''4 d''4 e''4 c''4 a'4 \break | g'2.~ g'2 g'8([ f'8)] | e'4 f'4 e'4 d'4 e'4 d'4 | c'2.( g'2) g'4 | c''4 e'4 f'4 g'4 c'4 d'4 \break | c'2.~ c'2 g'4^\markup { \box \bold "Chorus" } | c''4. c''8 c''4 d''4 c''4 a'4 | g'2.( e'2) g'4 | a'4 g'4 g'4 c''4 e'4 fis'4 \break | g'2.~ g'2 g'8([ f'8)] | e'4 f'4 e'4 d'4 e'4 d'4 | c'2.( g'2) g'4 | c''4 e'4 f'4 g'4 c'4 d'4 | c'2.~ c'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c8 s8 | s4 s4 s4 g4 s4 s4 | a2.:m c2 s4 | f4 s4 s4 a4:m s4 d4:7 | g2. g2:7 s8 s8 | c4 s4 s4 g4 s4 s4 | a2.:m c2 f4 | c4 s4 s4 g4:7 s4 s4 | c2 f4 c2 s8 s8 | f4 s4 s4 s4. s8 s4 | c2. s4 s4 s4 | g4 s4 s4 c4 s4 f4 | g2. g2:7 s8 s8 | c4 s4 s4 g4 s4 s4 | a2.:m c2 f4 | c4 s4 s4 g4:7 s4 s4 | c2 f4 c2 s4 | s4. s8 s4 f4 s4 s4 | c2. s2 s4 | f4 s4 c4 a4:m s4 d4:7 | g2. g2:7 s8 s8 | c4 s4 s4 g4 s4 s4 | a2.:m c2 f4 | c4 s4 s4 g4:7 s4 s4 | c2 f4 c2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "I" "have" "come" "to" "the" "Foun" -- "tain" "of" "Life," _ "A" "foun" -- "tain" "that" "flows" "from" "a" -- "bove;" _ "I" "have" "passed" "from" "the" "wa" -- "ters" "of" "strife" _ "And" "come" "to" "the" "E" -- "lim" "of" "love;" _ "I" "have" "drunk" "of" "the" "heav" -- "en" -- "ly" "well," _ "In" "the" "depths" "of" "my" "be" -- "ing" "it" "springs." _ "No" _ "mor" -- "tal" "can" "mea" -- "sure" "or" "tell" _ "The" "glad" -- "ness" "the" "Com" -- "fort" -- "er" "brings." _ \set stanza = "(C)" "Oh," "come" "to" "the" "Foun" -- "tain" "of" "Life," _ "The" "foun" -- "tain" "that" "nev" -- "er" "runs" "dry;" _ "Oh," _ "drink" "of" "the" "bound" -- "less" "sup" -- "ply," _ "For" "Christ" "is" "the" "Foun" -- "tain" "of" "Life." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "I have come to the Fountain of Blood" "That for guilt and uncleanness doth flow;" "I have washed in its sin-cleansing flood" "And my garments are whiter than snow." "I count not my righteousness mine—" "’Tis Jesus that lives in my soul." "I partake of His nature divine," "And in Him I am perfectly whole." } }
      \vspace #0.88
      \line { \bold "3." \column { "I have come to the Fountain of Health," "A boundless and endless supply;" "’Tis a secret man’s wisdom or wealth" "Can never discover or buy." "But the secret my Lord hath revealed" "In the fountain that flows from His side," "In the stripes by whose pain we are healed," "In Himself as He comes to abide." } }
    }
    \left-column {
      \line { \bold "4." \column { "I have come to the Fountain of Joy;" "His joy is the strength of my heart." "My delight is unmixed with alloy," "My sunshine can never depart." "The fig tree may wither and die," "Earth’s pleasures and prospects decline;" "But my fountains can never be dry—" "My portion, my joy is divine." } }
    }
  }
}
