\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E714.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.90
  }
  system-system-spacing = #'((basic-distance . 12.22) (minimum-distance . 12.22) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Through all the changing scenes of life"
  subtitle = "Comfort in Trials — By Trusting the Lord"
  opus = "714"
}

global = {
  \key aes \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  ees'4 | ees'2 aes'4 | aes'4( g'4) aes'4 | des''4( c''4) bes'4 | bes'4( c''4) ees'4 | ees'2 ees'4 | ees'4( c''4) aes'4 | aes'4( g'4)^\fermata bes'4 \break | aes'2 g'4 | aes'2 bes'4 | c''4( des''4) c''4 | c''4( bes'4) c''8([ aes'8)] | f'2 bes'4 | g'4.( f'8) g'4 | aes'2.~ | aes'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 | s2 d4 | g4 s4 s4 | d4:7 s4 d4 | e4:m s4 d4 | g2 d4 | g4 s4 s4 | d4 s4 s4 | e2:m b4 | e2:m d4 | g4 s4 s4 | d4 s4 g8 s8 | c2 a4:m | d4. s8 d4:7 | g2 c4 | g2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Through" "all" "the" _ "chang" -- "ing" _ "scenes" "of" "life," _ "In" "trou" -- "ble" "and" _ "in" "joy," _ "The" "prais" -- "es" "of" "my" "God" _ "shall" "still" _ "My" _ "heart" "and" "tongue" _ "em" -- "ploy." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Oh, magnify the Lord with me," "With me exalt His name;" "When in distress to Him I called," "He to my rescue came." } }
      \vspace #0.88
      \line { \bold "3." \column { "The hosts of God encamp around" "The dwellings of the just;" "Deliverance He affords to all" "Who on His succor trust." } }
      \vspace #0.88
      \line { \bold "4." \column { "Oh, make but trial of His love," "Experience will decide" "How blest they are, and only they," "Who in His truth confide." } }
      \vspace #0.88
      \line { \bold "5." \column { "Fear Him, ye saints, and you will then" "Have nothing else to fear;" "Make you His service your delight," "Your wants shall be His care." } }
    } \hspace #1.1 }
    \null
  }
}
