\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E74.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.90
  }
  system-system-spacing = #'((basic-distance . 12.56) (minimum-distance . 12.56) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "There is a name to Jesus given"
  subtitle = "Praise of the Lord — His Name"
  opus = "74"
}

global = {
  \key bes \major
  \time 3/2
  \autoBeamOff
  \partial 2.
}

melody = {
  \clef treble
  \global
  f'4 d'4 ees'4 | f'2. bes'4 c''4 bes'4 | a'2 g'4 bes'4 a'4 bes'4 | c''2. g'4 a'4 g'4 \break | f'2. f'4 d'4 ees'4 | f'2. bes'4 c''4 bes'4 | a'2 g'4 c''4 bes'4 g'4 | f'2. bes'4 c''4. bes'8 \break | bes'2. bes'4 a'4 bes'4 | c''2. g'4 a'4 g'4 | f'2 bes'2 bes'2 | bes'4. g'8 g'4 bes'4 d''4. c''8 \break | c''2 r4 f'4 d''4 bes'4 | f'2. bes'4 c''4 bes'4 | bes'2 g'4 c''4 bes'4 g'4 | f'2. bes'4 c''4. bes'8 | bes'2.^\fermata r2. \bar "|."
}

harmonies = \chordmode {
  \global
  d4 s4 s4 | g2. s4 s4 s4 | c2 s4 s4 s4 s4 | a2. s4 s4 s4 | d2. s4 d4:7 s4 | g2. s4 s4 s4 | c2 s4 s4 a4:m s4 | g2. s4 d4.:7 s8 | g2. s4 s4 s4 | a2.:m s4 a4 s4 | g2 c2 g2 | a4. s8 s4 s4 a4.:7 s8 | d2 s4 s4 g4 s4 | d2. s4 g4 s4 | c2 s4 s4 a4 s4 | g2. s4 d4.:7 s8 | c2 g4 s2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "There" "is" "a" "name" "to" "Je" -- "sus" "giv" -- "en," "His" "match" -- "less" "love" "its" "ac" -- "cents" "tell;" "For" "it" "de" -- "clares:" "He" "is" "my" "Broth" -- "er," "And" "this" "His" "name—" "Em" -- "man" -- "u" -- "el!" "The" "Lord," "by" "an" -- "gels" "wor" -- "shiped" "yon" -- "der," "Has" "stooped" "to" "earth" "with" "men" "to" "dwell," "In" -- "car" -- "nate" "God," "and" "man" "for" -- "ev" -- "er—" "Our" "own" "be" -- "loved" "Em" -- "man" -- "u" -- "el."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "There is a name that’s still more precious," "That stirs our hearts with fondest love:" "It is the charming name of Jesus," "The name all other names above." "It tells me that He is my Savior" "From sin and sickness and the grave." "I love the precious name of Jesus," "For I am one He came to save!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Though dear to us the name of Jesus," "The name of Christ is higher still!" "It tells of Him who dwells within us," "Our old heart to renew and fill." "It tells me of the Spirit’s fullness," "It brings the pow’r of Pentecost." "O blessed Christ, anoint me also," "And fill me with the Holy Ghost!" } }
    } \hspace #1.1 }
    \null
  }
}
