\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E806.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.03) (minimum-distance . 12.03) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Break Thou the Bread of Life"
  subtitle = "Study of the Word — Seeking for the Word"
  opus = "806"
}

global = {
  \key d \major
  \time 2/2
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  fis'2 d'4 fis'4 | a'4 b'4 a'2 | fis'2 d'4 fis'4 | e'1 \break | fis'2 d'4 fis'4 | a'4 b'4 a'4 b'4 | cis''2 b'2 | a'1 \break | e'2 fis'4 g'4 | b'4 a'4 fis'2 | a'2 b'4 b'4 | cis''1 \break | d''2 a'4 fis'4 | e'4 g'4 b'4 g'4 | e'2 a'2 | d'1 \bar "|."
}

harmonies = \chordmode {
  \global
  d2 s4 s4 | s4 s4 s2 | s2 s4 s4 | a2 a2:7 | d2 s4 s4 | s4 s4 s4 s4 | e2 e2:7 | a1 | a2:7 s4 s4 | d4 s4 s2 | s2 e4:7 s4 | a1 | d2 s4 s4 | e4:m s4 s4 s4 | a2 a2:7 | d1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Break" "Thou" "the" "Bread" "of" "Life," "Dear" "Lord," "to" "me," "As" "Thou" "didst" "break" "the" "loaves" "Be" -- "side" "the" "sea;" "Be" -- "yond" "the" "sa" -- "cred" "page" "I" "seek" "Thee," "Lord;" "My" "spir" -- "it" "pants" "for" "Thee," "O" "Liv" -- "ing" "Word."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Thou art the Bread of Life," "O Lord, to me," "Thy holy Word the truth" "That saveth me;" "Give me to eat and live" "With Thee above;" "Teach me to love Thy truth," "For Thou art Love." } }
      \vspace #0.88
      \line { \bold "3." \column { "Oh, send Thy Spirit, Lord," "Now unto me," "That He may touch my eyes," "And make me see;" "Show me the truth concealed" "Within Thy Word," "And in Thy Book revealed" "I see the Lord." } }
    }
    \left-column {
      \line { \bold "4." \column { "Bless Thou the truth, dear Lord," "To me, to me," "As Thou didst bless the bread" "By Galilee;" "Then shall all bondage cease," "All fetters fall," "And I shall find my peace," "My All in all." } }
    }
  }
}
