\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E84.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.91
  }
  system-system-spacing = #'((basic-distance . 12.22) (minimum-distance . 12.22) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Hark! the herald angels sing"
  subtitle = "Praise of the Lord — His Incarnation"
  opus = "84"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  c'4 f'4 f'4. e'8 | f'4 a'4 a'4( g'4) | c''4 c''4 c''4. bes'8 | a'4 g'4 a'2 \break | c'4 f'4 f'4. e'8 | f'4 a'4 a'4( g'4) | c''4 g'4 g'4. e'8 | e'4 d'4 c'2 \break | c''4 c''4 c''4 f'4 | bes'4 a'4 a'4( g'4) | c''4 c''4 c''4 f'4 | bes'4 a'4 a'4 g'4 \break | d''4 d''4 d''4 c''4 | bes'4 a'4 bes'2 | g'4 a'8([ bes'8)] c''4. f'8 | f'4 g'4 a'2 \break | d''4. d''8 d''4 c''4 | bes'4 a'4 bes'2 | g'4 a'8([ bes'8)] c''4. f'8 | f'4 g'4 f'2 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 s4 s4. s8 | s4 s4 a4 s4 | s4 s4 s4. s8 | s4 s4 d2 | d4 s4 s4. s8 | s4 s4 a4 s4 | s4 s4 s4. s8 | e4:7 s4 a2 | d4 s4 s4 s4 | g4 s4 a4 s4 | d4 s4 s4 s4 | g4 s4 a4 s4 | g4 s4 s4 s4 | s4 s4 a2 | s4 s8 s8 d4. s8 | a4 a4:7 d2 | g4. s8 s4 s4 | s4 s4 a2 | a4:7 s8 s8 d4. s8 | a4 a4:7 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Hark!" "the" "her" -- "ald" "an" -- "gels" "sing," _ "“Glo" -- "ry" "to" "the" "new-" -- "born" "King;" "Peace" "on" "earth," "and" "mer" -- "cy" "mild;" _ "God" "and" "sin" -- "ners" "re" -- "con" -- "ciled.”" "Joy" -- "ful," "all" "ye" "na" -- "tions," "rise," _ "Join" "the" "tri" -- "umph" "of" "the" "ski" -- "es;" "With" "an" -- "ge" -- "lic" "hosts" "pro" -- "claim," "“Christ" "is" _ "born" "in" "Beth" -- "le" -- "hem.”" "With" "an" -- "ge" -- "lic" "hosts" "pro" -- "claim," "“Christ" "is" _ "born" "in" "Beth" -- "le" -- "hem.”"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Christ, by highest heav’n adored," "Christ, the everlasting Lord:" "Late in time behold Him come," "Offspring of a virgin’s womb." "Veiled in flesh the Godhead see," "Hail th’ incarnate Deity!" "Pleased as man with man to dwell," "Jesus our Immanuel." } }
      \vspace #0.88
      \line { \bold "3." \column { "Hail the heav’n-born Prince of Peace!" "Hail the Sun of righteousness!" "Light and life to all He brings," "Ris’n with healing in His wings:" "Mild He lays His glory by," "Born that man no more may die;" "Born to raise the sons of earth;" "Born to give them second birth." } }
    }
    \left-column {
      \line { \bold "4." \column { "Come, Desire of nations, come!" "Fix in us Thy humble home:" "Rise, the woman’s conqu’ring seed," "Bruise in us the serpent’s head;" "Adam’s likeness now efface," "Stamp Thine image in its place:" "Final Adam from above," "Reinstate us in Thy love." } }
    }
  }
}
