\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E855.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.06
  }
  system-system-spacing = #'((basic-distance . 14.12) (minimum-distance . 14.12) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Behold, how good, how pleasant ’tis"
  subtitle = "The Church — Her Fellowship"
  opus = "855"
}

global = {
  \key a \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  e'4 | e'4( fis'4) e'4 | e'4( fis'4) e'4 | e'2 a'4 | e'2 cis'4 | cis'2 cis'4 | e'4( d'4) cis'4 \break | b2^\fermata e'4 | e'4( fis'4) e'4 | e'4( fis'4) e'4 | e'2 a'4 | cis''2 b'4 | a'2 a'4 | gis'4( fis'4) gis'4 \break | a'2 e'4^\markup { \box \bold "Chorus" } | b'2 ais'4 | b'2 bis'4 | cis''2 b'4 | a'2 e'4 | b'2 ais'4 | b'2 cis''4 \break | d''2^\fermata e'4 | e'4( fis'4) e'4 | e'4( fis'4) e'4 | e'2 a'4 | cis''2 b'4 | a'2 a'4 | gis'4( fis'4) gis'4 | a'2.~ | a'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  a4 | s4 s4 s4 | e4 s4 s4 | a2 s4 | s2 s4 | s2 s4 | s4 s4 s4 | e2 s4 | a4 s4 s4 | e4 s4 s4 | a2 s4 | s2 s4 | s2 s4 | e4:7 s4 s4 | a2 s4 | e2 s4 | s2 s4 | a2 s4 | s2 s4 | e2 s4 | b2:7 s4 | e2:7 s4 | a4 s4 s4 | e4 s4 s4 | a2 s4 | s2 s4 | s2 s4 | e4:7 s4 s4 | a2. | s2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Be" -- "hold," _ "how" "good," _ "how" "plea" -- "sant" "’tis" "When" "breth" -- "ren" "dwell" _ "in" "one!" "’Tis" "like" _ "the" "oil" _ "on" "Aa" -- "ron’s" "head," "Which" "to" "his" "skirts" _ "did" "run;" \set stanza = "(C)" "As" "dew" "of" "Her" -- "mon" "that" "des" -- "cends" "On" "Zi" -- "on’s" "moun" -- "tains" "o’er;" "The" "Lord" _ "His" "bless" -- _ "ing" "there" "com" -- "mands," "E’en" "life" "for" -- "ev" -- _ "er" -- "more." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

