\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E872.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.86
  }
  system-system-spacing = #'((basic-distance . 12.56) (minimum-distance . 12.56) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Fight the good fight with all thy might"
  subtitle = "Spiritual Warfare — Fighting On"
  opus = "872"
}

global = {
  \key g \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  b'4 b'4 b'4 | b'2 b'4 | a'2 g'4 | c''2. | b'4 b'4 b'4 | b'2 a'4 | a'2 g'4 | a'2. \break | b'4 b'4 b'4 | b'2 b'4 | a'2 b'4 | c''2. | a'4 a'4 a'4 | b'2 g'4 | g'2 fis'4 | g'2. \bar "|."
}

harmonies = \chordmode {
  \global
  g4 s4 s4 | s2 s4 | d2 g4 | c2. | g4 s4 s4 | e2:m s4 | a2:7 s4 | d2. | g4 s4 s4 | g2:7 s4 | a2:m g4 | c2. | d4 s4 s4 | g2 c4 | g2 d4:7 | g2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Fight" "the" "good" "fight" "with" "all" "thy" "might!" "Christ" "is" "thy" "strength," "and" "Christ" "thy" "right;" "Lay" "hold" "on" "life," "and" "it" "shall" "be" "Thy" "joy" "and" "crown" "e" -- "ter" -- "nal" -- "ly."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Run the straight race through God’s good grace," "Lift up thine eyes, and seek His face;" "Life with its way before us lies," "Christ is the path, and Christ the prize." } }
      \vspace #0.88
      \line { \bold "3." \column { "Cast care aside, lean on thy Guide;" "His boundless mercy will provide;" "Trust, and thy trusting soul shall prove" "Christ is its life, and Christ its love." } }
      \vspace #0.88
      \line { \bold "4." \column { "Faint not nor fear, His arms are near," "He changeth not, and thou art dear;" "Only believe, and thou shalt see" "That Christ is all in all to thee." } }
    } \hspace #1.1 }
    \null
  }
}
