\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E91.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #1.01
  }
  system-system-spacing = #'((basic-distance . 12.86) (minimum-distance . 12.86) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.97) (minimum-distance . 14.97) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "It was alone the Savior prayed"
  subtitle = "Praise of the Lord — His Suffering"
  opus = "91"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 4.
}

melody = {
  \clef treble
  \global
  f'8 f'8.[ g'16] | a'2~ a'8[ f'8 bes'8. f'16] | a'2. a'4 | c''2~ c''8[ bes'8 g'8 gis'8] \break | a'2~ a'8[ f'8 f'8. g'16] | a'2~ a'8[ c''8 c''8. f'16] | f'2. bes'4 | a'4. c'8 g'4. c'8 \break | f'2. f'4^\markup { \box \bold "Chorus" } | bes'2. f'4 | a'2. a'4 | g'4. f'8 g'4 a'4 | g'2. bes'4 \break | a'4. a'8 bes'8[ bes'8 c''8 c''8] | d''2. f'4 | f'16 a'8.[ bes'8^\fermata a'8] g'8[^\fermata d'8 g'8^\fermata c'8] | f'2~ f'8 r4. \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8. s16 | s2 g8:m s8 s8. s16 | d2 b4:m s4 | e2:m a8 s8 s8 s8 | d2 g8:m s8 s8. s16 | d2 d8:7 s8 s8. s16 | g2 e4:m s4 | d4. s8 a4.:7 s8 | d2 d4:7 s4 | g2. s4 | d2. s4 | e4. s8 e4:7 s4 | a2 a4:7 s4 | d4. s8 d8:7 s8 s8 s8 | g2. s4 | d16 s8. b8 s8 e8 s8 a8:7 s8 | d4 g4 d8 s4. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "It" "was" "a" -- "lone" _ "the" "Sav" -- "ior" "prayed" "In" "dark" _ "Geth" -- "sem" -- "a" -- "ne;" _ "A" -- "lone" "He" "drained" _ "the" "bit" -- "ter" "cup" "And" "suf" -- "fered" "there" "for" "me." \set stanza = "(C)" "A" -- "lone," "a" -- "lone," "He" "bore" "it" "all" "a" -- "lone;" "He" "gave" "Him" -- "self" "to" "save" "His" "own," "He" "suf" -- "fered," "bled" "and" "died" "a" -- "lone," "a" -- "lone." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "It was alone the Savior stood" "In Pilate’s judgment hall;" "Alone the crown of thorns He wore," "Forsaken thus by all." } }
      \vspace #0.88
      \line { \bold "3." \column { "Alone upon the cross He hung" "That others He might save;" "Forsaken then by God and man." "Alone, His life He gave." } }
      \vspace #0.88
      \line { \bold "4." \column { "Can you reject such matchless love?" "Can you His claim disown?" "Come, give your all in gratitude," "Nor leave Him thus alone." } }
    } \hspace #1.1 }
    \null
  }
}
