\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E933.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 13.06) (minimum-distance . 13.06) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.02) (minimum-distance . 15.02) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I have a Savior, He’s pleading in glory"
  subtitle = "Preaching of the Gospel — Praying for Others"
  opus = "933"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  c'2 c'4 f'4 | a'2 f'4 a'4 | a'4( g'4) d'4 e'4 | f'2 c'4 c'4 | c'2 f'4 a'4 | c''2 a'4 a'4 | a'2 g'4 f'4 \break | g'2. c'4 | c'2 c'4 f'4 | a'2 f'4 a'4 | a'4( g'4) d'4 e'4 | f'2 c'4 f'4 | f'2 e'4 d'4 | c'2 f'4 g'4 | a'2 g'4 g'4 \break | f'2. a'4 | c''2^\markup { \box \bold "Chorus" } c''4 d''4 | c''2 a'4 a'4 | a'2 a'4 bes'4 | a'2 g'4 f'4 | f'2 e'4 d'4 | c'2 f'4^\fermata f'4 | f'4( e'4) d'4 e'4^\fermata | f'2^\fermata r2 \bar "|."
}

harmonies = \chordmode {
  \global
  d2 s4 s4 | s2 b4:m s4 | a4 s4 a4:7 s4 | d2 s4 s4 | s2 s4 s4 | b2:m s4 s4 | g2 e4:7 s4 | a2 a4:7 s4 | d2 s4 s4 | b2:m s4 s4 | g4 s4 a4:7 s4 | b2:m d4 s4 | g2 s4 s4 | d2 b4:m s4 | d2 a4:7 s4 | d2. s4 | s2 g4 s4 | d2 s4 s4 | s2 a4:7 s4 | d2 s4 s4 | g2 s4 s4 | d2 b4:m s4 | d4 s4 a4:7 s4 | d2 s2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "I" "have" "a" "Sav" -- "ior," "He’s" _ "plead" -- "ing" "in" "glo" -- "ry," "A" "dear" "lov" -- "ing" "Sav" -- "ior," "though" "earth-" "friends" "be" "few;" "And" "now" "He" "is" "watch" -- "ing" "in" "ten" -- _ "der" -- "ness" "o’er" "me," "But" "oh," "that" "my" "Sav" -- "ior" "were" "your" "Sav" -- "ior" "too!" \set stanza = "(C)" "For" "you" "I" "am" "pray" -- "ing," "For" "you" "I" "am" "pray" -- "ing," "For" "you" "I" "am" "pray" -- "ing," "I’m" _ "pray" -- "ing" "for" "you."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "I have a Father: to me He has given" "A hope for eternity, blessed and true;" "He’ll call me one day to the kingdom of heaven," "But oh, that He’d let me bring you with me too!" } }
      \vspace #0.88
      \line { \bold "3." \column { "I have a peace: it is calm as a river," "A peace that the friends of this world never knew;" "My Savior alone is its Author and Giver," "And oh, could I know it was given to you!" } }
    } \hspace #1.1 }
    \null
  }
}
