\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E939.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 13.01) (minimum-distance . 13.01) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "O day of resurrection"
  subtitle = "The Lord’s Day — Day of Resurrection"
  opus = "939"
}

global = {
  \key ees \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  ees'8.([ f'16)] | g'4. g'8 g'8([ f'8) ees'8( f'8)] | ees'4 bes2 ees'8([ g'8)] | bes'4 bes'4 bes'8([ aes'8) g'8( aes'8)] \break | g'2. ees'8.([ f'16)] | g'4. g'8 g'8([ f'8) ees'8( f'8)] | ees'4 bes2 ees'8([ g'8)] | bes'4 bes'4 bes'8([ aes'8) g'8( aes'8)] \break | g'2. bes'4 | c''4. c''8 c''4 c''4 | bes'4 g'2 bes'4 | bes'4 aes'8([ g'8)] aes'4 bes'4 \break | g'2. bes'4 | c''4. c''8 ees''4 c''4 | bes'4 g'2 bes'4 | bes'4 g'8([ bes'8)] bes'8([ aes'8) g'8( f'8)] | ees'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8. s16 | s4. s8 g8 s8 s8 s8 | d4 s4 g4 s8 s8 | d4 s4 a8:7 s8 s8 s8 | d2. s8. s16 | s4. s8 a8 s8 s8 s8 | b4:m s4 d4 s8 s8 | e4:m s4 a8:7 s8 s8 s8 | d2 d4:7 s4 | g4. s8 s4 s4 | d4 s4 b4:m s4 | e4:m s8 s8 a4:7 s4 | d2 d4:7 s4 | g4. s8 s4 s4 | d4 s4 b4:m s4 | d4 s8 s8 a8:7 s8 s8 s8 | d4 g2 d4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "O" _ "day" "of" "re" -- _ "sur" -- _ "rec" -- "tion," "O" _ "day" "of" "joy" _ "and" _ "light," "O" _ "seal" "of" "our" _ "re" -- _ "demp" -- "tion," "Most" _ "beau" -- "ti" -- "ful," _ "most" _ "bright:" "On" "thee" "the" "high" "and" "low" -- "ly," "Bend" -- "ing" "be" -- _ "fore" "the" "throne," "Sing" "“Ho" -- "ly," "ho" -- "ly," "ho" -- "ly,”" "To" "the" _ "great" _ "Three" "in" _ "One."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "On thee at the creation" "The light first had its birth;" "On thee, for our salvation," "Christ rose from depths of earth;" "On thee, our Lord, victorious," "The Spirit sent from heaven;" "And thus on thee, most glorious," "A triple light was given." } }
      \vspace #0.88
      \line { \bold "3." \column { "Today on weary nations" "The heavenly manna falls!" "To holy convocations" "The silver trumpet calls," "Where gospel light is glowing" "With pure and radiant beams," "And living water flowing" "With soul-refreshing streams." } }
    }
    \left-column {
      \line { \bold "4." \column { "New graces ever gaining" "From this of days the best," "We reach the rest remaining" "For people who are blest;" "To Holy Ghost be praises," "To Father and to Son;" "The Church her voice upraises" "To Thee, blest Three in One." } }
    }
  }
}
