\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/E944.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.07
  }
  system-system-spacing = #'((basic-distance . 12.00) (minimum-distance . 12.00) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "The essence of the Kingdom is"
  subtitle = "The Kingdom — Its Reality"
  opus = "944"
}

global = {
  \key d \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  fis'4 | fis'4( eis'4) fis'4 | g'2 fis'4 | fis'2 e'4 | d'2 a'4 | a'4( gis'4) a'4 | d''2 a'4 | a'4( g'4) fis'4 \break | fis'4( e'4) a'4 | a'4( e'4) fis'4 | g'2 fis'4 | fis'4( g'4) a'4 | b'2 a'4 | a'4( cis''4) b'4 | a'2 d'8([ e'8)] | fis'2 e'4 | d'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 | s4 s4 s4 | s2 s4 | a2 s4 | d2 s4 | s4 s4 s4 | s2 s4 | s4 s4 s4 | a4 s4 s4 | s4 s4 s4 | a2:7 s4 | d4 s4 d4:7 | g2 s4 | a4 s4 s4 | d2 s8 s8 | a2 a4:7 | d2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "The" "es" -- _ "sence" "of" "the" "King" -- "dom" "is" "A" "life" _ "that’s" "un" -- "der" "heav" -- _ "en’s" "rule," _ "A" "life" _ "whose" "na" -- "ture" "is" _ "di" -- "vine" "With" _ "Christ" "ex" -- "pe" -- "ri" -- _ "enced" "in" "full."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Such is this life: in spirit poor," "With heart repentant, mourning, meek," "Which is to others merciful" "And purely God Himself doth seek;" } }
      \vspace #0.88
      \line { \bold "3." \column { "As sons of God the peace to make," "For righteousness e’en suffering pain;" "Reviled and hurt for Jesus’ sake," "Exceeding joyfulness to gain;" } }
      \vspace #0.88
      \line { \bold "4." \column { "As salt to kill corruption rife," "In darkness shining as the light," "In heart and action right and true," "In perfect love to claim no right." } }
      \vspace #0.88
      \line { \bold "5." \column { "This life self-glory doth renounce" "And ever for God’s kingdom prays;" "It trusts in God for every need" "And seeks His kingdom first always." } }
      \vspace #0.88
      \line { \bold "6." \column { "’Tis strict with self, with others kind," "And always dealing with the Lord;" "It ever does the Father’s will" "And acts according to His word." } }
      \vspace #0.88
      \line { \bold "7." \column { "To Satan it does not give ground," "Nor to the world, or self, or sin," "But seeks beneath the heaven’s rule" "God’s full authority to win." } }
      \vspace #0.88
      \line { \bold "8." \column { "’Tis such a life which subjugates" "All things with pow’r to God’s behest;" "The time it hastens when the Lord" "Will here His kingdom manifest." } }
    } \hspace #1.1 }
    \null
  }
}
