\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS1025.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.61\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.89
  }
  system-system-spacing = #'((basic-distance . 12.33) (minimum-distance . 12.33) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.98) (minimum-distance . 14.98) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "A Spirit of Love Fanned into Flame"
  subtitle = "Encouragement — For Exercising the Spirit"
  opus = ""
}

global = {
  \key c \major
  \time 3/4
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  g'8 | g'4 g'8 g'4. | g'2.~ | g'2.~ | g'2. \break | g'4 a'8 c''4. | b'2.~ | b'2.~ | b'2. | b'4 a'8 b'4. | c''4 a'4 a'4 \break | a'2 g'4 | a'2 g'4 | a'4 g'4 g'4 | g'2.~ | g'2.~ | g'2.~ | g'2. \break | r2 a'4^\markup { \bold "Chorus after Stanzas 4 and 6" } | a'4 a'4 a'8[ a'8~] | a'2.~ | a'4 g'4 g'8[ g'8(] \break | g'2.~ | g'4) d'8 d'4. | e'2.( | d'2.) \break | r2 e'4 | e'4 e'4 e'8[ f'8~] | f'2. | f'2 f'8[ g'8(] \break | g'2.~ | g'2.~ | g'2.~ | g'2) r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g8:7 | s4 s8 s4. | c2. | s2. | s2. | c4 s8 s4. | g2. | s2. | s2. | s4 s8 s4. | f4 s4 s4 | f2 s4 | s2 s4 | s4 s4 s4 | c2. | s2. | g2.:7 | s2. | a2:m s4 | s4 s4 s8 s8 | f2. | s4 s4 s8 s8 | g2. | s4 s8 s4. | c2. | g2. | a2:m s4 | s4 s4 s8 s8 | f2. | s2 s8 s8 | g2. | s2. | g2.:7 | s2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "A" "spir" -- "it" "of" "love" _ _ "Fanned" "in" -- "to" "flame;" _ _ "Love" "will" "pre" -- "vail" "more" "than" "an" -- "y" "word" "In" "pow" -- "er" "pro" -- "claimed." _ _ _ "If" "my" "own" "de" -- "sires" _ _ "Quench" "the" "Spir" -- _ _ "it" "with" -- "in," _ "Re" -- "mind" "me" "to" "fan" _ "it" "a" -- "gain." _ _ _ _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Things that we do," "Words that we say," "When in a spirit of love, how love" "Prevails in this way." } }
      \vspace #0.88
      \line { \bold "3." \column { "The spirit in man," "Where our God lives;" "Greatest of gifts we could e’er receive," "Freely He gives." } }
      \vspace #0.88
      \line { \bold "4." \column { "By His great love," "God is so known;" "Only a spirit of love in man" "Makes His love shown." \translate #'(2.77 . -2.00) "If my own desires" \translate #'(2.77 . -2.00) "Quench the Spirit within," \translate #'(2.77 . -2.00) "Remind me to fan it again." } }
    }
    \left-column {
      \line { \bold "5." \column { "Powerful will," "Sober in mind;" "Yet without love only threatening words" "Other souls find." } }
      \vspace #0.88
      \line { \bold "6." \column { "To overcome," "For this we yearn;" "Oh may a spirit that’s fanned into flame" "Increasingly burn." \translate #'(2.77 . -2.00) "If my own desires" \translate #'(2.77 . -2.00) "Quench the Spirit within," \translate #'(2.77 . -2.00) "Remind me to fan it again." } }
    }
  }
}
