\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS122.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.90
  }
  system-system-spacing = #'((basic-distance . 12.87) (minimum-distance . 12.87) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "When I’m with the saints"
  subtitle = "The Church—Building by the Growth in Life"
  opus = ""
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  fis'8[ e'8 fis'8 g'8] a'4 r4 | b8[ g'8 g'8 g'8~] g'4 r4 | cis'8[ g'8 g'8 g'8~] g'4 r4 | a'8[ b'8 a'8 fis'8~] fis'4 r4 \break | fis'8[ e'8 fis'8 g'8] a'4 r4 | b8[ g'8 g'8 g'8~] g'4 fis'4 | e'4. d'8 cis'4 e'4 | d'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 s8 s8 s4 s4 | e8:m s8 s8 s8 s4 s4 | a8:7 s8 s8 s8 s4 s4 | d8 s8 s8 s8 a4 s4 | d8 s8 s8 s8 s4 s4 | e8:m s8 s8 s8 g4 s4 | a4. s8 a4:7 s4 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "When" "I’m" "with" "the" "saints," "Hap" -- "py" "am" "I!" _ "Peace" -- "ful" "am" "I!" _ "Rest" -- "ful" "am" "I!" _ "When" "I’m" "with" "the" "saints," "Joy" -- "ful" "am" "I!" _ "A" "joy" "I" "can’t" "de" -- "ny!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "When I’m with the saints," "Christ we pursue!" "Seeking for You!" "Here loving You!" "When I’m with the saints," "Christ we do share!" "And for each member care!" } }
      \vspace #0.88
      \line { \bold "3." \column { "When I’m with the saints," "Christ we employ!" "Without alloy!" "Christ we enjoy!" "When I’m with the saints," "Hopeful am I!" "They are my life supply!" } }
      \vspace #0.88
      \line { \bold "4." \column { "When I’m with the saints," "Christ in them see!" "Our hope is He!" "Hope of glory!" "When I’m with the saints," "Foretaste have we!" "Conformed to Him we’ll be!" } }
      \vspace #0.88
      \line { \bold "5." \column { "When I’m with the saints," "Christ we await!" "Anticipate!" "Lord, don’t be late!" "When I’m with the saints," "For Christ we yearn!" "We long for His return!" } }
      \vspace #0.88
      \line { \bold "6." \column { "When I’m with the saints," "You will go on!" "I will go on!" "Let’s all go on!" "When I’m with the saints," "This we affirm!" "We live if you stand firm!" } }
    } \hspace #1.1 }
    \null
  }
}
