\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS136.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.89
  }
  system-system-spacing = #'((basic-distance . 12.55) (minimum-distance . 12.55) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.97) (minimum-distance . 14.97) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I’m a sinner without one plea"
  subtitle = "Assurance and Joy of Salvation—Satisfied with Christ"
  opus = ""
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  r4 d'8[ d'8] g'4 d'8[ d'8] | e'8 fis'4 g'8~ g'2 | r4 d'8[ d'8] d''8([ c''8)] b'4 | c''8 b'4 a'8~ a'2 \break | r4 d'8[ d'8] d''8([ c''8)] b'4 | c''8 b'4 a'8~ a'8 g'4 g'8 | e'8[ e'8 e'8 e'8] e'8 b'4 a'8~ | a'1 \break | r4 d'8[ d'8] g'4 d'4 | e'8 fis'4 g'8~ g'2 | r4 d'8[ d'8] d''8([ c''8)] b'4 | c''8 b'4 a'8~ a'2 \break | r4 d'8[ d'8] d''8([ c''8)] b'4 | c''8 b'4 a'8~ a'8 g'4 g'8 | e'8[ e'8 e'8 e'8] e'8 b'4 a'8 \break | r4 b'8[^\markup { \box \bold "Chorus" } b'8] c''8 c''4 d''8~ | d''1 | r4 c''8[ b'8] a'4 g'4 | b'4 b'4 b'4 b'4 | c''8 b'4 a'8~ a'8[ a'8 b'8 c''8] | d''1 \break | r8 c''8[ c''8 b'8] a'4 g'4 | b'4 b'4 b'4 b'4 | c''8 b'4 a'8~ a'4 g'4 | g'1~ | g'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 s8 s8 s4 s8 s8 | c8 s4 s8 s2 | a4:m s8 s8 s8 s8 s4 | d8:7 s4 s8 s2 | g4 s8 s8 s8 s8 s4 | c8 s4 s8 s8 s4 s8 | a8:m s8 s8 s8 s8 s4 s8 | d1:7 | g4 s8 s8 s4 s4 | c8 s4 s8 s2 | a4:m s8 s8 s8 s8 s4 | d8:7 s4 s8 s2 | g4 s8 s8 s8 s8 s4 | c8 s4 s8 s8 s4 s8 | a8:m s8 s8 s8 s8 s4 s8 | d4:7 s8 s8 s8 s4 s8 | g1 | e4:m s8 s8 s4 s4 | c4 s4 s4 s4 | d8:7 s4 s8 s8 s8 s8 s8 | g1 | e8:m s8 s8 s8 s4 s4 | c4 s4 s4 s4 | d8:7 s4 s8 s4 s4 | g2 c2 | g2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "I’m" "a" "sin" -- "ner" "with" -- "out" "one" _ "plea," "But" "the" _ "Lamb" "of" "God" "in" "me;" _ "I" "was" "lost" _ "and" "with" -- "out" "hope" _ "But" "my" "Sav" -- "ior" "came" "and" "sought" "me" "out." _ "’Tis" "my" "sto" -- "ry" "and" "my" _ "song;" "To" "the" "world" _ "I" "say" "so" "long;" _ "I" "now" "walk" _ "and" "live" "in" "light" _ "With" "the" "New" "Je" -- "ru" -- "sa" -- "lem" "in" "sight." \set stanza = "(C)" "Till" "the" "end" "of" "days," _ "He" "will" "be" "with" "me" "And" "lead" "me" "to" "that" _ "place;" "I" "give" "my" "all:" "My" "life," "my" "ways," "my" "thoughts," "And" "ev" -- "ery" -- "thing" "to" _ "Him," "my" "love." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Sometimes I think that I might leave" "And wallow in misery," "But then graciously He comes" "And applies His gentle, soothing touch." "’Tis my story and my fight;" "To the self I say goodbye;" "I now walk and live in light" "With the coming kingdom full in sight." } }
    } \hspace #1.1 }
    \null
  }
}
