\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS192.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 14.33) (minimum-distance . 14.33) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Some, these days, would tell us that our Jesus is not food"
  subtitle = "Experience of Christ—As Food and Drink"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  a'8[ a'8 a'8 g'8] f'8[ g'8 f'8 d'8] | c'8[ d'8 c'8 a8] c'2 | d'8[ f'8 f'8 d'8] c'8[ f'8 f'8 f'8] | g'8[ g'8 g'8 a'8] g'2 \break | a'8[ a'8 a'8 g'8] f'8[ g'8 f'8 d'8] | c'8[ d'8 c'8 a8] c'2 | d'8[ f'8 f'8 d'8] c'8[ f'8 f'8 g'8] | a'8[ a'8 g'8 g'8] f'2 \break | a'8[ c''8~^\markup { \box \bold "Chorus" } c''8 d''8] a'8([ g'8)] f'4 | d'8[ f'8 g'8 f'8] a'8[ c''16 d''8. c''8] | a'8[ c''8~ c''8 d''8] a'8([ g'8)] f'4 | g'8[ g'8 g'8 a'8] g'2 \break | a'8[ c''8~ c''8 d''8] a'8([ g'8)] f'4 | d'8[ f'8 g'8 f'8] a'8[ c''16 d''8. c''8] | a'8[ c''8~ c''8 d''8] a'8([ g'8)] f'4 | a'8[ a'8 g'8 g'8] f'2 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 s8 s8 g8 s8 s8 s8 | d8 s8 s8 s8 s2 | g8 s8 s8 s8 d8 s8 s8 s8 | e8:7 s8 s8 s8 a2 | d8 s8 s8 s8 g8 s8 s8 s8 | d8 s8 s8 s8 s2 | g8 s8 s8 s8 d8 s8 g8 s8 | d8 s8 a8:7 s8 d2 | d8 s8 s8 s8 s8 s8 s4 | g8 s8 s8 s8 d8 s16 s8. s8 | s8 s8 s8 s8 b8:m s8 s4 | e8:7 s8 s8 s8 a2:7 | d8 s8 s8 s8 s8 s8 s4 | g8 s8 s8 s8 d8 s16 s8. s8 | s8 s8 s8 s8 b8:m s8 s4 | e8:7 s8 a8:7 s8 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Some," "these" "days," "would" "tell" "us" "that" "our" "Je" -- "sus" "is" "not" "food," "That" "we" "on" -- "ly" "need" "to" "know" "a" -- "bout" "Him" "and" "do" "good," "But" "we’re" "glad" "to" "tell" "you" "broth" -- "ers," "it’s" "just" "not" "that" "way—" "Je" -- "sus" "is" "the" "bread" "of" "life;" "we" "eat" "Him" "ev" -- "ery" "day." \set stanza = "(C)" "We" "love" _ "the" _ "church" "life," "eat" -- "ing," "drink" -- "ing," "breath" -- "ing" "Je" -- "sus." "We" "love" _ "the" _ "church" "life," "tak" -- "ing" "in" "God’s" "Word." "We" "love" _ "to" "hear" _ "those" "“O" "Lord," "A" -- "men," "Hal" -- "le" -- "lu" -- "jahs!”" "We" "love" _ "the" _ "church" "life," "feast" -- "ing" "with" "the" "Lord."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "When He fills our inward parts, we’re never quite the same," "So much richness we can taste by calling on His name." "“Services” but once a week for us will never do." "Every day we need the fellowship to take us through." } }
      \vspace #0.88
      \line { \bold "3." \column { "If these latter days and situations of the world" "Make you feel that round a vicious circle you are swirled," "Then please listen closely to the things we have to say;" "It may be that you will find with us a better way." } }
    } \hspace #1.1 }
    \null
  }
}
