\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS216.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #1.01
  }
  system-system-spacing = #'((basic-distance . 13.53) (minimum-distance . 13.53) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Speak to me, Lord every day"
  subtitle = "Longings—For Fellowship with Christ"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  a'8[ g'8 f'8 c'8~] c'2 | d'8[ f'8] g'4 a'2 \break | a'8[ g'8 f'8 c'8~] c'8[ c'8 c'8 c'8] | d'8[ f'8] g'4 f'2 \break | a'8[ g'8 f'8 c'8~] c'4. c'8 | \tuplet 3/2 { bes'4 c''4 bes'4 } a'2 \break | bes'8[ a'8 g'8 c''8~] c''4 bes'8[ a'8] | f'2 g'2 | f'1~ | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 s8 s8 s2 | g8 s8 s4 d2 | d8 s8 s8 s8 s8 s8 s8 s8 | g8 s8 s4 d2 | d8 s8 s8 s8 s4. s8 | \tuplet 3/2 { g4 s4 s4 } d2 | g8 s8 s8 s8 d4 s8 s8 | e2:m7 a2:7 | d2 g2 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Speak" "to" "me," "Lord" _ "ev" -- "er" -- "y" "day." "Speak" "to" "me," "Lord—" _ "I" "love" "to" "hear" "what" "You" "say." "Speak" "to" "me," "Lord" _ "un" -- "til" "I" "have" "heard." "Speak" "to" "me," "Lord" _ "through" "Your" "liv" -- "ing" "Word." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Speak to me, Lord every day." "Speak to me, Lord—I love to hear what You say." "Speak to me, Lord, fill me with light." "Speak to me, Lord all Your words of life." } }
    } \hspace #1.1 }
    \null
  }
}
