\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS288.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.23
  }
  system-system-spacing = #'((basic-distance . 14.07) (minimum-distance . 14.07) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Lord, keep my heart open and soft toward You"
  subtitle = "Longings—For a Soft and Open Heart"
  opus = ""
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  d'2^\markup { \box \bold "PART 1" } a'4 d'8[ cis'8~] | cis'1 | a'4 fis'8[ g'8] d''4 g'8[ a'8~] | a'1 \break | d'2 a'4 d'8[ d'8(] | cis'2.) r8 a'8 | a'4 fis'8[ g'8] d''4 g'8[ a'8~] | a'1~ \break | a'4.^\markup { \box \bold "PART 2" } a8 fis'8[ g'8] fis'4 | e'8 d'2.( cis'8~ | cis'2) fis'8[ g'8 fis'8 e'8~] | e'4 d'8[ a8~] a4 fis'8[ e'8~] \break | e'4. a8 fis'8[ g'8] fis'4 | e'4 fis'8 d'2( cis'8~ | cis'2) fis'8[ g'8 fis'8 e'8~] | e'8[ d'8 d'8 d'8] a8[ a8 fis'8 e'8~] \break | e'2^\markup { \box \bold "UNISON" } d'8[ e'8 fis'8 d'8] | b'2 a'2~ | a'4. fis'8 e'8[ d'8 fis'8 d'8~] | d'2 a'8[ g'8 fis'8 d'8~] \break | d'2 d'8[ e'8 fis'8 e'8] | d'2.~ d'8([ cis'8~] | cis'4) fis'4 e'8([ d'8)] e'4 | d'1~ | d'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d2 s4 s8 s8 | a1 | g4 s8 s8 s4 s8 s8 | a1 | d2 s4 s8 s8 | a2. s8 s8 | g4 s8 s8 s4 s8 s8 | a1:sus4 | a4.:7 s8 s8 s8 s4 | d8 s2. s8 | a2 s8 s8 s8 s8 | g4 s8 s8 s4 s8 s8 | a4. s8 s8 s8 s4 | d4 s8 s2 s8 | a2 s8 s8 s8 s8 | g8 s8 s8 s8 s8 s8 s8 s8 | a2 d8 s8 s8 s8 | g2 s2 | a4. s8 s8 s8 s8 s8 | b2:m s8 s8 s8 s8 | d2 s8 s8 s8 s8 | g2. s8 s8 | a4:7 s4 s8 s8 s4 | g1 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "(C)" "Lord," "keep" "my" "heart" _ "o" -- "pen" "and" "soft" "toward" "You." _ "Lord," "draw" "my" "eyes" _ "to" "see" "noth" -- "ing" "else" "but" "You." _ _ "What" -- "ev" -- "er" "may" "hap" -- "pen," _ _ "I" "know" "You" "want" _ "to" "gain" _ "my" "heart." _ "Though" "I" "may" "not" "un" -- "der" -- "stand," _ _ "Just" "keep" "dis" -- "pens" -- _ "ing" "in" -- "to" "my" "ev" -- "ery" "part." _ "Make" "me" "a" "be" -- "liev" -- "er" _ "By" "look" -- "ing" "at" "You." _ "(Look" -- "ing" "at" "You)" _ "Stand" -- "ing" "on" "Your" "Word," _ "Faith" -- _ "ful" "and" _ "true." _ _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

