\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS34.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.92
  }
  system-system-spacing = #'((basic-distance . 14.17) (minimum-distance . 14.17) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "He knows, He knows"
  subtitle = "Comfort in Trials—By Trusting the Lord"
  opus = ""
}

global = {
  \key ees \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  bes'4 g'4~ g'4 aes'4 | bes'2. bes'4 | aes'4 g'4 f'4 ees'4 | f'4 g'2. | bes'4 g'4~ g'4 c''4 | bes'2. bes4 | aes'4 g'8[ ees'8~] ees'4 g'4 | f'1 \break | bes'4 g'4~ g'4 aes'4 | bes'2. bes'4 | aes'4 g'4 f'4 ees'4 | f'4 g'2. | c'4 ees'4~ ees'4 f'4 | g'2. ees'4 | aes'4 g'8[ ees'8~] ees'4 g'4 | f'1~ | f'2. r4 \break | g'4 bes'4~^\markup { \box \bold "Chorus" } bes'4 bes'4 | bes'1 | aes'4 g'8[ f'8~] f'4 ees'4 | f'4 g'2. | g'4 bes'4~ bes'4 c''4 | bes'2. bes4 | aes'4 g'8[ ees'8~] ees'4 g'4 | f'1 \break | g'4 bes'4~ bes'4 bes'4 | bes'1 | aes'4 g'8[ f'8~] f'4 ees'4 | f'4 g'2. | c'4 ees'4~ ees'4 f'4 | ees'2. bes4 | aes'4 f'8[ c'8~] c'4 d'4 | ees'1 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 s4 s4 s4 | s2. s4 | g4 s4 a4 s4 | d4 s2. | fis4:m s4 s4 s4 | b2.:m s4 | g4 s8 s8 s4 s4 | a1 | d4 s4 s4 s4 | s2. s4 | g4 s4 a4 s4 | b4:m s2. | g4 s4 s4 s4 | d2. s4 | e4:m7 s8 s8 s4 s4 | a1:sus4 | a2. s4 | d4 s4 s4 s4 | s1 | g4 s8 s8 a4 s4 | d4 s2. | fis4:m s4 s4 s4 | b2.:m s4 | g4 s8 s8 s4 s4 | a1 | d4 s4 s4 s4 | s1 | g4 s8 s8 a4 s4 | b4:m s2. | g4 s4 s4 s4 | d2. s4 | e4:m s8 s8 a4:7 s4 | d1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Fear" "not," _ "He" "knows;" "My" "soul" "why" "fret" "and" "trem" -- "ble?" "Fear" "not," _ "He" "knows;" "Your" "life" "is" "in" _ "His" "hands." "Fear" "not," _ "He" "knows;" "And" "you" "know" "He" "is" "a" -- "ble" "To" _ "care" "for" "You," "So" "trust" "the" _ "best" "is" _ "planned!" \set stanza = "(C)" "Oh" _ "Lord," "You" "know;" "’Tis" "a" _ "thought" "so" "joy" -- "ous!" "Though" "I" _ "don’t" "know," "What" "need" "have" "I" _ "to" "fear?" "You" _ "know," "You" "know;" "Thank" "and" _ "praise" "You," "Je" -- "sus!" "Through" "all" _ "un" -- "knowns," "You" "make" "Your" -- _ "self" "so" "dear!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Just trust, He knows" "Life’s still unwritten letter." "Just trust, He knows" "Plans time would now disguise." "Just trust, He knows," "He sees which turn is better;" "At the right time" "He’ll open up your eyes!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Just rest, He knows;" "With Him blindness is pleasant!" "Just rest, He knows;" "Sightless, you see Him best!" "Just rest, He knows;" "My soul, don’t waste the present" "On those “what-if’s“." "Just turn to Him and rest!" } }
    }
    \left-column {
      \line { \bold "4." \column { "Just seek, He knows;" "Seek first His heart’s great yearning." "Just seek, He knows;" "Serve Him, in Him abide." "Just seek, He knows;" "Have peace and rest while turning." "Put His cares first;" "All else He will provide." } }
    }
  }
}
