\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS423.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 13.25) (minimum-distance . 13.25) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Christ in You, the Hope of Glory"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  a8 | a'4 a'8[ a'8] a'4 g'4 | fis'4 e'8[ e'8~] e'4. a8 | d'4 d'4 d'4 e'8[ fis'8] \break | fis'4. cis'8~ cis'4 a4 | b2 b4 b4 | a4. d'8~ d'4. d'8 | e'2 e'2 \break | g'2. r8 a8 | a'4. a'8~ a'4 a'4 | g'8 fis'4 e'8~ e'4. a8 | d'4 d'4 d'4 e'8[ fis'8] | fis'4. cis'8~ cis'2 \break | b2 b2 | a4. d'8~ d'4. d'8 | e'4. e'8 e'8[ cis'8] e'4 | d'1~ \break | d'2. r8 a8 | b'2 b'4 d''4 | cis''4 b'8[ b'8~] b'8 a'4. | a'2 d'2 \break | b'2. r8 d'8 | g'2 g'4 a'8[ b'8] | a'8 a'4. \tuplet 3/2 { a'4 a'4 g'4 } | a'8 fis'4.~ fis'2 \break | fis'2. d'8[ d'8] | b'2 b'4 b'8[ d''8] | e''4 d''8[ cis''8~] cis''4. b'8 | a'2 a'4 e''4 \break | d''2. b'8[ b'8] | b'2. b'4 | a'4. a'8 \tuplet 3/2 { a'4 fis'4 e'4 } | d'1~ | d'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8:sus2 | s4 s8 s8 s4 s4 | a4 s8 s8 s4. s8 | b4:m s4 s4 s8 s8 | fis4.:m s8 s4 s4 | g2 s4 s4 | d4. s8 s4. s8 | e2:m s2 | a2.:7 s8 s8 | d4.:sus2 s8 s4 s4 | a8 s4 s8 s4. s8 | b4:m s4 s4 s8 s8 | fis4.:m s8 s2 | g2 s2 | d4. s8 s4. s8 | e4.:m s8 a8:7 s8 s4 | d1 | d2. s8 s8 | g2 s4 s4 | a4 s8 s8 s8 s4. | fis2:m s2 | b2.:m s8 s8 | g2 s4 s8 s8 | a8 s4. \tuplet 3/2 { s4 s4 s4 } | d8 s4. s2 | d2.:7 s8 s8 | g2 s4 s8 s8 | a4 s8 s8 s4. s8 | fis2:m s4 s4 | b2.:m s8 s8 | g2. s4 | a4. s8 \tuplet 3/2 { s4 s4 s4 } | d1 | s2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Of" "which" "I" "be" -- "came" "a" "min" -- "is" -- "ter" _ "ac" -- "cord" -- "ing" "to" "the" "ste" -- "ward" -- "ship" _ "of" "God," "which" "was" "giv" -- "en" _ "to" "me" "for" "you," "to" "com" -- _ "plete" "the" "word" "of" _ "God," "The" "mys" -- "tery" "which" "has" "been" "hid" -- "den" _ "from" "the" "ag" -- "es" _ "and" "from" "the" "gen" -- "er" -- "a" -- "tions" _ "but" "now" "has" "been" "man" -- "i" -- "fest" -- _ "ed" "to" "His" "saints;" "To" "whom" "God" "willed" "to" "make" "known" "what" "are" "the" "rich" -- "es" _ _ "of" "the" "glo" -- "ry" "of" "this" "mys" -- "ter" -- "y" _ "a" -- "mong" "the" "Gen" -- "tiles," "which" "is" "Christ" "in" "you," "the" "hope" "of" "glo" -- "ry." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

