\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS433.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.02
  }
  system-system-spacing = #'((basic-distance . 13.33) (minimum-distance . 13.33) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Consider Your Ways"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  g'4 | g'2. a'4 | g'2 e'4 g'4 | a'2. c''4 | b'4 b'4 a'4 g'4 | a'2. a'8[ a'8] | g'4 a'2 g'4 | e'1~ \break | e'2. e'4 | f'4 f'4~ f'4 a'4 | g'2. f'4 | e'2. g'4 | a'4( g'4~ g'4) e'4 | f'2.( a'4) | g'4( a'4~ a'4) g'4 | e'1~ \break | e'2. e'4 | f'2. a'4 | b'4( g'2.) | g'4 g'4~ g'4 d''4 | c''2. g'4 | a'2. a'4 | g'4( e'4~ e'4) d'4 | c'1~ \break | c'2. g'4 | a'2. a'4 | b'4. b'8~ b'4. g'8 | b'4. b'8~ b'4 d''8([ b'8)] | c''2. g'4 | a'2. a'8[ a'8] | g'4 e'4~ e'4 d'4 | e'4 g'2.~ \break | g'2. g'4 | a'2. d''4 | b'2. b'8[ b'8] | e''2.( d''4) | d''8( c''4) c''8~ c''4 b'4 | a'2. a'4 | g'4 g'4 e'4 d'4 | c'1~ | c'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 | s2. s4 | e2:m s4 s4 | a2.:m s4 | e4:m s4 s4 s4 | f2. s8 s8 | g4 s2 s4 | c1 | c2.:7 s4 | f4 s4 s4 s4 | g2. s4 | e2.:m s4 | a4:m s4 s4 s4 | f2. s4 | g4 s4 s4 s4 | c1 | c2.:7 s4 | f2. s4 | g4 s2. | e4:m s4 s4 s4 | a2.:m s4 | f2. s4 | g4 s4 s4 s4 | c1 | c2.:7 s4 | f2. s4 | g4. s8 s4. s8 | e4.:m s8 s4 s8 s8 | a2.:m s4 | f2. s8 s8 | g4 s4 s4 s4 | c4 s2. | c2.:7 s4 | f2. s4 | g2. s8 s8 | e2.:m s4 | a8:m s4 s8 s4 s4 | f2. s4 | g4 s4 s4 s4 | c1 | s2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "If" "we" "do" "not" "have" "the" "heart" "to" "take" "care" "of" "God’s" "house" "for" "His" "sat" -- "is" -- "fac" -- "tion," _ "No" "mat" -- "ter" _ "how" "much" "we" "eat" "or" _ "drink" _ "or" "how" _ "well" _ _ "we" "dress," _ "There" "will" "be" "no" _ "sat" -- "is" -- _ "fac" -- "tion;" "if" "we" "ne" -- "glect" _ _ "the" "church—" _ "Thus" "says" "Je" -- "ho" -- _ "vah," "Con" -- "sid" -- "er" _ _ "your" "ways." "Go" "up" "to" "the" "moun" -- "tain" _ "and" "bring" "wood," _ "And" "build" "My" "house," "and" "I’ll" "take" _ _ "plea" -- _ "sure" "in" "it," "And" "will" "be" "glo" -- "ri" -- "fied." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

