\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS510.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.13) (minimum-distance . 12.13) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.97) (minimum-distance . 14.97) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Into our care did God entrust"
  subtitle = "Encouragement — For Shepherding the Children"
  opus = ""
}

global = {
  \key g \major
  \time 3/4
  \autoBeamOff
  \partial 4.
}

melody = {
  \clef treble
  \global
  d'8 d'8[ g'8] | b'4. b'8 a'8[ g'8] | e'4. a'8 g'8[ e'8] \break | d'4. g'8 b'8[ g'8] | a'4. d'8 d'8[ g'8] | b'4. b'8 a'8[ g'8] \break | e'4. a'8 g'8[ e'8] | d'8[ g'8] b'4 a'4 \break | g'4. d'8^\markup { \box \bold "Chorus" } g'8[ b'8] | d''4. d''8 c''8[ b'8] | c''4. d'8 fis'8[ a'8] \break | c''4. c''8 b'8[ a'8] | b'4. d''8 d''8[ b'8] | g'4. b'8 a'8[ g'8] \break | e'4. a'8 g'8[ e'8] | d'8[ g'8] b'4 a'4 | g'4. r4. \bar "|."
}

harmonies = \chordmode {
  \global
  g8 s8 s8 | s4. s8 g8:7 s8 | c4. s8 s8 s8 | g4. s8 s8 s8 | d4. s8 d8:7 s8 | g4. s8 g8:7 s8 | c4. s8 s8 s8 | g8 s8 s4 d4:7 | g4. s8 s8 s8 | s4. s8 s8 s8 | d4. s8 s8 s8 | d4.:7 s8 s8 s8 | g4. s8 s8 s8 | s4. s8 g8:7 s8 | c4. s8 s8 s8 | g8 s8 d4:7 s4 | g4. s4. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "In" -- "to" "our" "care" "did" "God" "en" -- "trust" "The" "chil" -- "dren," "an" "in" -- "her" -- "i" -- "tance," "We" "must" "e" -- "quipped" "in" "spir" -- "it" "be," "To" "match" "God’s" "heart" "in" "shep" -- "herd" -- "ing." \set stanza = "(C)" "To" "shep" -- "herd" "them," "seize" "ev" -- "ery" "chance," "Im" -- "part" "the" "faith" "with" "dil" -- "i" -- "gence;" "Build" "char" -- "ac" -- "ter" "with" -- "out" "de" -- "lay," "Raise" "up" "the" "ves" -- "sels" "of" "the" "age."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Enjoy the grace of Christ each day," "Each moment live the God-man way;" "For the right timing, watch and pray," "And be good patterns every day." } }
      \vspace #0.88
      \line { \bold "3." \column { "This crooked age defiled all lands;" "The church alone most holy stands." "Coordinate with other saints," "Young vessels unto honor gain." } }
    } \hspace #1.1 }
    \null
  }
}
