\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS514.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 12.12) (minimum-distance . 12.12) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.97) (minimum-distance . 14.97) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Your People Will Offer Themselves Willingly"
  subtitle = "Consecration — Answering the Lord’s Call"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  r4 d'4 d'4 e'4 | f'2.( a'4) | bes'4 bes'4~ bes'4 a'4 | g'2 g'4 f'4 | e'2 e'4. e'8 | a'4 g'4~ g'4 e'4 | f'4 a'2.~ | a'1 \break | r4 d'4 d'4 e'4 | f'2.( a'4) | bes'4 bes'4~ bes'4 a'4 | g'2 g'4 f'4 | e'2 e'4. e'8 | a'4 g'4~ g'4 e'4 | f'4 d'2.~ | d'1 \break | r2 a'4 a'4 | d''2. a'4 | bes'1~ | bes'1 | r2 g'2 | c''2. g'4 | bes'4 a'2.~ | a'1 \break | r2 d'2 | bes'2 bes'4 a'4 | g'4 g'4 g'4 f'4 | e'2 e'4 e'4 | e'4. f'8~ f'4 e'4 | d'1~ | d'1 \break | r2 a'4 a'4 | d''2 a'4 a'4 | bes'1~ | bes'1 | r2 g'2 | c''2. g'4 | bes'4 a'2.~ | a'1 \break | r2 d'4 d'4 | bes'2 bes'4 a'4 | g'4 g'4 g'4 f'4 | e'2 e'4 e'4 | e'4.( f'8~ f'4) e'4 | d'1~ | d'1 \bar "|."
}

harmonies = \chordmode {
  \global
  d4:m s4 s4 s4 | s2. s4 | g4:m s4 s4 s4 | s2 s4 s4 | a2 s4. s8 | a4:7 s4 s4 s4 | d4:m s2. | s1 | d4:m s4 s4 s4 | s2. s4 | g4:m s4 s4 s4 | s2 s4 s4 | a2 s4. s8 | a4:7 s4 s4 s4 | d4:m s2. | s1 | d2:m s4 s4 | d2. s4 | g1:m | s1 | c2 s2 | c2.:7 s4 | d4:m s2. | s1 | d2:m s2 | g2:m s4 s4 | s4 s4 s4 s4 | a2 s4 s4 | a4.:7 s8 s4 s4 | d1:m | s1 | d2:m s4 s4 | s2 s4 s4 | g1:m | s1 | c2 s2 | c2.:7 s4 | d4:m s2. | s1 | d2:m s4 s4 | g2:m s4 s4 | s4 s4 s4 s4 | a2 s4 s4 | a4.:7 s8 s4 s4 | d1:m | s1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Your" "peo" -- "ple" "will" _ "of" -- "fer" _ "them" -- "selves" "will" -- "ing" -- "ly" "In" "the" "day" "of" _ "Your" "war" -- "fare;" _ "Your" "peo" -- "ple" "will" _ "of" -- "fer" _ "them" -- "selves" "will" -- "ing" -- "ly" "In" "the" "day" "of" _ "Your" "war" -- "fare," _ "In" "the" "splen" -- "dor" "of" _ "their" "con" -- "se" -- "cra" -- "tion." _ "Your" "young" "men" "will" "be" "like" "dew" "to" "You" "From" "the" "womb" "of" _ "the" "dawn." _ "You" "will" "drink" "from" "the" "brook," _ "Your" "o" -- "ver" -- "com" -- "ers," _ "As" "You" "fight" "on" "the" "way" "to" "car" -- "ry" "out" "God’s" "e" -- "con" -- _ _ "o" -- "my." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Dear Lord, I will offer myself willingly" "In the day of Your warfare;" "Dear Lord, I will offer myself willingly" "In the day of Your warfare," "In the splendor of fresh consecration." "As young men we’ll be like dew to You" "Of our generation." "We will be the brook to water You, Lord," "As You take th’ lead to fight through to the end;" "You will lift up Your head." } }
    } \hspace #1.1 }
    \null
  }
}
