\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS524.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.02
  }
  system-system-spacing = #'((basic-distance . 12.06) (minimum-distance . 12.06) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "2 Corinthians 12:15-16a"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  d'4 | a'1~ | a'4 b'8[ a'8~] a'8[ g'8~ g'8 fis'8~] | fis'8[ g'8~ g'8 d'8~] d'2 \break | r4 fis'8[ fis'8] e'8[ d'8] b4 | fis'2.( e'4 | b2) d'4 d'4 | fis'2 e'8[ d'8~ d'8 e'8~] \break | e'2. d'4 | a'1~ | a'4 b'8[ a'8~] a'8[ g'8~ g'8 fis'8~] | fis'8[ g'8~ g'8 d'8~] d'2 \break | r4 fis'8[ fis'8] e'8[ d'8] b4 | fis'2.( e'4 | b2) d'4 d'4 | fis'2 e'8[ d'8~ d'8 e'8~] | e'1~ \break | e'4 r4 d'4 d'4 | b'2 b'2 | cis''4 cis''8[ cis''8~] cis''8[ d''8~ d''8 a'8~] | a'1 \break | fis'4 fis'8[ g'8~] g'8[ a'8~ a'8 g'8~] | g'2. fis'4 | e'2. d'4 | fis'1~ \break | fis'2 d'4 d'4 | b'2 b'2 | cis''4 cis''8[ cis''8~] cis''8[ d''8~ d''8 a'8~] | a'1 \break | fis'4 fis'8[ g'8~] g'8[ a'8~ a'8 g'8~] | g'2. fis'4 | e'4. d'8~ d'4 cis'4 | d'1~ | d'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 | s1 | s4 s8 s8 s8 s8 s8 s8 | g8 s8 s8 s8 s2 | g4 s8 s8 s8 s8 s4 | e2.:m s4 | s2 s4 s4 | g2 s8 s8 s8 s8 | a2. s4 | d1 | s4 s8 s8 s8 s8 s8 s8 | g8 s8 s8 s8 s2 | g4 s8 s8 s8 s8 s4 | e2.:m s4 | s2 s4 s4 | g2 s8 s8 s8 s8 | a1:sus4 | a4 s4 s4 s4 | g2 s2 | a4 s8 s8 s8 s8 s8 s8 | d1 | b4:m s8 s8 s8 s8 s8 s8 | e2.:m s4 | a2. s4 | d1 | d2:7 s4 s4 | g2 s2 | a4 s8 s8 s8 s8 s8 s8 | d1 | b4:m s8 s8 s8 s8 s8 s8 | g2. s4 | a4. s8 s4 s4 | d1 | s2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "But" "I," _ "I" "will" _ "most" _ "glad" -- _ "ly" _ "spend" _ "and" "be" "ut" -- "ter" -- "ly" "spent" _ _ "on" "be" -- "half" "of" "your" _ "souls." _ "But" "I," _ "I" "will" _ "most" _ "glad" -- _ "ly" _ _ "spend" "and" "be" "ut" -- "ter" -- "ly" "spent" _ _ "on" "be" -- "half" "of" "your" _ "souls." _ _ "If" "I" "love" "you" "more" "a" -- "bun" -- _ "dant" -- _ "ly," _ "more" "a" -- "bun" -- _ "dant" -- _ "ly," _ "am" "I" "loved" "less?" _ "If" "I" "love" "you" "more" "a" -- "bun" -- _ "dant" -- _ "ly," _ "more" "a" -- "bun" -- _ "dant" -- _ "ly," _ "but" "let" "it" _ "be" "so!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

