\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS547.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #1.03
  }
  system-system-spacing = #'((basic-distance . 12.22) (minimum-distance . 12.22) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Beloved, Let Us Love One Another"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  c'8 | a'8 a'4.~ a'2 | a'8[ a'8~ a'8 a'8~] a'4 g'8[ f'8] | e'8 g'4.~ g'2 \break | g'2. r8 c'8 | bes'8[ bes'8 bes'8 bes'8~] bes'4. c'8 | bes'8[ bes'8 bes'8 bes'8] bes'8[ a'8~ a'8 g'8] \break | f'8[ g'8~ g'8 a'8~] a'4. a'8 | a'8[ g'8~ g'8 f'8~] f'4 a'8[ bes'8] | c''8[ c''8] c''4~ c''2 \break | c''8[ c''8 c''8 c''8(] c''8[ bes'8~ bes'8) a'8] | g'8[ a'8~ a'8 bes'8~] bes'2~ | bes'2. r8 c'8 \break | bes'8 bes'4.~ bes'2 | bes'8[ bes'8~ bes'8 bes'8~] bes'4 a'8[ g'8] | g'8 f'4.~ f'2~ | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 | s8 s4. s2 | s8 s8 s8 s8 s4 s8 s8 | a8 s4. s2 | a2. s8 s8 | a8:7 s8 s8 s8 s4. s8 | s8 s8 s8 s8 s8 s8 s8 s8 | d8 s8 s8 s8 s4. s8 | b8:m s8 s8 s8 s4 s8 s8 | d8 s8 s4 s2 | d8:7 s8 s8 s8 s8 s8 s8 s8 | e8:m s8 s8 s8 s2 | s2. s8 s8 | a8:7 s4. s2 | s8 s8 s8 s8 s4 s8 s8 | d8 s4. g2 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Be" -- "lov" -- "ed," _ "let" "us" _ "love" _ "one" "an" -- "oth" -- "er," _ _ "For" "love" "is" "of" "God," _ "And" "ev" -- "ery" -- "one" "that" "lov" -- "eth" _ "is" "born" "of" _ "God" _ "And" "know" -- "eth" _ "God." _ "He" "that" "lov" -- "eth" "not" _ "know" -- "eth" "not" "God," _ _ _ "For" "God" "is" _ "love." _ _ "Be" -- "lov" -- "ed," _ "let" "us" _ "love" _ "one" "an" -- "oth" -- "er." _ _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

