\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS563.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 1)" \null }
    \vspace #0.82
  }
  system-system-spacing = #'((basic-distance . 13.49) (minimum-distance . 13.49) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "The Rainbow"
  subtitle = "Worship of the Father — His Faithfulness"
  opus = ""
}

global = {
  \key ees \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  ees'4. f'8 g'4 f'4 | aes'4 g'4 f'8([ d'8)] ees'4 | c''4 bes'4 aes'4 g'4 | f'4 g'8([ ees'8)] bes'2 \break | ees'4. f'8 g'4 f'4 | aes'4 g'4 f'8([ d'8)] ees'4 | c''4 bes'4 aes'4 g'4 | f'4 g'8([ ees'8)] bes'2 \break | f'4 g'4 f'8([ d'8)] bes4 | aes'4 g'4 f'8([ d'8)] bes4 | bes'4 aes'4 g'4. g'8 | a'4. a'8 bes'2 \break | ees''4. d''8 c''4 bes'4 | c''4. bes'8 bes'8([ aes'8)] g'4 | f'4 g'8([ aes'8)] bes'8([ c''8) aes'8( f'8)] | ees'4 g'8([ f'8)] ees'2 \bar "|."
}

harmonies = \chordmode {
  \global
  d4. s8 s4 s4 | g4 s4 a8 s8 d4 | g4 s4 s4 s4 | e4:7 s8 s8 a2 | d4. s8 s4 s4 | g4 s4 a8 s8 d4 | g4 s4 s4 s4 | e4:7 s8 s8 a2 | a4 s4 s8 s8 s4 | s4 s4 s8 s8 s4 | d4 s4 s4. s8 | e4.:7 s8 a2 | d4. s8 s4 s4 | g4. s8 d8 s8 s4 | a4 s8 s8 d8 s8 s8 s8 | a4 a8:7 s8 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "God" "has" "set" "His" "sign," "a" "rain" -- _ "bow," "Midst" "the" "rain" -- "y" "clouds" "a" -- _ "bove;" "’Tis" "the" "to" -- "ken" "of" "His" "cov’" -- _ "nant" "With" "the" "man" "and" "earth" "He" _ "loves;" "Ne’er" "a" -- "gain" _ "to" "send" "a" "del" -- _ "uge," "Hence" "His" "faith" -- "ful" -- "ness" "is" "told!" "He" "is" "true" "to" "ev" -- "ery" "prom" -- _ "ise," "And" "His" _ _ "change" -- "less" _ "word" "we" _ "hold!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "The appearance of that rainbow," "Brightly in its splendor’s shown" "’Round the Lamb-God of redemption," "Seated there upon the throne;" "With His righteousness and glory" "And His holiness He shines!" "Colors blue and red and yellow" "Show forth heaven’s hues divine!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Lo! The open door in heaven;" "See the jasper God enthroned." "That same firm, majestic rainbow" "Still surrounds the reigning One." "Though He must judge fallen sinners," "With the rainbow He is crowned!" "He must spare us as He promised;" "By His cov’nant He is bound!" } }
      \vspace #0.88
      \line { \bold "4." \column { "New Jerusalem’s foundation" "Is adorned with precious stones;" "On the colors of a rainbow" "Rests the building God would own." "Now His steadfastness eternal" "For that City is secured!" "We the saved ones joy to witness:" "“Yes! God’s faithfulness endures!”" } }
    }
    \left-column {
      \line { \bold "5." \column { "God is faithful, who has called us," "To His Son’s communion real;" "When we share in Christ our wisdom," "He on us His image seals;" "Attributes of God wrought in us" "Make us righteous, holy, bright!" "Soon we, too, will be a rainbow" "For His pleasure, His delight!" } }
      \vspace #0.88
      \line { \bold "6." \column { "May the meaning of the rainbow" "Be our full reality;" "In the church and in our living," "God expressed for all to see;" "’Round the throne in that bright City," "Grateful voices we shall raise:" "“God is faithful in salvation!" "Shout to His eternal praise!”" } }
    }
  }
}
