\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS677.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #1.04
  }
  system-system-spacing = #'((basic-distance . 13.07) (minimum-distance . 13.07) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "’Tis because Thou drawest me"
  subtitle = "Praise of the Lord — His Beauty"
  opus = ""
}

global = {
  \key f \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'8.[ c'16] | a'4. a'8 g'8[ f'8] | c'4 r4 d'8.[ e'16] | f'4. a'8 d''8[ c''8] \break | g'4 r4 c'8.[ c'16] | a'4. a'8 g'8[ f'8] | d'4 r4 f'8[ g'8] | a'4. c'8 a'8.[ g'16] \break | f'2 a'8.[ a'16] | a'4. d''8 cis''8[ d''8] | a'4 r4 d'8.[ e'16] | f'4. f'8 e'8[ d'8] \break | a'4 r4 a'8.[ a'16] | a'4. d''8 cis''8[ d''8] | a'4 r4 d'8.[ e'16] | f'4. f'8 g'8[ gis'8] \break | a'2^\fermata a'8.[ a'16] | a'4. a'8 g'8[ f'8] | c'4 r4 d'8.[ e'16] | f'4. a'8 d''8[ c''8] \break | g'4 r4 a'8.[ bes'16] | c''4. c''8 bes'8[ a'8] | d''4 r4 f'8[ g'8] | a'4. c'8 a'8.[ g'16] | f'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d8. s16 | s4. s8 s8 s8 | s4 s4 s8. s16 | b4.:m s8 s8 s8 | a4 s4 s8. s16 | d4. s8 s8 s8 | g4 s4 s8 s8 | d4. s8 a8.:7 s16 | d2 s8. s16 | b4.:m s8 s8 s8 | s4 s4 s8. s16 | g4. s8 s8 s8 | fis4 s4 s8. s16 | b4.:m s8 s8 s8 | s4 s4 s8. s16 | g4. s8 s8 s8 | fis2 s8. s16 | d4. s8 s8 s8 | s4 s4 s8. s16 | b4.:m s8 s8 s8 | a4 s4 s8. s16 | d4. s8 s8 s8 | g4 s4 s8 s8 | d4. s8 a8.:7 s16 | d2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "’Tis" "be" -- "cause" "Thou" "draw" -- "est" "me" "I" "can" "close" -- "ly" "fol" -- "low" "Thee;" "Thy" "for" -- "bear" -- "ance" "can" "ap" -- "praise," "Thee" "ex" -- "pe" -- "rience" "all" "my" "days." "Hen" -- "na" "flow’r," "Thy" "love" -- "li" -- "ness" "Beau" -- "ti" -- "fies" "earth’s" "wil" -- "der" -- "ness;" "Like" "the" "fra" -- "grant" "myrrh" "to" "me," "In" "my" "heart" "I’ve" "hid" -- "den" "Thee." "Hear," "O" "Lord," "my" "whis" -- "pered" "plea:" "Hence" -- "forth" "I’ve" "no" "Lord" "but" "Thee;" "All" "Thy" "wealth" "is" "joy" "to" "me," "By" "Thy" "life" "ma" -- "tured" "I’d" "be."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

