\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS841.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 9.03\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar)" \null }
    \vspace #1.11
  }
  system-system-spacing = #'((basic-distance . 12.15) (minimum-distance . 12.15) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Blessed is the man whose strength is in You"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key g \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  d'8 d'4.~( d'4~ | d'2) g'8[ g'8] | e'2.~ | e'2 g'4 | a'2.~ \break | a'2 a'8[ g'8] | fis'2.~ | fis'2 d'8[ d'8] | d''2.~ \break | d''2 d''8[ d''8] | d''2. | c''2 b'4 | b'2.~( | b'4 c''4 b'4) | a'2.~ | a'2. \break | b2 d'4 | d'2 d'4 | e'4 d'4 c'4 | c'8[ b8~] b2 \break | e'2. | e'4 fis'4 g'4 | fis'2( e'4 | d'2) b4 \break | d'2.~ | d'2 d'4 | e'2 d'4 | c'2. \break | e'2 e'4 | e'2 g'4 | a'2( g'4) \break | fis'2 d'4 | g'2 g'4 | g'2 g'4 | d''2.~ | d''2. \break | e'2 e'4 | e'2 g'4 | fis'4 fis'4 g'4 | a'4 fis'4 d'4 \break | g'2 g'4 | g'2 g'4 | d''2.~ | d''2. \break | e'2 e'4 | e'2 g'4 | fis'4 fis'4 g'4 | a'4( fis'4 d'4) | g'2.~ | g'2. \bar "|."
}

harmonies = \chordmode {
  \global
  g8 s4. s4 | s2 s8 s8 | c2. | s2 s4 | a2.:m | a2:m s8 s8 | d2. | s2 s8 s8 | g2. | g2 s8 s8 | c2. | s2 s4 | a2.:m | s4 s4 s4 | d2. | s2. | g2 s4 | s2 s4 | c4 s4 s4 | s8 s8 s2 | a2.:m | s4 s4 s4 | d2 s4 | s2 s4 | g2. | s2 s4 | c2 s4 | s2. | a2:m s4 | s2 s4 | d2 s4 | d2 s4 | g2 s4 | s2 s4 | c2. | s2. | a2:m s4 | s2 s4 | d4 s4 s4 | s4 s4 s4 | g2 s4 | s2 s4 | c2. | s2. | a2:m s4 | s2 s4 | d4 s4 s4 | s4 s4 s4 | g2. | s2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Bless" -- "ed" _ _ "is" "the" "man" _ "whose" "strength" _ "is" "in" "You," _ "In" "whose" "heart" _ "are" "the" "high" -- "ways" "to" "Zi" -- _ _ _ "on." _ "Pass" -- "ing" "through" "the" "val" -- "ley" "of" "Ba" -- "ca," _ "They" "make" "it" "a" "spring;" _ _ "In" -- "deed" _ "the" "ear" -- "ly" "rain" "cov" -- "ers" "it" "with" "bless" -- _ "ings." "They" "go" "from" "strength" "to" "strength;" _ "Each" "ap" -- "pears" "be" -- "fore" "God" "in" "Zi" -- "on." "They" "go" "from" "strength" "to" "strength;" _ "Each" "ap" -- "pears" "be" -- "fore" "God" "in" "Zi" -- _ _ "on." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

