\version "2.24.3"

% Generated by svg-to-lilypond from guitarSvg/NS970.svg

#(set-global-staff-size 15.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.15\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \fill-line { \bold \italic "(Guitar: Capo 3)" \null }
    \vspace #0.99
  }
  system-system-spacing = #'((basic-distance . 12.83) (minimum-distance . 12.83) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.04) (minimum-distance . 15.04) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Forever Love"
  subtitle = "Experience of Christ — As Love"
  opus = ""
}

global = {
  \key f \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'4 \bar ".|:" | f'2 f'4 | f'2 f'4 | e'4 f'4 g'4~ | g'4 r4 c'4 | f'2. | f'2. | d'2. \break | r2 c'4 | f'2 f'4 | f'2 f'4 | e'4 f'4 g'4~ | g'4 r4 e'4 | f'2. | f'2. | g'2. \break | r2 a'4 | c''4 bes'4 a'4 | a'2 f'4 | g'4 a'4 a'4~ | a'4 r4 f'4 | a'4 g'4 f'4 | a'4 g'4 f'4 | d'2.( \break | c'4) r4 a'4 | c''4 bes'4 a'4 | a'2 f'4 | g'4 a'4 a'4~ | a'4 r4 f'4 | a'2. | c''2. \break | f'2 c'4 | f'4^\markup { \bold "Chorus Part 1" } g'4 a'4 | a'2. | f'2. | a'2. | g'2. | f'2. | r2. \break | r2 c'4 | f'4 g'4 a'4 | a'2. | f'2. | a'2. | g'2. | f'2. | r4 a'4 bes'4 | c''4( bes'4) a'4 \break | f'2 c''4 | c''2^\markup { \bold "Chorus Part 2" } f'4 | f'2 c''4 | c''2 f'4 | g'2 f'4 | c''2 c''4 | c''4 bes'4 a'4 | g'4 f'2 \break | r2 c''4 | c''2 f'4 | f'2 c''4 | c''2 g'4 | g'4( a'4) bes'4 | \set Score.repeatCommands = #'((volta "1.")) a'4 f'2 | r2. | r2. | r2 c'4 \bar ":|." | \set Score.repeatCommands = #'((volta #f) (volta "2.")) a'4 f'2 | r2. \break | r2 c'4 | f'4 g'4 a'4 | a'2. | f'2. | a'2. | g'2. | f'2. | r2. \break | r2 c'4 | f'4 g'4 a'4 | a'2. | f'2. | a'2. | g'2. | f'2. \bar "|." \set Score.repeatCommands = #'((volta #f))
}

harmonies = \chordmode {
  \global
  d4 | s2 s4 | s2 s4 | a4 s4 s4 | s4 s4 s4 | b2.:m | s2. | g2. | g2 s4 | d2 s4 | s2 s4 | a4 s4 s4 | s4 s4 s4 | b2.:m | s2. | g2. | g2 s4 | d4 s4 s4 | s2 s4 | a4 s4 s4 | s4 s4 s4 | b4:m s4 s4 | s4 s4 s4 | g2. | g4 s4 s4 | d4 s4 s4 | s2 s4 | a4 s4 s4 | s4 s4 s4 | b2.:m | a2. | g2 s4 | s4 s4 s4 | d2. | s2. | a2. | s2. | b2.:m | s2. | g2 s4 | s4 s4 s4 | d2. | s2. | a2. | s2. | b2.:m | s4 s4 s4 | g4 s4 s4 | g2 s4 | d2 s4 | s2 s4 | a2 s4 | s2 s4 | b2:m s4 | s4 s4 s4 | g4 s2 | g2 s4 | d2 s4 | s2 s4 | a2 s4 | s4 s4 s4 | b4:m s2 | s2. | g2. | s2 s4 | b4:m s2 | s2. | g2 s4 | s4 s4 s4 | d2. | s2. | a2. | s2. | b2.:m | s2. | g2 s4 | s4 s4 s4 | d2. | s2. | a2. | s2. | d2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Dear" "Lord," "You" "want" "me" "as" "Your" "bride," _ "all" "for" "Your" "own." "So" "now" "my" "heart" "I" "o" -- "pen" "wide;" _ "it’s" "Yours" "a" -- "lone." "An" "in" -- "ti" -- "mate" "love," "af" -- "fec" -- "tion" -- "ate," _ "is" "all" "that" "You’re" "seek" -- "ing" "in" "me." _ "To" "live" "in" "Your" "pres" -- "ence," "day" "by" "day," _ "in" "u" -- "ni" -- "ty." "You" "have" "a" "for" -- "ev" -- "er" "love" "for" "me." "I" "have" "a" "for" -- "ev" -- "er" "love" "for" "You," "All" "be" -- "cause" _ "of" "You." "Your" "love" "found" "me," "at" -- "tract" -- "ed" "me;" "Your" "end" -- "less" "love" "has" "dis" -- "armed" "me." "You’ve" "poured" "Your" "love" "in" -- "to" "my" _ "heart" "to" "love" "You." -- "⠀" "love" "You." "You" "have" "a" "for" -- "ev" -- "er" "love" "for" "me." "I" "have" "a" "for" -- "ev" -- "er" "love" "for" "You."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Your love is like a rushing wave, constraining me" "To love You with my very life, no longer free." "O Lord, keep me ever in Your love; Your Word keep empowering me" "To love You in body, soul, and strength, with my whole being." } }
      \vspace #0.88
      \line { \bold "3." \column { "My love for You is not my own; You first loved me." "You are Eternal Love itself and live in me." "The more that I open to Your love, the more love arises in me." "Our love we’ll enjoy forevermore, eternally." \translate #'(2.73 . -2.00) "(Chorus Part 1 & Part 2)" \translate #'(2.73 . -5.00) "You have a forever love for me." \translate #'(2.73 . -5.00) "I have a forever love for You." \translate #'(2.73 . -7.00) "Chorus Parts 1 and 2 can be sung together." } }
    } \hspace #1.1 }
    \null
  }
}
