\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/BF32.svg

#(set-global-staff-size 15.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.39\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.75
  }
  system-system-spacing = #'((basic-distance . 13.07) (minimum-distance . 13.07) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I know not what awaits me (New Tune)"
  subtitle = "Comfort in Trials—By Trusting the Lord"
  opus = "711"
}

global = {
  \key ees \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  ees'8([ f'8)] | g'2 g'4 | g'2 aes'4 | g'8([ f'8)] ees'2~ | ees'2 bes'4 | bes'2 c''4 | bes'4.( aes'8) g'4 | g'2.~ \break | g'2 bes'4 | c''2 c''4 | c''4.( bes'8) aes'8[ bes'8] | c''2 d''4 | c''2 bes'8([ aes'8)] | g'2 aes'4 | bes'2 ees'4 | f'2.~ \break | f'2 bes'8([ aes'8)] | g'2 aes'4 | f'2 g'4 | ees'2 ees'4 | ees''2 d''4 | c''4( bes'4) bes'4 | bes'2 a'4 | bes'2.~ \break | bes'2 g'8([ aes'8)]^\markup { \box \bold "Chorus" } | bes'2 bes'4 | bes'4.( c''8) bes'8([ aes'8)] | g'8([ f'8)] ees'2~ | ees'2 c'8([ d'8)] | ees'2 ees'4 | ees'4.( f'8) g'4 | f'2.~ \break | f'2 g'8([ aes'8)] | bes'2 bes'4 | bes'4.( c''8) bes'8([ aes'8)] | g'8[ f'8] ees'2~ | ees'2 c'8([ d'8)] | ees'2 ees'4 | ees'4.( f'8) g'4 | f'2.~ \break | f'2 g'8([ f'8)] | ees'2 d'8([ c'8)] | d'2 ees'8([ f'8)] | g'2 f'4 | ees'2 ees'4 | ees'2 aes'8([ g'8)] | f'4.( ees'8) d'4 | ees'2.~ | ees'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  ees8 s8 | s2 s4 | bes2 s4 | ees8 s8 s2 | s2 s4 | f2:m s4 | bes4. s8 s4 | ees2. | ees2:7 s4 | aes2 s4 | aes4./ees s8 s8 s8 | aes2 s4 | bes2:7/aes s8 s8 | ees2/g s4 | c2:m s4 | f2.:m7 | bes2:7 s8 s8 | ees2 s4 | bes2/d s4 | ees2 s4 | c2:m s4 | aes4 s4 s4 | f2:7 s4 | bes2. | bes2:7 s8 s8 | ees2 s4 | aes4./ees s8 s8 s8 | ees8 s8 s2 | s2 s8 s8 | c2:m s4 | aes4. s8 s4 | bes2. | bes2/d s8 s8 | ees2 s4 | bes4.:7 s8 s8 s8 | ees8 s8 s2 | s2 s8 s8 | c2:m s4 | aes4. s8 s4 | bes2. | bes2 s8 s8 | c2:m s8 s8 | bes2 s8 s8 | ees2 s4 | c2:m s4 | aes2 s8 s8 | bes4.:7 s8 s4 | aes2./ees | ees2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "I" _ "know" "not" "what" "a" -- _ "waits" "me," _ "God" "kind" -- "ly" "veils" _ "my" "eyes," _ "And" "o’er" "each" "step" _ "of" "my" "on" -- "ward" "way" "He" _ "makes" "new" "scenes" "to" "rise;" _ _ "And" "ev" -- "ery" "joy" "He" "sends" "me" "comes" "A" "sweet" _ "and" "glad" "sur" -- "prise." _ _ \set stanza = "(C)" "Where" "He" "may" "lead" _ "I’ll" _ "fol" -- _ "low," _ "My" _ "trust" "in" "Him" _ "re" -- "pose;" _ _ "And" "ev" -- "ery" "hour" _ "in" _ "per" -- "fect" "peace," _ "I’ll" _ "sing," "“He" "knows," _ "He" "knows“;" _ _ "And" "ev" -- "ery" _ "hour" "in" _ "per" -- "fect" "peace," "I’ll" "sing," _ "“He" "knows," _ "He" "knows.”" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "One step I see before me," "’Tis all I need to see," "The light of heaven more brightly shines" "When earth’s illusions flee;" "And sweetly through the silence comes," "His loving, “Trust in Me!”" } }
      \vspace #0.88
      \line { \bold "3." \column { "Oh, blissful lack of wisdom," "’Tis blessed not to know;" "He holds me with His own right hand," "And will not let me go," "And lulls my troubled soul to rest" "In Him who loves me so." } }
    }
    \left-column {
      \line { \bold "4." \column { "So on I go not knowing;" "I would not if I might;" "I’d rather walk in the dark with God" "Than go alone in the light;" "I’d rather walk by faith with Him" "Than go alone by sight." } }
    }
  }
}
