\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/BF425.svg

#(set-global-staff-size 14.500)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.37\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.72
  }
  system-system-spacing = #'((basic-distance . 12.68) (minimum-distance . 12.68) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.90) (minimum-distance . 14.90) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Once it was the blessing (New Tune)"
  subtitle = "Experience of Christ—As Everything"
  opus = "513"
}

global = {
  \key ees \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  bes'2 bes'4 | bes'4( aes'4) g'4 | g'2( ees'4) | c'2. | ees'2 ees'4 | f'4( g'4) aes'4 | bes'2.~ | bes'2. \break | bes'2 bes'4 | bes'4( aes'4) g'4 | g'2( ees'4) | c'2. | ees'2 ees'4 | d'2 d'4 | ees'2.~ | ees'2. \break | bes'2 c''4 | bes'2 aes'8([ g'8)] | f'2( g'4) | g'2. | r4 aes'4 bes'4 | bes'4( aes'4) g'4 | f'2.~ | f'2. \break | bes'2 bes'4 | bes'4( aes'4) g'4 | g'2( ees'4) | c'2. | ees'2 ees'4 | d'2 d'4 | ees'2.~ | ees'2. \break | bes'2^\markup { \box \bold "Chorus" } c''4 | bes'2 aes'8([ g'8)] | f'2( g'4) | g'2. | r4 aes'4 bes'4 | bes'4( aes'4) g'4 | f'2.~ | f'2. \break | bes'2 bes'4 | bes'4( aes'4) g'4 | g'2( ees'4) | c'2 ees'4 | ees'2 ees'4 | d'2 d'4 | ees'2.~ | ees'2. \bar "|."
}

harmonies = \chordmode {
  \global
  ees2 s4 | bes4/d s4 s4 | c2:m ees4/bes | aes2. | ees2/bes s4 | bes4:7 s4 s4 | ees2. | bes2.:7 | ees2 s4 | bes4/d s4 s4 | c2:m ees4/bes | aes2. | ees2/bes s4 | bes2:7 s4 | aes2./ees | ees2. | aes2 s4 | ees2/g aes8 s8 | bes2 s4 | c2.:m | f4:m7 s4 s4 | ees4/g s4 aes4 | bes2. | bes2.:7 | ees2 s4 | bes4/d s4 s4 | c2:m ees4/bes | aes2. | ees2/bes s4 | bes2:7 s4 | ees2. | s2. | aes2 s4 | ees2/g aes8 s8 | bes2 s4 | c2.:m | f4:m7 s4 s4 | ees4/g s4 aes4 | bes2. | bes2.:7 | ees2 s4 | bes4/d s4 s4 | c2:m ees4/bes | aes2 s4 | ees2/bes s4 | bes2:7 s4 | aes2./ees | ees2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Once" "it" "was" _ "the" "bless" -- _ "ing," "Now" "it" "is" _ "the" "Lord;" _ "Once" "it" "was" _ "the" "feel" -- _ "ing," "Now" "it" "is" "His" "Word;" _ "Once" "His" "gift" "I" _ "want" -- _ "ed," "Now," "the" "Giv" -- _ "er" "own;" _ "Once" "I" "sought" _ "for" "heal" -- _ "ing," "Now" "Him" -- "self" "a" -- "lone." _ \set stanza = "(C)" "All" "in" "all" "for" -- _ "ev" -- _ "er," "On" -- "ly" "Christ" _ "I’ll" "sing;" _ "Ev" -- "ery" -- "thing" _ "is" "in" _ "Christ," "And" "Christ" "is" "ev" -- "ery" -- "thing." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Once ’twas painful trying," "Now ’tis perfect trust;" "Once a half salvation," "Now the uttermost;" "Once ’twas ceaseless holding," "Now He holds me fast;" "Once ’twas constant drifting," "Now my anchor’s cast." } }
      \vspace #0.88
      \line { \bold "3." \column { "Once ’twas busy planning," "Now ’tis trustful prayer;" "Once ’twas anxious caring," "Now He has the care;" "Once ’twas what I wanted," "Now what Jesus says;" "Once ’twas constant asking," "Now ’tis ceaseless praise." } }
    }
    \left-column {
      \line { \bold "4." \column { "Once it was my working," "His it hence shall be;" "Once I tried to use Him," "Now He uses me;" "Once the pow’r I wanted," "Now the Mighty One;" "Once for self I labored," "Now for Him alone." } }
      \vspace #0.88
      \line { \bold "5." \column { "Once I hoped in Jesus," "Now I know He’s mine;" "Once my lamps were dying," "Now they brightly shine;" "Once for death I waited," "Now His coming hail;" "And my hopes are anchored" "Safe within the veil." } }
    }
  }
}
