\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/C132.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 9.01\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.84
  }
  system-system-spacing = #'((basic-distance . 14.29) (minimum-distance . 14.29) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.95) (minimum-distance . 14.95) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "長似東西無終點"
  subtitle = "讚美主－祂的愛"
  opus = "C132"
}

global = {
  \key g \major
  \time 6/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'2 g'4 g'2 e'4 | d'2 cis'4 d'2. | g'2 g'4 g'2 e'4 | d'2 cis'4 d'2. \break | fis'2 fis'4 g'2 g'4 | a'4( g'4) a'4 b'2. | c''2 c''4 b'2 b'4 | cis''4( b'4) cis''4 d''2 b'4 | a'2. a'2. | d'2.~ d'2 r4 \break | g'2^\markup { \box \bold "副" } d'4 g'2 d'4 | b'2. g'2. | d''2. c''2 a'4 | g'2.~ g'2 r4 \break | g'2 fis'4 g'2 e'4 | d'2 g'4 b'2. | a'2 gis'4 a'2 fis'4 | g'2 b'4 d''2 e''4 | d''2. fis'2. | g'2.~ g'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g2 s4 c2 s4 | g2 s4 s2. | g2/b s4 c2 s4 | g2 s4 s2. | d2:7 s4 g2/b s4 | d4:7 s4 s4 g2. | d2:7/fis s4 g2 s4 | a4:7 s4 s4 d2 g4 | d2./a a2.:7 | d2. d2:7 s4 | g2 s4 c2/g s4 | g2. s2. | g2./b d2:7/a s4 | g2. g2:7/b s4 | c2 s4 c2/e s4 | g2 s4 e2.:m | d2 s4 d2:7/c s4 | g2/b s4 g2 c4 | g2./d d2.:7 | g2 c4/g g2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "長" "似" "東" "西" "無" "終" "點，" "闊" "似" "宇" "宙" "無" "邊" "岸，" "高" "似" "高" "天" "無" _ "限" "量，" "深" "似" "深" "海" "無" _ "底" "疆，" "基" "督" "大" "愛！" _ "大" "哉，" "大" "哉，" "大" "哉，" "基" "督" "大" "愛！" _ "長、" "闊、" "高、" "深" "不" "能" "度，" "豐" "滿、" "優" "厚" "臨" "及" "我，" "直" "到" "萬" "代！" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "長得使祂來捨身，" "闊得使祂成救恩，" "高得使祂將我升，" "深得使祂臨我生，" "基督大愛！" } }
      \vspace #0.88
      \line { \bold "3." \column { "長得使我得赦免，" "闊得使我蒙恩典，" "高得使我天上坐，" "深得在我裡面活，" "基督大愛！" } }
      \vspace #0.88
      \line { \bold "4." \column { "長、闊，並非何尺度，" "高、深，也非何事物；" "『長、』『闊，』" "二形乃是指，" "『高、』『深，』" "二者也都是，" "基督大愛！" } }
    } \hspace #1.1 }
    \null
  }
}
