\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH107.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.84\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.08
  }
  system-system-spacing = #'((basic-distance . 12.00) (minimum-distance . 12.00) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net; © 2014 Bible StorySongs, Inc. Used by permission." }
}

\header {
  title = "What Kind of a Sharer?"
  subtitle = "Principles on How to Be a Proper Human Being — General"
  opus = ""
}

global = {
  \key c \major
  \time 2/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  e'4 | e'4 c'4~ | c'4 d'4 | e'4 c'4~ | c'4 d'4 | e'4 e'4 | f'4 e'4 | d'2 \break | r4 f'4 | f'4 d'4~ | d'4 e'4 | f'4 d'4~ | d'4 g'4 | g'4 g'4 | a'4 g'4 | e'2 \break | r4 e'4 | e'4 e'4 | e'4 e'4 | d'4 c'4 | c'4 c'4 | e'4 e'4 | f'4 g'4 | a'2~ | a'4 r4 \break | g'8[ g'8] g'4 | g'4 e'4 | g'4 g'4 | g'4 e'4 | g'4 f'4 | e'4 d'4 | c'2~ | c'4 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | g2:7 | g4:7 s4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | c2 | c4 s4 | s4 s4 | s4 s4 | s4 s4 | s4 s4 | c4:7 s4 | s4 s4 | f2 | s4 s4 | c8 s8 s4 | s4 s4 | a4:7 s4 | s4 s4 | d4:m s4 | g4:7 s4 | c2 | s4 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "What" "kind" "of" _ "a" "shar" -- "er" _ "does" "ev" -- "ery" -- "bod" -- "y" "love?" "What" "kind" "of" _ "a" "shar" -- "er" _ "does" "ev" -- "ery" -- "bod" -- "y" "love?" "While" "play" -- "ing" "with" "my" "broth" -- "ers" "and" "my" "sis" -- "ters" "and" "my" "friends," _ "Ev" -- "ery" -- "one" "loves" "a" "gen" -- "’rous," "will" -- "ing" "shar" -- "er" "with" "a" "grin." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "My snacks and my muffins, my favorite truck or hat;" "My colors, my markers; I’m sharing this and that." "It’s not because I have to, and it’s not with a pity-pout!" "When we share with everyone we’re happy — there’s no doubt." } }
    } \hspace #1.1 }
    \null
  }
}
