\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH110.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.84\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.07
  }
  system-system-spacing = #'((basic-distance . 12.41) (minimum-distance . 12.41) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net; © 2007 Bible StorySongs, Inc. Used by permission." }
}

\header {
  title = "By Faith We Understand"
  subtitle = "Gospel — God’s Creation"
  opus = ""
}

global = {
  \key d \major
  \time 6/8
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  a8 | d'4 a8 e'4 a8 | fis'4.~ fis'4 a8 \break | d'4 a8 e'4 a8 | fis'4.~ fis'4 fis'8 \break | g'4 fis'8 e'4 a'8 | fis'4( e'8) d'4 a8 \break | a8([ e'8) a8] a8([ e'8) a8] | d'4.~ d'4 r8 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 | s4 s8 a4:7 s8 | d4. s4 s8 | d4 s8 a4:7 s8 | d4. s4 s8 | a4:7 s8 s4 s8 | d4 s8 s4 s8 | a8:7 s8 s8 s8 s8 s8 | d4. s4 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "By" "faith" "we" "un" -- "der" -- "stand," _ "by" "faith" "we" "un" -- "der" -- "stand," _ "the" "un" -- "i" -- "verse" "was" "framed" _ "by" "the" "word," _ "the" "word" _ "of" "God!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

