\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH178.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.85\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.18
  }
  system-system-spacing = #'((basic-distance . 12.13) (minimum-distance . 12.13) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Choices, Choices"
  subtitle = "Principles on How to Be a Proper Human Being — General"
  opus = ""
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  fis'4 d'4 fis'4 d'4 | e'8.[ dis'16 e'8. g'16] fis'4 d'4 | fis'4 cis'4 d'4 b4 | e'8.[ d'16 cis'8. b16] a2 \break | fis'4 d'4 fis'4 d'4 | e'8.[ dis'16 e'8. g'16] fis'4 d'4 | fis'4 a'4 d'8.[ cis'16 d'8. e'16] | fis'4 e'4 d'2 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 s4 s4 s4 | a8. s16 s8. s16 d4 s4 | fis4 s4 b4:m s4 | e8. s16 s8. s16 a2 | d4 s4 s4 s4 | a8. s16 s8. s16 d4 s4 | s4 s4 g8. s16 s8. s16 | d4/a a4:7 d2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Choic" -- "es," "choic" -- "es," "We" "must" "all" "make" "choic" -- "es—" "Big" "ones," "small" "ones," "Choic" -- "es" "ev" -- "ery" "day." "Choic" -- "es," "choic" -- "es," "We" "must" "all" "make" "choic" -- "es—" "Don’t" "choose" "fool" -- "ish" -- "ly" "But" "choose" "God’s" "way."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Choices, choices," "We must all make choices." "Don’t be jealous" "Of what another has," "Choices, choices," "We must all make choices." "Just be satisfied" "With what you have." } }
    } \hspace #1.1 }
    \null
  }
}
