\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH170.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.84\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.22
  }
  system-system-spacing = #'((basic-distance . 12.00) (minimum-distance . 12.00) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Always Pursue (1 Thessalonians 5:15b)"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  c'4 d'8[ d'8] e'4. g'8 | g'8[ g'8 d'8 f'8] e'8 c'4. \break | c''4 g'8([ a'8)] g'2 | c'8[ c'16 c'16 d'8 d'8] e'2 \break | g'4 f'4 e'2 | e'4 d'4 c'2 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 g8 s8 c4. s8 | s8 s8 g8 s8 c8 s4. | c4 g8 s8 c2 | s8 s16 s16 g8 s8 c2 | c4/e g4:7/d c2 | c4/g g4:7 c2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Al" -- "ways" "pur" -- "sue" "What’s" "good" "for" "one" "an" -- "oth" -- "er" "And" "for" _ "all," "First" "Thes" -- "sa" -- "lo" -- "ni" -- "ans" "Chap" -- "ter" "five:" "fif" -- "teen" "“b”."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

