\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH192.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.85\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.19
  }
  system-system-spacing = #'((basic-distance . 12.01) (minimum-distance . 12.01) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Give and it Shall be Given Unto You"
  subtitle = "Principles on How to Be a Proper Human Being — Helping Others"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  e'2 e'4 f'4 | g'2 e'4( d'4) | c'4 a4 c'4 d'4 | e'1 \break | f'2 g'4( f'4) | e'2 f'4( e'4) | d'1 | g'2. r4 \break | e'2 e'4 f'4 | g'2 e'4( d'4) | c'4 a4 c'4 d'4 | e'1 \break | f'2 g'4 f'4 | e'2 f'4 e'4 | d'1( | c'2.) r4 \break | c''1 | b'1 | a'1 | g'1 \break | a'1 | g'1 | g'2( a'2) | b'1 \break | c''1 | b'1 | a'1 | g'1 \break | f'2( g'4 f'4) | e'2( f'4 e'4) | d'1 | c'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c2 s4 s4 | g2/b s4 s4 | a4:m s4 s4 s4 | c1/g | f2 s4 s4 | c2/e s4 s4 | d1:m | g2.:7 s4 | c2 s4 s4 | g2/b s4 s4 | a4:m s4 s4 s4 | c1/g | f2 s4 s4 | c2/e f4 s4 | g1:7 | c2. s4 | c1 | g1 | f1 | c1 | f1 | c1 | g2 s2 | g1:7 | c1 | g1 | f1 | c1 | f2 s4 s4 | c2 f4 s4 | g1:7 | c2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Give" "and" "it" "shall" "be" _ "giv" -- "en" "un" -- "to" "you," "Pressed" "down," _ "run" -- "ning" _ "o" -- "ver." "Give" "and" "it" "shall" "be" _ "giv" -- "en" "un" -- "to" "you." "Luke," "chap" -- "ter" "six:" "thir" -- "ty" -- "eight" _ "God" "loves" "giv" -- "ers!" "God" "loves" "giv" -- _ "ers!" "God" "loves" "giv" -- "ers!" "God" _ _ "loves" _ _ "giv" -- "ers!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

