\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH202.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.84\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.07
  }
  system-system-spacing = #'((basic-distance . 12.27) (minimum-distance . 12.27) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I Believe the Bible"
  subtitle = "The Word of God — General"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'4 g'4 g'4 g'4 | g'4.( a'8) g'2 | d'4 d'4 c'4 d'4 | e'1 \break | c'4 e'4 g'4 c''4 | c''2 b'2 | a'4 a'4 e'4 fis'4 | g'1 \break | d'4 d'4 g'4 d'4 | e'4.( f'8) e'2 | g'4 g'4 c''4 g'4 | a'1 \break | a'4 g'4 f'4 g'4 | a'4( g'4) f'4( g'4) | a'4 g'4 f'4 e'4 | d'1 \break | c'4^\markup { \box \bold "Chorus" } c'4 c'4 c'4 | c'4( b8[ a8)] b4( c'4) | d'4 d'4 d'4 c'8([ d'8)] | e'1 \break | g'4 g'4 c''4 b'4 | c''2 g'2 | f'4 e'4 d'4. c'8 | c'1^\fermata \bar "|."
}

harmonies = \chordmode {
  \global
  c4 s4 f4 s4 | e4.:m s8 a2:m | d4:m s4 g4:7 s4 | c1 | c4 s4 g4/b s4 | a2:m a2:m/c | d4 s4 d4:7/fis s4 | g1 | g4 s4 g4/b s4 | c4. s8 s2 | c4/e s4 c4 s4 | f1 | f4 s4 s4 s4 | s4 s4 s4 s4 | s4 s4 d4:7/fis s4 | g2 g2:7 | c4 s4 s4 s4 | g4/b s8 s8 s4 s4 | g4:7 s4 s4 s8 s8 | c1 | c4/e s4 g4:7/d s4 | e2:m a2:m | f4 s4 g4.:7 s8 | c4 f4/c c2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "I" "be" -- "lieve" "the" "Bi" -- _ "ble" "Is" "God’s" "Word" "and" "true." "It" "is" "God’s" "own" "speak" -- "ing," "Real" "and" "pre" -- "cious," "too." "Through" "the" "Ho" -- "ly" "Bi" -- _ "ble" "The" "truth" "God" "does" "show." "Through" "the" "Ho" -- "ly" "Bi" -- _ "ble" _ "My" "God" "I" "can" "know." \set stanza = "(C)" "I" "be" -- "lieve" "the" "Bi" -- _ _ "ble" _ "Is" "God’s" "Word" "and" _ "true." "It" "is" "God’s" "own" "speak" -- "ing," "Real" "and" "pre" -- "cious," "too."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

