\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH229.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.85\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.12
  }
  system-system-spacing = #'((basic-distance . 13.33) (minimum-distance . 13.33) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net; © 2013 Bible StorySongs, Inc. Used by permission." }
}

\header {
  title = "The Sun and Moon Didn’t Just Happen"
  subtitle = "Gospel — God’s Creation"
  opus = ""
}

global = {
  \key g \major
  \time 6/8
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  d'8 | d'8[ d'8 d'8] d'8[ e'8 fis'8] | g'4. d'4 g'8 | a'8[ a'8 a'8] a'8[ g'8 a'8] | b'4.~ b'4 d'8 \break | d'8[ d'8 d'8] d'8[ e'8 fis'8] | g'4. d'4 g'8 | a'8[ a'8 a'8] a'8[ b'8 a'8] \break | g'4.~ g'4 g'8 | c''4.~^\markup { \box \bold "Chorus" } c''4 c''8 | b'4.~ b'4 g'8 | a'8[ a'8 a'8] a'8[ g'8 a'8] | b'4.~ b'4 d'8 \break | e'4. c''4 e'8 | d'4. b'4^\fermata g'8 | a'8[ a'8 a'8] a'8[ b'8 a'8] | g'4.~ g'4 r8 \bar "|."
}

harmonies = \chordmode {
  \global
  g8 | s8 s8 s8 c8/g s8 s8 | g4. e4:m s8 | d8/fis s8 s8 d8 s8 s8 | g4. c4/g s8 | g8 s8 s8 d8/fis s8 s8 | e4.:m g4/b s8 | a8:m s8 s8 d8:7 s8 s8 | c4./g g4:7 s8 | c4. s4 s8 | g4. s4 s8 | d8 s8 s8 s8 s8 s8 | g4. g4:7 s8 | c4. s4 s8 | g4. e4:m s8 | a8:m s8 s8 d8:7 s8 s8 | c4./g g4 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "The" "sun" "and" "moon" "did" -- "n’t" "just" "hap" -- "pen," "The" "stars" "were" "con" -- "struct" -- "ed" "to" "glow!!" _ "My" "great," "great," "great," "great," "great," "grand" -- "dad" -- "dy" "Was" "not" "a" "go" -- "ril" -- "la—" "NO," "NO!" _ \set stanza = "(C)" "All" "things," _ "all" "things" _ "Have" "come" "in" -- "to" "be" -- "ing" "through" "Him," _ "Not" "one" "thing," "not" "one" "thing," "Not" "one" "thing" "ex" -- "ists" "with" -- "out" "Him!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "The kittens and puppies and hippos" "Are not from primordial stew," "No random, haphazard event could" "Make something as precious as you." } }
    } \hspace #1.1 }
    \null
  }
}
