\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH44.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.73
  }
  system-system-spacing = #'((basic-distance . 13.13) (minimum-distance . 13.13) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Our God is so big"
  subtitle = "Gospel—God’s Creation"
  opus = ""
}

global = {
  \key d \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  a4 | d'4 d'4 d'4 | fis'2 a4 | d'4 d'4 d'4 | fis'4 e'4 d'4 | e'4 e'4 e'4 | e'4 d'4 cis'4 | d'2.~ \break | d'4 r4 a4 | d'4 d'4 d'4 | fis'2 a4 | d'4 d'4 d'4 | fis'4 e'4 d'4 | e'4 e'4 e'4 | e'4 d'4 cis'4 | d'2.~ \break | d'4 r4 d'4 | g'4 g'4 g'4 | g'2 g'4 | fis'4 fis'4 fis'4 | fis'2 fis'4 | e'4 e'4 e'4 | e'4 d'4 e'4 | fis'2.~ \break | fis'2 a4 | d'4 d'4 d'4 | fis'2 a4 | d'4 d'4 d'4 | fis'4 e'4 d'4 | e'4 e'4 e'4 | e'4 d'4 cis'4 | d'2.~ | d'4 r2 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 | s4 s4 s4 | s2 s4 | s4 s4 s4 | s4 s4 s4 | a4 s4 s4 | a4:7 s4 s4 | d2 g4/d | d4 s4 s4 | s4 s4 s4 | s2 s4 | s4 s4 s4 | s4 s4 s4 | a4 s4 s4 | a4:7 s4 s4 | d2 g4/d | d4 s4 s4 | g4 s4 s4 | s2 s4 | d4 s4 s4 | s2 s4 | a4 s4 s4 | s4 s4 s4 | d2. | d2 s4 | s4 s4 s4 | s2 s4 | s4 s4 s4 | s4 s4 s4 | a4 s4 s4 | a4:7 s4 s4 | d4 g2/d | d4 s2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Our" "God" "is" "so" "big," "So" "strong," "and" "so" "migh" -- "ty—" "There’s" "noth" -- "ing" "our" "God" "can" -- "not" "do." _ "Our" "God" "is" "so" "big," "So" "strong," "and" "so" "migh" -- "ty—" "There’s" "noth" -- "ing" "our" "God" "can" -- "not" "do." _ "The" "moun" -- "tains" "are" "His;" "The" "val" -- "leys" "are" "His;" "The" "stars" "are" "His" "hand" -- "i" -- "work," "too." _ "Our" "God" "is" "so" "big," "So" "strong," "and" "so" "migh" -- "ty—" "There’s" "noth" -- "ing" "our" "God" "can" -- "not" "do." _
}

verseTwo = \lyricmode {
  \set ignoreMelismata = ##t _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ "That’s right!" _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ "That’s right!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
    \addlyrics { \verseTwo }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

