\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH65.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.73
  }
  system-system-spacing = #'((basic-distance . 13.07) (minimum-distance . 13.07) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I’m a vessel this I know"
  subtitle = "Gospel—God’s Creation"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'4 e'4 e'4 d'4 | e'4 g'4 g'2 | a'4 a'4 c''4 a'4 | a'4 g'4 g'2 \break | g'4 e'4 e'4 d'4 | e'4 g'4 g'2 | a'4 a'4 g'4 c'4 | e'4 d'4 c'2 \break | g'2^\markup { \box \bold "Chorus" } e'4 g'4 | a'4 c''2. | g'2 e'4 c'4 | e'4 d'2. \break | g'2 e'4 g'4 | a'4 c''2 a'4 | g'4 c'4 e'4 d'4 | c'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 s4 g4/b s4 | a4:m s4 c2/g | f4 s4 g4:7/f s4 | c4/e s4 g2 | c4 s4 g4/b s4 | a4:m s4 c2/g | f4 s4 c4/e d4:7/fis | c4/g g4:7 c2 | c2 c4:7/e s4 | f4 s4 g2:7/f | e2:m a4:m s4 | d4:m7 s4 g2:7 | c2 c4:7/e s4 | f4 s4 d4:7/fis s4 | c4/g s4 g4:7 s4 | c4 f2/c c4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "I’m" "a" "ves" -- "sel," "this" "I" "know!" "For" "the" "Bi" -- "ble" "tells" "me" "so." "God’s" "the" "Pot" -- "ter," "I’m" "the" "clay;" "He" "made" "me" "this" "spe" -- "cial" "way." \set stanza = "(C)" "Yes," "I’m" "a" "ves" -- "sel," "Yes," "I’m" "a" "ves" -- "sel," "Yes," "I’m" "a" "ves" -- "sel," "The" "Bi" -- "ble" "tells" "me" "so."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

