\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CH99.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 12.84\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.22
  }
  system-system-spacing = #'((basic-distance . 12.51) (minimum-distance . 12.51) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net; © 2012 Bible StorySongs, Inc. Used by permission." }
}

\header {
  title = "He Came Serving"
  subtitle = "Principles on How to Be a Proper Human Being — General"
  opus = ""
}

global = {
  \key e \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  gis'2 e'2 | b8([ cis'8)] b4 cis'4 b4 | gis'2 e'2 | fis'8([ gis'8)] fis'4 cis'4 b4 \break | gis'2 e'2 | a'8([ b'8)] a'4 a'4. a'8 | gis'4 gis'4 fis'4 fis'4 | e'1 \break | gis'2 e'2 | b8[ cis'8] b4 cis'8[ cis'8] b4 | gis'2 e'2 | fis'8[ gis'8] fis'4 cis'8[ cis'8] b4 \break | gis'2 e'2 | a'8[ b'8] a'4 a'4. a'8 | gis'4 gis'4 fis'4 fis'4 | e'4 b4 e'2 \break | gis'4. fis'8 e'4 fis'4 | gis'4 gis'4 gis'2 | fis'4 fis'4 fis'2 | gis'4 b'4 b'2 \break | gis'4. fis'8 e'4 fis'4 | gis'4 gis'4 gis'4 gis'4 | fis'4 fis'4 gis'4 fis'4 | e'4 b8[ cis'8] b8[ a8 gis8 fis8] \bar "|."
}

harmonies = \chordmode {
  \global
  e2 s2 | s8 s8 s4 s4 s4 | s2 s2 | b8 s8 s4 s4 s4 | e2 e2:7 | a8 s8 s4 s4. s8 | e4/b s4 b4:7 s4 | e1 | e2 s2 | s8 s8 s4 s8 s8 s4 | s2 s2 | b8 s8 s4 s8 s8 s4 | e2 e2:7 | a8 s8 s4 s4. s8 | e4/b s4 b4:7 s4 | e4 s4 s2 | e4. s8 s4 s4 | s4 s4 s2 | b4:7 s4 s2 | e4 s4 s2 | e4. s8 s4 s4 | s4 s4 s4 s4 | b4:7 s4 s4 s4 | e4 s8 s8 s8 s8 s8 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "He" "came" "serv" -- _ "ing," "(serv" -- "ing)" "He" "came" "serv" -- _ "ing," "(serv" -- "ing)" "He" "came" "serv" -- _ "ing," "not" "to" "be" "served," "but" "to" "serve." "Mark" "ten," "for" -- "ty" "five," "(for" -- "ty" "five)" "Mark" "ten," "for" -- "ty" "five," "(for" -- "ty" "five)" "Mark" "ten," "for" -- "ty" "five," "not" "to" "be" "served," "but" "to" "serve." "(He" "served!)" "And" "to" "give" "His" "life" "for" "all," "Life" "for" "all," "life" "for" "all;" "And" "to" "give" "His" "life" "for" "all," "A" "ran" -- "som" "for" "us" "all." "(He" "was" "al" -- "ways" "serv" -- "ing!)"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

