\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CS239.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 9.00\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.59
  }
  system-system-spacing = #'((basic-distance . 13.24) (minimum-distance . 13.24) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "我奉耶穌基督的名"
  subtitle = "享受基督"
  opus = "Cs239"
}

global = {
  \key bes \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  bes'4 bes'4 bes'4 | bes'4 f'4 d'4 | ees'2^\fermata f'4 | a'4 a'4 a'4 | a'4 g'4 f'4 \break | d'2^\fermata f'8[ f'8] | bes'2 bes'4 | bes'4 f'4 d'4 | ees'2^\fermata g'4 | f'4. f'8 f'4 | a'4 bes'4 c''4 \break | bes'2^\fermata bes'8[ c''8] | d''4 bes'4 bes'4 | d''4 bes'4 bes'4 | a'2 c''4 | a'2. \break | c''4 a'4 a'4 | c''4 a'4 a'4 | bes'2 g'4 \break | f'2 f'8[ f'8] | bes'2 bes'4 | bes'4 f'4 d'4 \break | ees'2^\fermata g'4 | f'4. f'8 f'4 | a'4 bes'4 c''4 | bes'2. \bar "|."
}

harmonies = \chordmode {
  \global
  bes4 s4 s4 | s4 s4 s4 | c2:m s4 | f4 s4 s4 | f4:7 s4 s4 | bes2 s8 s8 | s2 s4 | s4 s4 s4 | ees2 s4 | f4. s8 s4 | f4:7 s4 s4 | bes2 s8 s8 | s4 s4 s4 | s4 s4 s4 | f2 s4 | s2. | f4 s4 s4 | f4:7 s4 s4 | bes2 s4 | bes2 s8 s8 | s2 s4 | s4 s4 s4 | ees2 s4 | f4. s8 s4 | f4:7 s4 s4 | bes2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "『金" "銀" "財" "寶" "我" "沒" "有，" "只" "把" "我" "所" "有" "的" "給" "你；" "我" "奉" "耶" "穌" "基" "督" "的" "名，" "叫" "你" "現" "在" "起" "來" "行" "走！』" "他" "就" "走" "著，" "又" "跳" "著，" "又" "讚" "美" "神；" "走" "著，" "又" "跳" "著，" "又" "讚" "美" "神。" "阿" "利" "路" "亞，" "讚" "美" "我" "主！" "榮" "耀，" "榮" "耀" "歸" "於" "主" "名！"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "金銀財寶我沒有，" "卻有七倍加強的靈；" "我奉耶穌基督的名，" "剛強站起作祂見證！" "我在召會中" "又讚美又見證，" "召會中又讚美又見證。" "阿利路亞，讚美我主！" "榮耀，榮耀歸於主名！" } }
    } \hspace #1.1 }
    \null
  }
}
