\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CS459.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.65
  }
  system-system-spacing = #'((basic-distance . 12.76) (minimum-distance . 12.76) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.02) (minimum-distance . 15.02) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "與神和好"
  subtitle = "追求與長進"
  opus = "Cs459"
}

global = {
  \key e \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  b'4 | gis'4 fis'4 e'4 fis'8([ e'8)] | cis'2 b4 b'4 | b'4 cis''4 b'4 a'4 \break | gis'2. b'4 | gis'4 fis'4 e'4 fis'8([ e'8)] | cis'2 b4 b4 | e'4 fis'8([ gis'8)] a'8([ gis'8)] fis'4 \break | e'2. b'4 | e''4 dis''4 cis''4 b'4 | b'4( ais'4) b'4^\fermata b'4 | cis''4 b'4 a'4 gis'4 \break | fis'2. b'4 | gis'4 fis'4 e'4 fis'8([ e'8)] | cis'2 b4 b4 | e'4 fis'8([ gis'8)] a'8([ gis'8)] fis'4 | e'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  e4 | s4 s4 s4 s8 s8 | a2 e4 s4 | s4 s4 b4:7 s4 | e2. s4 | s4 s4 s4 s8 s8 | a2 e4 s4 | cis4:m s8 s8 b8:7 s8 s4 | e2. s4 | s4 s4 s4 s4 | s4 s4 s4 s4 | a4 s4 s4 s4 | b2 b4:7 s4 | e4 s4 s4 s8 s8 | a2 e4 s4 | cis4:m s8 s8 b8:7 s8 s4 | e2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "主，" "你" "旨" "意" "我" _ "願" "憑，" "主，" "你" "聖" "言" "我" "聽，" "不" "讓" "閒" "話" "漏" _ "生" "命，" "不" "讓" "俗" _ "務" _ "擾" "靈。" "求" "你" "向" "我" "多" "吸" _ "引，" "使" "我" "與" "你" "更" "親，" "讓" "我" "常" "見" "你" _ "榮" "形，" "緊" "緊" "跟" _ "隨" _ "你" "行。"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "主，你道路我願走，" "不管風狂雨驟，" "雖然有憂也有愁，" "主恩卻更深厚。" "我今追求雖不彀，" "有時會貪優游，" "求你仍把我收留，" "用愛把我浸透。" } }
      \vspace #0.88
      \line { \bold "3." \column { "主，你十架我願負，" "面向你的國度，" "雖然流淚雖然苦，" "你手卻常攙扶。" "前面路程已不長，" "屬天家鄉在望，" "有朝，父懷我安躺，" "我就喜樂歡暢。" } }
      \vspace #0.88
      \line { \bold "4." \column { "主，你榮耀快顯現，" "這是我心所羨，" "你的應許不改變，" "你來將不遲延。" "求主使我能自勉，" "不向世界流連，" "我眼能常望著天，" "心能向你戀戀。" } }
    } \hspace #1.1 }
    \null
  }
}
