\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/CS849.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.97\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.64
  }
  system-system-spacing = #'((basic-distance . 13.28) (minimum-distance . 13.28) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.02) (minimum-distance . 15.02) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "禧年的生活"
  subtitle = "事奉與福音"
  opus = "Cs849"
}

global = {
  \key bes \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  d'8[ ees'8] | f'4 f'4 bes'8[ bes'8 a'8( g'8)] | f'2. d'4 | f'4. g'8 f'4 ees'4 \break | d'2. d'8[ ees'8] | f'4 f'4 bes'8[ bes'8 a'8( g'8)] | f'2. bes'4 | a'4. bes'8 c''4 a'4 \break | bes'2. f'8[ bes'8] | a'2. f'8[ c''8] | bes'2. f'8[ d''8] | c''4. d''8 c''8[ bes'8 a'8( g'8)] \break | f'2. d'8[ ees'8] | f'4 f'4 bes'8[ bes'8 a'8( g'8)] | f'2. bes'4 | a'4. bes'8 c''4 a'4 | bes'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  bes8 s8 | s4 s4 ees8 s8 s8 s8 | bes2. s4 | s4. s8 f4:7 s4 | bes2. s8 s8 | s4 s4 ees8 s8 s8 s8 | bes2. s4 | f4. s8 f4:7 s4 | bes2. s8 s8 | f2 f4:7 s8 s8 | bes2. s8 s8 | f4./c s8 c8:7 s8 s8 s8 | f2 f4:7 s8 s8 | bes4 s4 ees8 s8 s8 s8 | bes2. s4 | f4. s8 f4:7 s4 | bes2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "哦，" "讓" "我" "們" "揚" "聲" "歡" _ "呼，" "角" "聲" "遍" "地" "發" "出，" "同" "宣" "告" "神" "救" "贖" "之" _ "日，" "人" "生" "從" "今" "開" "始；" "出" "黑" "暗，" "脫" "捆" "綁，" "我" "這" "罪" "囚" "大" "得" "釋" _ "放。" "哦，" "讓" "我" "們" "揚" "聲" "歡" _ "呼，" "角" "聲" "遍" "地" "發" "出。"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "哦，讓我們擊鼓跳舞，" "踏著喜悅腳步，" "同進入神恩典禧年，" "前途美好無限；" "我權益都恢復，" "重歸自由，產業豐富。" "哦，讓我們擊鼓跳舞，" "踏著喜悅腳步。" } }
      \vspace #0.88
      \line { \bold "3." \column { "哦，讓我們盡情享受，" "去罷，煩惱、憂愁，" "將你喜樂快快敞開，" "神自己必進來；" "祂豐富充滿我，" "如同大水，全人漫過。" "哦，讓我們盡情享受，" "去罷，煩惱、憂愁。" } }
      \vspace #0.88
      \line { \bold "4." \column { "哦，讓我們喫喝快樂，" "父家滿了詩歌，" "祂是我們完全的愛，" "我們一生年代；" "來安家神居所，" "天天過著禧年生活。" "哦，讓我們喫喝快樂，" "父家滿了詩歌。" } }
    } \hspace #1.1 }
    \null
  }
}
