\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E1066.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.70
  }
  system-system-spacing = #'((basic-distance . 13.46) (minimum-distance . 13.46) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.78) (minimum-distance . 14.78) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Down at the cross"
  subtitle = "Gospel—Testimony"
  opus = "1066"
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  b'4 b'8.[ a'16] g'4 g'8.[ fis'16] | e'4 g'4 d'2 | b'4 b'8.[ b'16] d''4 d''8.[ b'16] | g'4 b'4 a'2 \break | b'4 b'8.[ a'16] g'4 g'8.[ fis'16] | e'4 g'4 d'2 | b'4. g'8 b'4 a'4 | g'2. r4 \break | g'4.^\markup { \box \bold "Chorus" } g'8 g'4 e'4 | d'4.( e'8 g'4) r4 | b'4. b'8 b'4 g'4 | a'4.( b'8 a'4) r4 \break | b'4 b'8.[ a'16] g'4 g'8.[ fis'16] | e'4 g'4 d'2 | b'4. g'8 b'4 a'4 | g'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 s8. s16 g4/b s8. s16 | c4 s4 g2 | s4 s8. s16 e4:m s8. s16 | a4:7 s4 d2 | g4 s8. s16 g4/b s8. s16 | c4 s4 g2 | g4./d s8 d4:7 s4 | g4 c2/g g4 | g4. s8 c4/g s4 | g4. s8 s4 s4 | s4. s8 e4:m s4 | a4.:m s8 d4:7 s4 | g4 s8. s16 g4/b s8. s16 | c4 s4 g4/b c4 | g4./d s8 d4:7 s4 | g4 c2/g g4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Down" "at" "the" "cross" "where" "my" "Sav" -- "ior" "died," "Down" "where" "for" "cleans" -- "ing" "from" "sin" "I" "cried," "There" "to" "my" "sin" "was" "the" "blood" "ap" -- "plied;" "Glo" -- "ry" "to" "His" "name!" \set stanza = "(C)" "Glo" -- "ry" "to" "His" "name," _ _ "Glo" -- "ry" "to" "His" "name;" _ _ "There" "to" "my" "sin" "was" "the" "blood" "ap" -- "plied;" "Glo" -- "ry" "to" "His" "name!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "I am so wondrously saved from sin," "Jesus so sweetly abides within;" "There at the cross where He took me in;" "Glory to His name." } }
      \vspace #0.88
      \line { \bold "3." \column { "Oh, precious fountain that saves from sin," "I am so glad I have entered in;" "There Jesus saves me and keeps me clean;" "Glory to His name." } }
      \vspace #0.88
      \line { \bold "4." \column { "Come to this fountain so rich and sweet;" "Cast thy poor soul at the Savior’s feet;" "Plunge in today, and be made complete;" "Glory to His name." } }
    } \hspace #1.1 }
    \null
  }
}
