\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E1098.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 13.63) (minimum-distance . 13.63) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Our hearts are overflowing"
  subtitle = "Praise of the Lord—His Victory and Exaltation"
  opus = "1098"
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  d'4 | fis'4 a'4 a'4 b'4 | a'2 fis'4 d'4 | cis'4 d'4 g'4 fis'4 | fis'2( e'4) d'4 \break | fis'4 a'4 a'4 b'4 | a'2 fis'4 e'4 | fis'4 b'4 a'4 gis'4 | a'2. a'4 \break | d''4 a'4 g'4 fis'4 | b'2 a'4 cis''4 | d''4 a'4 a'8([ g'8)] fis'4 | fis'2( e'4) d'4 \break | fis'4 a'4 a'4 b'4 | a'2 fis'4 d'4 | e'4 g'4 fis'4 e'4 | d'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 | s4 s4 g4 s4 | d2 s4 s4 | g4 d4/fis a4/e d4 | d2/a a4 s4 | d4 s4 a4/e s4 | d2/fis d4 s4 | b4:m s4 e4:7 s4 | a2 a4/g s4 | d4/fis s4 d4 s4 | g2 d4/fis a4/e | d4 s4 a8/cis s8 d4 | d2/a a4 s4 | d4 s4 a4/e s4 | fis2:m7 b4:m7 s4 | e4:m7/g s4 a4:7 s4 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Our" "hearts" "are" "o" -- "ver" -- "flow" -- "ing" "To" "speak" "a" "good" -- "ly" "thing—" _ "To" "tell" "what" "we’ve" "ex" -- "pe" -- "rienced" "Of" "our" "ex" -- "alt" -- "ed" "King." "Our" "tongues" "as" "pens" "are" "rea" -- "dy," "We’ve" "vo" -- "lumes" "here" _ "to" "“write”—" _ "The" "glo" -- "ries" "of" "our" "Bride" -- "groom," "Our" "Lord" "and" "our" "de" -- "light."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Lord Jesus, Thou art fairer" "Than all the sons of men;" "Thy goodness is transcendent—" "Hallelujah! Amen!" "Upon Thy lips most holy" "Abundant grace is poured;" "Forever God has blessed Thee," "Our gracious, glorious Lord!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Thou art the mighty Warrior" "Who rides to victory;" "In Thy majestic glory" "Ride on triumphantly!" "The peoples fall beneath Thee—" "The conquering One Thou art." "Thine arrows in their sharpness" "Have entered Satan’s heart!" } }
    }
    \left-column {
      \line { \bold "4." \column { "Thy throne, O God, forever" "And ever shall endure;" "The sceptre of Thy kingdom" "Upon the earth is sure." "’Tis with the oil of gladness" "God has anointed Thee" "Above all Thy companions—" "How worthy there to be!" } }
      \vspace #0.88
      \line { \bold "5." \column { "Of aloes, myrrh, and cassia" "Do all Thy garments smell:" "Thy death and resurrection" "Do all Thy deeds forthtell." "Out of the local churches" "Shall praises make Thee glad," "And praises upon praises" "Thy joyful saints shall add." } }
    }
  }
}
