\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E126.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.78
  }
  system-system-spacing = #'((basic-distance . 12.85) (minimum-distance . 12.85) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "To Thee, dear Lord, O Christ of God"
  subtitle = "Praise of the Lord—His Victory"
  opus = "126"
}

global = {
  \key ees \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'4 aes'4 g'4 | bes'2 ees'4 | f'4( g'4) f'4 | ees'2. | c''4 bes'4 g'4 | ees'4( f'4) g'4 | f'2. \break | g'4 g'4 g'4 | g'2 g'4 | a'4( g'4) a'4 | bes'2. | d''4 c''4 g'4 | bes'2 a'4 | bes'2. \break | bes'4 c''4 bes'4 | ees''2 d''4 | d''4( c''4) bes'4 | aes'2. | g'4 fis'4 g'4 | bes'4( aes'4) f'4 | ees'2.( | d'2.) \break | f'4 g'4 f'4 | ees'2 bes'4 | bes'4( aes'4) g'4 | aes'2. | g'4 g'4 f'4 | ees'2 d'4 | ees'2.~ | ees'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  ees4 s4 s4 | ees2/g s4 | aes4 s4 bes4 | ees2. | aes4 s4 ees4/g | c4:m s4 s4 | bes2. | ees4 s4 bes4/d | c2:m s4 | f4 s4 s4 | g2.:m | ees4 s4 c4:m | bes2/f f4 | bes2. | bes4/aes s4 s4 | ees2/g s4 | aes4 s4 ees4/g | f2.:m | ees4 s4 s4 | aes4 s4 s4 | ees2./bes | bes2. | bes4/aes s4 s4 | ees2/g s4 | c4:7 s4 s4 | f2.:m | ees4/g s4 f4:m/aes | ees2/bes bes4:7 | ees4 aes2/ees | ees2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "To" "Thee," "dear" "Lord," "O" "Christ" _ "of" "God," "We" "sing," "we" "ev" -- _ "er" "sing;" "For" "Thou" "hast" "shed" "Thy" "pre" -- _ "cious" "blood" "Our" "cup" "of" "joy" "to" "bring." "Thy" "might" -- "y" "arm" "the" "fight" _ "hath" "fought," "Thou" "art" "en" -- _ "throned" "a" -- "bove;" _ "We" "in" -- "to" "glo" -- "ry" "will" _ "be" "brought" "Thy" "won" -- "drous" "grace" "to" "prove." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "To Thee, dear Lord, O Christ of God," "We sing, we ever sing;" "Thou hast invaded death’s abode" "And robbed him of his sting." "The house of dust enthralls no more," "For Thou, the strong to save," "Thyself doth guard that silent door," "Great Keeper of the grave." } }
      \vspace #0.88
      \line { \bold "3." \column { "To Thee, dear Lord, O Christ of God," "We sing, we ever sing;" "For Thou hast crushed beneath Thy rod" "The world’s proud rebel king," "And plunged in Thine imperial strength" "To gulfs of darkness down," "And brought Thy trophy up at length" "The foiled usurper’s crown." } }
    }
    \left-column {
      \line { \bold "4." \column { "To Thee, dear Lord, O Christ of God," "We sing, we ever sing;" "Thou hast redeemed us with Thy blood" "From every evil thing." "God’s saving strength Thine arm upbore," "The arm that set us free;" "Glory, O Christ, for evermore" "Be to Thy God and Thee." } }
    }
  }
}
