\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E1341.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.75
  }
  system-system-spacing = #'((basic-distance . 12.44) (minimum-distance . 12.44) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Therefore the redeemed of the Lord shall return"
  subtitle = "Scriptures for Singing"
  opus = "1341"
}

global = {
  \key bes \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  r4 f'4 f'4 g'8.[ d'16] | f'4 g'8.[ d'16] f'4 g'8.[ d'16] | f'2 r8 d''8 d''8.[ c''16] | bes'8 bes'2~ bes'8 g'8.[ bes'16] \break | c''8 bes'2 bes'8 bes'8.[ c''16] | d''4 d''8.([ c''16)] bes'4. d''8 | c''4 c''4 bes'4 a'4 | bes'1 \break | r4 f'4 f'4 g'8.[ d'16] | f'4 g'8.[ d'16] f'4 g'8.[ d'16] | f'2 r8 d''8 d''8.[ c''16] | bes'8 bes'2~ bes'8 g'8.[ bes'16] \break | c''8 bes'2 bes'8 bes'8.[ c''16] | d''4 d''8.([ c''16)] bes'4. d''8 | c''4 c''4 bes'4 a'4 | bes'1 \break | r4 bes'4 bes'4 bes'4 | bes'1~ | bes'4 bes'4 a'4 g'4 | f'1 | r4 bes'4 bes'4 g'4~ | g'4 bes'4 bes'4 g'4~ | \defaultTimeSignature \time 2/4 g'8.[ d''16] c''8.[ bes'16] | \defaultTimeSignature \time 4/4 c''1 \break | r4 f'4 f'4 g'8.[ d'16] | f'4 g'8.[ d'16] f'4 g'8.[ d'16] | f'2 r8 d''8 d''8.[ c''16] | bes'8 bes'2~ bes'8 g'8.[ bes'16] \break | c''8 bes'2 bes'8 bes'8.[ c''16] | d''4 d''8.([ c''16)] bes'4. d''8 | c''4 c''4 bes'4 a'4 | bes'1~ | bes'4 r2. \bar "|."
}

harmonies = \chordmode {
  \global
  bes4 s4 f4:7 s8. s16 | bes4 s8. s16 bes4/f s8. s16 | bes2 bes8:7/d s8 s8. s16 | ees8 s2 ees8/bes s8. s16 | ees8 s4. ees8/g s8 f8./a s16 | bes4 s8. s16 g4.:m s8 | c4:m s4 f4:7 s4 | bes2 ees2/bes | bes4 s4 f4:7 s8. s16 | bes4 s8. s16 bes4/f s8. s16 | bes2 bes8:7/d s8 s8. s16 | ees8 s2 ees8/bes s8. s16 | ees8 s4. ees8/g s8 f8./a s16 | bes4 s8. s16 g4.:m s8 | c4:m s4 f4:7 s4 | bes2 ees2/bes | bes4 s4 bes4:7 s4 | ees4 ees2./bes | ees4 s4 ees4/g f4/a | bes2 bes2/f | bes4 s4 c4:7 s4 | c4:7/g s4 c4:7 s4 | \defaultTimeSignature \time 2/4 c8.:7/e s16 s8. s16 | \defaultTimeSignature \time 4/4 c2:m/ees c2:m/g | f4 s4 f4:7 s8. s16 | bes4 s8. s16 bes4/f s8. s16 | bes2 bes8:7/d s8 s8. s16 | ees8 s2 ees8/bes s8. s16 | ees8 s4. ees8/g s8 f8./a s16 | bes4 s8. s16 g4.:m s8 | c4:m s4 f4:7 s4 | bes2 ees2/bes | bes4 s2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "There" -- "fore" "the" "re" -- "deemed" "of" "the" "Lord" "shall" "re" -- "turn," "And" "come" "with" "sing" -- "ing" _ "un" -- "to" "Zi" -- "on;" "And" "ev" -- "er" -- "last" -- "ing" _ "joy" "shall" "be" "up" -- "on" "their" "head." "There" -- "fore" "the" "re" -- "deemed" "of" "the" "Lord" "shall" "re" -- "turn," "And" "come" "with" "sing" -- "ing" _ "un" -- "to" "Zi" -- "on;" "And" "ev" -- "er" -- "last" -- "ing" _ "joy" "shall" "be" "up" -- "on" "their" "head." "They" "shall" "ob" -- "tain" _ "glad" -- "ness" "and" "joy;" "And" "sor" -- "row" _ "and" "mourn" -- "ing" _ "shall" "flee" "a" -- "way." "There" -- "fore" "the" "re" -- "deemed" "of" "the" "Lord" "shall" "re" -- "turn," "And" "come" "with" "sing" -- "ing" _ "un" -- "to" "Zi" -- "on;" "And" "ev" -- "er" -- "last" -- "ing" _ "joy" "shall" "be" "up" -- "on" "their" "head." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

