\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E14.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.71
  }
  system-system-spacing = #'((basic-distance . 12.63) (minimum-distance . 12.63) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Immortal, invisible, God only wise"
  subtitle = "Worship of the Father—His Immortality"
  opus = "14"
}

global = {
  \key g \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  g'4 | e'4 c'4 a'4 | fis'4 d'4 g'8([ a'8)] | b'4 b'4 a'4 | g'2 g'4 \break | e'4 c'4 a'4 | fis'4 d'4 g'8([ a'8)] | b'4 b'4 a'4 | g'2 g'4 \break | b'4 b'4 d''4 | b'4 g'4 g'4 | b'4 b'4 d''4 | a'2 b'4 \break | g'4 e'4 a'4 | fis'4 d'4 g'8([ a'8)] | b'4 b'4 a'4 | g'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 | c4 s4 a4 | d4 s4 s8 s8 | g4/d s4 d4:7 | g2 s4 | c4 s4 a4 | d4 s4 e8:m s8 | c4 s4 d4:7 | g2 s4 | g4 s4 s4 | s4 s4 s4 | s4 s4 s4 | d2 e4:m | c4 s4 a4 | d4 s4 e8:m s8 | c4 s4 d4:7 | g2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Im" -- "mort" -- "al," "in" -- "vi" -- "si" -- "ble," _ "God" "on" -- "ly" "wise," "In" "light" "in" -- "ac" -- "cess" -- "i" -- "ble" _ "hid" "from" "our" "eyes," "Most" "bless" -- "ed," "most" "glor" -- "ious," "the" "An" -- "cient" "of" "Days," "Al" -- "might" -- "y," "vic" -- "tor" -- "ious," "Thy" _ "great" "name" "we" "praise."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Unresting, unhasting, and silent as light," "Nor wanting, nor wasting, Thou rulest in might;" "Thy justice like mountains high soaring above" "Thy clouds which are fountains of goodness and love." } }
      \vspace #0.88
      \line { \bold "3." \column { "To all life Thou givest, to both great and small;" "In all life Thou livest, the true life of all;" "We blossom and flourish as leaves on the tree," "And wither and perish, but nought changeth Thee." } }
      \vspace #0.88
      \line { \bold "4." \column { "Great Father of Glory, pure Father of Light" "Thine angels adore Thee, all veiling their sight;" "All laud we would render, O help us to see:" "’Tis only the splendor of light hideth Thee." } }
      \vspace #0.88
      \line { \bold "5." \column { "Immortal, invisible, God only wise," "In light inaccessible hid from our eyes," "Most blessed, most glorious, the Ancient of Days," "Almighty, victorious, Thy great name we praise." } }
    } \hspace #1.1 }
    \null
  }
}
