\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E144.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.69
  }
  system-system-spacing = #'((basic-distance . 12.93) (minimum-distance . 12.93) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Lord of glory, we adore Thee"
  subtitle = "Praise of the Lord—His Glory"
  opus = "144"
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  f'2 g'2 | a'4 f'4 bes'4 a'4 | a'2 g'2 | f'4 bes'4 a'4 g'4 | f'2 e'2 | f'1 \break | f'2 g'2 | a'4 f'4 bes'4 a'4 | a'2 g'2 | f'4 bes'4 a'4 g'4 | f'2 e'2 | f'1 \break | c''2 d''2 | c''2 a'2 | c''2 d''2 | c''1 | f'4 g'4 a'4 g'4 | f'2 e'2 | f'1 \bar "|."
}

harmonies = \chordmode {
  \global
  f2 c2/e | f4 s4 c4/e f4 | c2 s2 | d4:m s4 bes4 s4 | f2/c c2:7 | f1 | f2 c2/e | f4 s4 c4/e f4 | c2 s2 | d4:m s4 bes4 s4 | f2/c c2:7 | f1 | f2/a bes2 | f2/a f2 | f2/a bes2 | c1 | d4:m s4 f4/c s4 | bes2 c2:7 | f1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Lord" "of" "glo" -- "ry," "we" "a" -- "dore" "Thee!" "Christ" "of" "God," "as" -- "cend" -- "ed" "high!" "Heart" "and" "soul" "we" "bow" "be" -- "fore" "Thee," "Glo" -- "rious" "now" "be" -- "yond" "the" "sky:" "Thee" "we" "wor" -- "ship," "Thee" "we" "praise—" "Ex" -- "cel" -- "lent" "in" "all" "Thy" "ways."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Anointed King, with glory crowned," "Rightful Heir and Lord of all!" "Once rejected, scorned, disowned," "E’en by those Thou cam’st to call:" "Thee we honor, Thee adore—" "Glorious now and evermore." } }
      \vspace #0.88
      \line { \bold "3." \column { "Lord of life! to death once subject;" "Blesser, yet a curse once made;" "Of Thy Father’s heart the object," "Yet in depths of anguish laid;" "Thee we gaze on, Thee recall—" "Bearing here our sorrows all." } }
      \vspace #0.88
      \line { \bold "4." \column { "Royal robes shall soon invest Thee," "Royal splendors crown Thy brow;" "Christ of God, our souls confess Thee" "King and Sov’reign even now!" "Thee we rev’rence, Thee obey—" "Own Thee Lord and Christ alway." } }
    } \hspace #1.1 }
    \null
  }
}
