\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E201.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.62
  }
  system-system-spacing = #'((basic-distance . 13.73) (minimum-distance . 13.73) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "O Lord, Thou art our Paraclete"
  subtitle = "Praise of the Lord—His All-Inclusiveness"
  opus = "201"
}

global = {
  \key a \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  e'4 | e'4( fis'4) e'4 | e'4( fis'4) e'4 | cis''2 b'4 | a'2 a'4 | gis'4( fis'4) e'4 | b'2 dis'4 | e'2 e'4 \break | e'4( fis'4) gis'4 | a'2 e'4 | fis'4( b'4) a'4 | gis'2 e'4 | a'4( cis''4) b'4 | a'2 gis'4 | a'2.~ | a'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  a4 | s4 s4 s4 | s4 s4 s4 | e2 s4 | fis2:m s4 | e4/b s4 s4 | b2:7 s4 | e2 e4:7 | a4/cis d4 e4/b | a2/cis a4 | d4 b4:m b4/dis | e2 e4/d | a4/cis s4 d4 | a2/e e4:7 | a4 d2/a | a2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "O" "Lord," _ "Thou" "art" _ "our" "Pa" -- "ra" -- "clete," "Our" "Com" -- _ "fort" -- "er" "in" -- "deed," "Our" "Pa" -- _ "tron" "with" "our" "God" _ "a" -- "bove," "The" "Ad" -- _ "vo" -- "cate" "we" "need." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Thou art our Counsel of defense," "The Pleader of our case," "Our Interceder for all things," "Our Helper in all ways." } }
      \vspace #0.88
      \line { \bold "3." \column { "Lord, Thou dost manage all affairs" "For us in God’s delight," "Both in the heavens and in us" "With power in Thy right." } }
      \vspace #0.88
      \line { \bold "4." \column { "Thou intercedest all the time," "Lord Spirit, with Thy grace," "In heav’n to plead, in us to groan," "Entreating in our place." } }
      \vspace #0.88
      \line { \bold "5." \column { "Thou helpest as the living One," "And attest by God’s plan" "In resurrection pow’r of life," "Empow’ring our inner man." } }
      \vspace #0.88
      \line { \bold "6." \column { "Thou, as the Spirit giving life," "In weakness dost sustain;" "And in our spirit with Thy strength," "Our being dost maintain." } }
      \vspace #0.88
      \line { \bold "7." \column { "Thou servest ever with Thyself," "In mercy and in love," "That Thou may be our all in all," "And we Thy fulness prove." } }
    } \hspace #1.1 }
    \null
  }
}
