\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E232.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.62
  }
  system-system-spacing = #'((basic-distance . 14.19) (minimum-distance . 14.19) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "By Christ redeemed, in Christ restored"
  subtitle = "Praise of the Lord—Remembrance of Him"
  opus = "232"
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  fis'4 | fis'4 e'4 d'4 d'4 | g'4 g'4 fis'4 a'4 | a'4 g'4 fis'4 d'4 | fis'4 e'8([ d'8)] e'4 fis'4 \break | a'4 a'4 c''4 c''4 | b'4 b'4 a'4 gis'4 | a'2 g'2 | fis'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  d4 | s4 s4 s4 s4 | g4 s4 d4 s4 | d4/fis a4/e d4 s4 | e4:7 s8 s8 a4 s4 | d4 s4 d4:7/fis s4 | g4 s4 d4/fis e4/f | d2/fis a2:7 | d2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "By" "Christ" "re" -- "deemed," "in" "Christ" "re" -- "stored," "We" "keep" "the" "me" -- "mo" -- "ry" "a" -- _ "dored," "And" "show" "the" "death" "of" "our" "dear" "Lord" "Un" -- "til" "He" "come."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "His body broken in our stead" "Is seen in this memorial bread," "And so our feeble love is fed" "Until He come." } }
      \vspace #0.88
      \line { \bold "3." \column { "The drops of His dread agony," "His life-blood shed for us, we see;" "The wine shall tell the mystery" "Until He come." } }
      \vspace #0.88
      \line { \bold "4." \column { "And thus that dark betrayal-night" "With the last advent we unite," "By one blest chain of loving rite," "Until He come." } }
      \vspace #0.88
      \line { \bold "5." \column { "Until the trump of God be heard," "Until the ancient graves be stirred," "And with the great commanding word" "The Lord shall come." } }
      \vspace #0.88
      \line { \bold "6." \column { "O blessed hope! with this elate;" "Let not our heart be desolate," "But, strong in faith, in patience wait" "Until He come." } }
    } \hspace #1.1 }
    \null
  }
}
