\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E274.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.62
  }
  system-system-spacing = #'((basic-distance . 14.06) (minimum-distance . 14.06) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "O Lord, we seek the power we need"
  subtitle = "Fulness of the Spirit—The Baptism"
  opus = "274"
}

global = {
  \key aes \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  ees'4 f'8.[ ees'16] c'4 ees'4 | aes'4 bes'8.[ aes'16] f'2 | g'4 g'8.[ aes'16] bes'4 c''4 | aes'4 g'8.[ f'16] ees'2 \break | ees'4 f'8.[ ees'16] c'4 ees'4 | aes'4 bes'8.[ aes'16] f'2 | g'4 g'8.[ aes'16] bes'4 c''4 | aes'2. r4 \break | c''4 c''4^\markup { \box \bold "Chorus" } des''4. c''8 | c''8[ bes'8 bes'8 f'8] bes'2 | bes'4 bes'4 c''4. bes'8 | bes'8[ aes'8 aes'8 f'8] ees'2 \break | ees'4 f'8.[ ees'16] c'4 ees'4 | aes'4 bes'8.[ aes'16] f'2 | g'4 g'8.[ aes'16] bes'4 c''4 | aes'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  aes4 s8. s16 aes4/c s4 | des4 s8. s16 bes2:m | ees4 s8. s16 ees4:7 s4 | aes4 s8. s16 des2/aes | aes4 s8. s16 aes4/c s4 | des4 s8. s16 bes2:m | ees4 s8. s16 ees4:7 s4 | aes4 des2/aes aes4 | aes4 s4 des4/aes aes8 s8 | bes8:7 s8 s8 s8 s2 | ees4 s4 ees4.:7 s8 | aes8 s8 des8/aes s8 aes2 | aes4 s8. s16 aes4/c s4 | des4 s8. s16 bes2:m | ees4 s8. s16 ees4:7 s4 | aes4 des4/aes aes4 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "O" "Lord," "we" "seek" "the" "pow" -- "er" "we" "need;" "We" "are" "so" "weak" "in" "word" "and" "in" "deed" "And" "in" "Thy" "serv" -- "ice" "can" -- "not" "pro" -- "ceed," "Clothe" "us" "with" "pow’r" "we" "pray!" \set stanza = "(C)" "We" "are" "wait" -- "ing," "and" "to" "Thee" "we" "bow," "In" "Thy" "pre" -- "sence" "all" "our" "need" "a" -- "vow;" "Give" "us" "Thy" "pow" -- "er," "give" "ev" -- "en" "now," "Clothe" "us" "with" "pow’r" "to" -- "day."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Lord, come and visit us at this place," "Grant to Thy Church the gifts of Thy grace," "Fully with might our service embrace," "Clothe us with pow’r we pray!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Send us Thy power with its full sway," "As Thou didst send on Pentecost day;" "Answer our prayer and make no delay," "Clothe us with pow’r we pray!" } }
      \vspace #0.88
      \line { \bold "4." \column { "Here, as Thy Body, Thy pow’r we claim;" "Claiming by faith in Thy mighty Name," "Thy heav’nly show’r with Thy heav’nly flame;" "Clothe us with pow’r we pray!" } }
    } \hspace #1.1 }
    \null
  }
}
