\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E365.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.76
  }
  system-system-spacing = #'((basic-distance . 12.93) (minimum-distance . 12.93) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Jesus, Thy life is mine"
  subtitle = "Longings—For Christ as Life"
  opus = "365"
}

global = {
  \key g \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  d'4 g'4 g'4 | g'4( fis'4) fis'4 | g'2. | a'4 b'4 b'4 | b'4( a'4) g'4 | fis'2. \break | fis'4 g'4 a'4 | a'4( g'4) g'4 | c''2 b'4 | b'4( a'4) g'4 | g'4( fis'4) g'4 | e'2. | fis'2. | g'2.~ | g'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 s4 e4:m | g4/d s4 d4/c | g2./b | d4/fis g4 e4:m | a4:7 s4 s4 | d2. | d4/c s4 s4 | g4/b s4 s4 | c2/e g4/d | c4 s4 g4/b | a4:m s4 s4 | a2.:m/c | d2.:7 | g4 c2/g | g2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Je" -- "sus," "Thy" "life" _ "is" "mine," "Dwell" "ev" -- "er" -- "more" _ "in" "me;" "And" "let" "me" "see" _ "That" "noth" -- "ing" "can" _ "unt" -- "wine" _ "Thy" "life" "from" "mine." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Thy life in me be shown," "Lord, I would henceforth seek" "To think and speak" "Thy thoughts, Thy words alone," "No more my own." } }
      \vspace #0.88
      \line { \bold "3." \column { "Thy love, Thy joy, Thy peace," "Continuously impart" "Unto my heart," "Fresh springs that never cease," "But still increase." } }
      \vspace #0.88
      \line { \bold "4." \column { "The blest reality" "Of resurrection power," "Thy Church’s dower," "Life more abundantly," "Lord, give to me." } }
      \vspace #0.88
      \line { \bold "5." \column { "Thy fullest gift, O Lord," "Now at Thy word I claim," "Through Thy dear Name," "And touch the rapturous chord" "Of praise forth-poured." } }
      \vspace #0.88
      \line { \bold "6." \column { "Jesus, my life is Thine," "And evermore shall be" "Hidden in Thee," "For nothing can untwine" "Thy life from mine." } }
    } \hspace #1.1 }
    \null
  }
}
