\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E387.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.83
  }
  system-system-spacing = #'((basic-distance . 13.12) (minimum-distance . 13.12) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I am Thine, O Lord, I have heard Thy voice"
  subtitle = "Longings—For a Closer Walk with Christ"
  opus = "387"
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  b'8.[ c''16] | b'4 a'4 a'4 a'8.[ b'16] | a'4 g'4 g'4 g'8.[ fis'16] | e'4 e'4 e'4 g'8.([ e'16)] \break | d'2. b'8.[ c''16] | b'4 a'4 a'4 a'8.[ b'16] | a'4 g'4 g'4 a'8[ b'8] | c''4 c''4 fis'4 fis'4 \break | g'2 r4 b'8.[^\markup { \box \bold "Chorus" } c''16] | d''2 b'2 | a'8[ g'8 fis'8 e'8] d'4 g'8[ fis'8] | e'4 g'4 c''4 b'4 \break | a'2 r4 b'8.[ c''16] | d''4 d''8 r8 b'4 b'8 r8 | a'8[ g'8 fis'8 e'8] c''4^\fermata b'8.[ a'16] | g'4 g'4 b'4. a'8 | g'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g8. s16 | d4 s4 s4 s8. s16 | e4:m s4 g4/b s8. s16 | c4 s4 c4/e s8. s16 | g2. s8. s16 | d4/fis s4 d4 s8. s16 | e4:m s4 g4/b s8 s8 | a4:m s4 d4:7 s4 | g2 c4/g s8. s16 | g2 g2:7/b | c8 s8 s8 s8 g4/b s8 s8 | c4 g4/b a4:m g4 | d2 d4:7 s8. s16 | g4 s8 s8 g4:7/b s8 s8 | c8 s8 s8 s8 a4:m s8. s16 | g4/d s4 d4.:7 s8 | g4 c2/g g4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "I" "am" "Thine," "O" "Lord," "I" "have" "heard" "Thy" "voice," "And" "it" "told" "Thy" "love" "to" _ "me;" "But" "I" "long" "to" "rise" "in" "the" "arms" "of" "faith," "And" "be" "clos" -- "er" "drawn" "to" "Thee." \set stanza = "(C)" "Draw" "me" "near" -- "er," "near" -- "er," "bless" -- "ed" "Lord," "To" "the" "cross" "where" "Thou" "hast" "died;" "Draw" "me" "near" -- "er," "near" -- "er," "near" -- "er," "bless" -- "ed" "Lord," "To" "Thy" "pre" -- "cious," "bleed" -- "ing" "side."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Consecrate me now to Thy service, Lord," "By the pow’r of grace divine;" "Let my soul look up with a steadfast hope," "And my will be lost in Thine." } }
      \vspace #0.88
      \line { \bold "3." \column { "O the pure delight of a single hour" "That before Thy throne I spend," "When I kneel in prayer, and with Thee, my God," "I commune as friend with friend!" } }
      \vspace #0.88
      \line { \bold "4." \column { "There are depths of love that I yet may know" "Ere Thee face to face I see;" "There are heights of joy that I yet may reach" "Ere I rest in peace with Thee." } }
    } \hspace #1.1 }
    \null
  }
}
