\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E506.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.70
  }
  system-system-spacing = #'((basic-distance . 13.09) (minimum-distance . 13.09) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Jesus lives! thy terrors now"
  subtitle = "Experience of Christ—As Life"
  opus = "506"
}

global = {
  \key b \major
  \time 3/2
  \autoBeamOff
  \partial 2
}

melody = {
  \clef treble
  \global
  fis'4. fis'8 | b'2. fis'4 gis'4 fis'4 | gis'1 gis'4 fis'4 | \defaultTimeSignature \time 4/4 e'4 dis'4 cis'4 b4 \break | \defaultTimeSignature \time 3/2 dis'2 cis'2 dis'4 e'4 | fis'2. fis'4 gis'4 ais'4 | \defaultTimeSignature \time 4/4 b'2 b'4 cis''4 \break | dis''4. cis''8 b'4 gis'4 | fis'4 dis'4 cis'4 b4 | cis'1 | b1 \bar "|."
}

harmonies = \chordmode {
  \global
  fis4.:7 s8 | b2. s4 b4/dis s4 | e1 s4 s4 | \defaultTimeSignature \time 4/4 cis4:m s4 b4 s4 | \defaultTimeSignature \time 3/2 fis2/ais fis2 fis4:7/ais s4 | b2. s4 e4 fis4 | \defaultTimeSignature \time 4/4 b2 b4/dis fis4 | b4. s8 gis4:m s4 | b4/fis s4 gis4:m b4/fis | cis2:m/e fis2:7 | b1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Je" -- "sus" "lives!" "thy" "ter" -- "rors" "now" "Can," "O" "Death," "no" "more" "ap" -- "pall" "us;" "Je" -- "sus" "lives!" "by" "this" "we" "know" "Thou," "O" "Grave," "canst" "not" "en" -- "thrall" "us." "Hal" -- "le" -- "lu" -- "jah!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Jesus lives! henceforth is death" "But the gate of Life immortal;" "This shall calm our trembling breath," "When we pass its gloomy portal." "Hallelujah!" } }
      \vspace #0.88
      \line { \bold "3." \column { "Jesus lives! for us He died;" "Then alone to Jesus living," "Pure in heart may we abide," "Glory to our Savior giving." "Hallelujah!" } }
      \vspace #0.88
      \line { \bold "4." \column { "Jesus lives! our hearts know well" "Naught from us His love shall sever;" "Life, nor death, nor powers of hell" "Tear us from His keeping ever." "Hallelujah!" } }
      \vspace #0.88
      \line { \bold "5." \column { "Jesus lives! to Him the Throne" "Over all the world is given;" "We, in spirit with Him one," "Rest and reign with Him in heaven." "Hallelujah!" } }
    } \hspace #1.1 }
    \null
  }
}
