\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E53.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.82
  }
  system-system-spacing = #'((basic-distance . 13.12) (minimum-distance . 13.12) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Our God and Father, we respond anew"
  subtitle = "Worship of the Father—His Praise from Many Sons"
  opus = "53"
}

global = {
  \key aes \major
  \time 4/4
  \autoBeamOff
  \partial 4.
}

melody = {
  \clef treble
  \global
  ees'8[ c'8 ees'8] | c''4. c''8 bes'8[ aes'8 f'8 aes'8] | f'4( ees'4.) ees'8[ g'8 bes'8] \break | des''4. des''8 des''8[ d''8 ees''8 bes'8] | c''2 r8 ees'8[ c'8 ees'8] \break | c''4. c''8 bes'8[ aes'8 f'8 aes'8] | f'4( ees'4.) ees'8[ aes'8 c''8] \break | ees''8[ c''8 aes'8 bes'8] c''8([ aes'8)] bes'4 | aes'2~ aes'8 r4. \bar "|."
}

harmonies = \chordmode {
  \global
  aes8 s8 s8 | s4. s8 aes8/c s8 des8 s8 | aes4 s4. s8 s8 s8 | ees4./g s8 ees8 s8 s8 s8 | aes2 des8/aes s8 s8 s8 | aes4. s8 aes8/c s8 des8 s8 | aes4 s4 f8:m s8 s8 s8 | aes8/ees s8 f8:m s8 aes8/ees s8 ees4:7 | aes4 des4/aes aes8 s4. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Our" "God" "and" "Fa" -- "ther," "we" "res" -- "pond" "a" -- "new" _ "To" "love" "in" "Christ" "re" -- "vealed," "and" "praise" "Thy" "Name." "He" "did" "Thy" "will;" "and" "for" "the" "joy" "in" "view," _ "En" -- "dured" "the" "cross," "des" -- "pi" -- "sing" "all" _ "the" "shame." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "He, midst His brethren, strikes the note of praise;" "We hear His song, our hearts responsive swell;" "And on this day when He His voice doth raise," "In spirit we do join and praise Thee well." } }
      \vspace #0.88
      \line { \bold "3." \column { "Chosen in Him Thy well-beloved Son," "We have our part in joy before Thy face;" "Predestined, ere this world had yet begun," "For that blest world, where all bespeaks Thy grace." } }
      \vspace #0.88
      \line { \bold "4." \column { "Sons loved and loving, whom Thy Spirit fills," "Our endless portion Christ in us to be;" "Each with some trait of Him whose love us thrills," "For Thy delight and joy eternally." } }
    } \hspace #1.1 }
    \null
  }
}
