\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E539.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 13.46) (minimum-distance . 13.46) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.02) (minimum-distance . 15.02) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "O Lord, Thou art in me as life"
  subtitle = "Experience of Christ—As the Available One"
  opus = "539"
}

global = {
  \key c \major
  \time 3/4
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  g'8 | g'4 g'8 g'4 g'8 | g'8([ fis'8)] g'8[ a'8(] g'8)[ e'8] | d'4 e'8 g'4 f'8 \break | e'2~ e'8[ g'8] | g'4 g'8 g'4 g'8 | g'8([ fis'8)] g'8[ a'8(] g'8)[ a'8] | b'4 c''8 b'4 a'8 \break | g'2~ g'8[ g'8]^\markup { \box \bold "Chorus" } | c''4 c''8[ b'8(] a'8)[ g'8] | a'4. g'4 g'8 | a'4 c''8 g'4 e'8 \break | d'2~ d'8[ d'8] | e'4 e'8 g'4 g'8 | c''4 c''8[ d''8(] c''8)[ a'8] | g'4 g'8 a'4 b'8 | c''2~ c''8 r8 \bar "|."
}

harmonies = \chordmode {
  \global
  c8 | s4 s8 g4/b s8 | a8:m s8 s8 c8/g s8 s8 | f4 s8 g4:7 s8 | c2 g8:7 s8 | c4 s8 g4/b s8 | a8:m s8 s8 c8/g s8 s8 | g4/d s8 d4:7 s8 | g2 g8:7 s8 | c4 s8 s8 s8 s8 | f4. c4/e s8 | f4 s8 e4:m a8:m | d2:m7 g8:7 s8 | c4 s8 g4/d s8 | c4/e s8 f8 s8 s8 | c4/g s8 g4:7 s8 | c4 f4 c8 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "O" "Lord," "Thou" "art" "in" "me" _ "as" "life" _ "And" "ev" -- "ery" -- "thing" "to" "me!" _ "Sub" -- "jec" -- "tive" "and" "a" -- "vail" -- _ "a" -- "ble," _ "Thus" "I" "ex" -- "pe" -- "rience" "Thee." _ \set stanza = "(C)" "O" "Lord," "Thou" "art" _ "the" "Spir" -- "it!" "How" "dear" "and" "near" "to" "me!" _ "How" "I" "en" -- "joy" "Thy" "mar" -- "vel" -- "ous" _ "A" -- "vail" -- "a" -- "bil" -- "i" -- "ty!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "To all my needs both great and small" "Thou art the rich supply;" "So ready and sufficient too" "For me now to apply." } }
      \vspace #0.88
      \line { \bold "3." \column { "Thy sweet anointing with Thy might" "In weakness doth sustain;" "By Thy supply of energy" "My strength Thou dost maintain." } }
      \vspace #0.88
      \line { \bold "4." \column { "Thy law of life in heart and mind" "My conduct regulates;" "The wealth of Thy reality" "My being saturates." } }
      \vspace #0.88
      \line { \bold "5." \column { "O Thou art ever one with me," "Unrivaled unity!" "One spirit with me all the time" "For all eternity!" } }
    } \hspace #1.1 }
    \null
  }
}
