\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E589.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.58
  }
  system-system-spacing = #'((basic-distance . 13.27) (minimum-distance . 13.27) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "God in heaven hath a treasure"
  subtitle = "Experience of Christ—Expressing Him"
  opus = "589"
}

global = {
  \key ees \major
  \time 2/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  bes'4. c''8 | bes'4 g'4 | bes'4. aes'8 | aes'4 g'4 | f'4 c'4 | ees'4 g'4 | bes'4. aes'8 | g'2 \break | bes'4. c''8 | bes'4 g'4 | bes'4. aes'8 | aes'4 g'4 | f'4 c'4 | ees'4 d'4 | g'4. f'8 | ees'2 \break | ees'4. f'8 | f'4 ees'4 | ees'4 f'8([ g'8)] | f'4 ees'4 | f'4. f'8 | g'4 bes'4 | c''4 bes'8([ g'8)] | f'2^\fermata \break | bes'4. c''8 | bes'4 g'4 | bes'4. aes'8 | aes'4 g'4 | f'4 c'4 | ees'4 d'4 | g'4. f'8 | ees'2 \bar "|."
}

harmonies = \chordmode {
  \global
  ees4 aes8/ees s8 | ees4 s4 | bes4.:7/d bes8:7 | c4:m s4 | f4:m/aes s4 | f4:m s4 | bes4.:7 s8 | ees2 | ees4./g aes8 | ees4/g ees4 | bes4./d bes8 | c4:m s4 | f4:m/aes s4 | f4:m s4 | bes4.:7 s8 | ees2 | ees4.:7 s8 | aes4 s4 | ees4 s8 s8 | aes4 s4 | f4.:m s8 | ees4/g s4 | aes4 s8 s8 | bes2:7 | ees4 aes8/ees s8 | ees4 s4 | bes4.:7/d bes8:7 | c4:m s4 | f4:m/aes s4 | f4:m s4 | bes4.:7 s8 | ees2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "God" "in" "heav" -- "en" "hath" "a" "trea" -- "sure," "Rich" -- "es" "none" "may" "count" "or" "tell;" "Hath" "a" "deep" "e" -- "ter" -- "nal" "plea" -- "sure," "Christ" "the" "Son," "He" "lov" -- "eth" "well." "God" "hath" "here" "on" "earth" "a" _ "trea" -- "sure," "None" "but" "He" "its" "price" "may" _ "know—" "Deep," "un" -- "fath" -- "om" -- "a" -- "ble" "plea" -- "sure," "Christ" "re" -- "vealed" "in" "saints" "be" -- "low."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "God in tongues of fire descending," "Chosen vessels thus to fill" "With the treasure never ending," "Ever spent—unfailing still." "God’s own hand the vessel filling" "From the glory far above," "Longing hearts forever stilling" "With the riches of His love." } }
      \vspace #0.88
      \line { \bold "3." \column { "Thus though worn, and tried, and tempted," "Glorious calling, saint, is thine;" "Let the Lord but find thee emptied," "Living branch in Christ the Vine!" "Vessels of the world’s despising," "Vessels weak and poor and base," "Bearing wealth God’s heart is prizing," "Glory from Christ’s blessed face." } }
    }
    \left-column {
      \line { \bold "4." \column { "Oh to be but emptier, lowlier," "Mean, unnoticed—and unknown," "And to God a vessel holier," "Filled with Christ and Christ alone!" "Naught of earth to cloud the glory," "Naught of self the light to dim," "Telling forth His wondrous story," "Emptied to be filled with Him." } }
    }
  }
}
