\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E608.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.75
  }
  system-system-spacing = #'((basic-distance . 13.26) (minimum-distance . 13.26) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "What mystery, the Father, Son, and Spirit"
  subtitle = "Experience of God—By the Trinity"
  opus = "608"
}

global = {
  \key bes \major
  \time 4/4
  \autoBeamOff
  \partial 4.
}

melody = {
  \clef treble
  \global
  f'8[ f'8 f'8] | d'4. f'8 f'8[ f'8 g'8 g'8] | ees'4 g'4 r8 g'8[ g'8 g'8] | f'4. d'8 f'8[ f'8 ees'8 ees'8] \break | d'2 r8 f'8[ f'8 f'8] | d'4. f'8 f'8[ f'8 g'8 g'8] | ees'4 g'4 r8 g'8[ g'8 g'8] | f'4. d'8 f'8[ f'8 ees'8 ees'8] \break | d'2 r8 f'8[ f'8^\markup { \box \bold "Chorus" } bes'8] | d''4. c''8 bes'8[ a'8 bes'8 g'8] | f'2 r8 bes'8[ bes'8 a'8] | c'2 r8 ees'8[ g'8 f'8] \break | d'2 r8 f'8[ f'8 bes'8] | d''4. c''8 bes'8[ a'8 bes'8 g'8] | f'2 r8 bes'8[ a'8 bes'8] | c''2 r8 d''8[^\fermata ees''8^\fermata a'8]^\fermata | bes'2 r2 \bar "|."
}

harmonies = \chordmode {
  \global
  f8 s8 s8 | bes4. s8 s8 s8 s8 s8 | ees4 s4 c8:m s8 s8 s8 | bes4./f s8 f8:7 s8 s8 s8 | bes2 f8:7 s8 s8 s8 | bes4. s8 s8 s8 s8 s8 | ees4 s4 c8:m s8 s8 s8 | bes4./f s8 f8:7 s8 s8 s8 | bes2 f8:7 s8 s8 s8 | bes4. s8 ees8 s8 s8 s8 | d2:m7 g8:m7 s8 s8 s8 | c2:m7 f8:7 s8 s8 s8 | bes2 f8:7 s8 s8 s8 | bes4 bes8:7 s8 ees8 s8 s8 s8 | d2:m7 g8:m7 s8 s8 s8 | c2:m/ees s8 g8:7/d c8:m7 f8:7 | bes4 ees4 bes2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "What" "mys" -- "te" -- "ry," "the" "Fath" -- "er," "Son," "and" "Spir" -- "it," "In" "per" -- "son" "three," "in" "sub" -- "stance" "all" "are" "one." "How" "glo" -- "ri" -- "ous," "this" "God" "our" "be" -- "ing" "en" -- "ters" "To" "be" "our" "all," "thru" "Spir" -- "it" "in" "the" "Son!" \set stanza = "(C)" "The" "Tri" -- "une" "God" "has" "now" "be" -- "come" "our" "all!" "How" "won" -- "der" -- "ful!" "How" "glo" -- "ri" -- "ous!" "This" "Gift" "di" -- "vine" "we" "nev" -- "er" "can" "ex" -- "haust!" "How" "ex" -- "cel" -- "lent!" "How" "mar" -- "vel" -- "ous!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "How rich the source, the Father as the fountain," "And all this wealth He wants man to enjoy!" "O blessed fact, this vast exhaustless portion" "Is now for us forever to employ!" } }
      \vspace #0.88
      \line { \bold "3." \column { "How wonderful, the Son is God’s expression" "Come in the flesh to dwell with all mankind!" "Redemption’s work, how perfectly effective," "That sinners we with God might oneness find." } }
      \vspace #0.88
      \line { \bold "4." \column { "The Spirit is the Son’s transfiguration" "Come into us as life the full supply." "Amazing fact, our spirit with the Spirit" "Now mingles and in oneness joins thereby!" } }
      \vspace #0.88
      \line { \bold "5." \column { "How real it is that God is now the Spirit" "For us to touch, experience day by day!" "Astounding fact, with God we are one spirit," "And differ not in life in any way!" } }
    } \hspace #1.1 }
    \null
  }
}
