\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E644.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.76
  }
  system-system-spacing = #'((basic-distance . 13.47) (minimum-distance . 13.47) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.67) (minimum-distance . 14.67) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Looking unto Jesus"
  subtitle = "Encouragement—For Fellowship with the Lord"
  opus = "644"
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  b'4. b'8 b'4 a'4 | g'2 e'2 | c''4. b'8 a'4 g'4 | fis'1 | d''4 a'4 b'4 c''4 | b'2 g'2 | a'4. g'8 fis'4 e'4 | d'1 \break | d'4 d'4 e'4 fis'4 | a'2 g'2 | g'4 g'4 c''4 c''4 | b'1 | g'4 a'4 b'4 c''4 | d''2 d'2 | e'4 c''4 b'4 a'4 | g'1 \break | b'4.^\markup { \box \bold "Chorus" } b'8 b'4 a'4 | g'2 e'2 | c''4. b'8 a'4 g'4 | fis'1 \break | g'4 a'4 b'4 c''4 | d''2 d'2 | e'4 c''4 b'4 a'4 | g'1 \bar "|."
}

harmonies = \chordmode {
  \global
  g4. s8 b4 s4 | e2:m s2 | a4.:m s8 a4/cis s4 | d1 | s4 d4/c g4/b d4/a | g2 g2/b | d4./fis g8 d4/a a4 | d1 | g4/b g4 c4 a4:m | d2/fis g2 | c4 g4/b d4/a d4 | g1 | s4 d4/fis g4 c4/e | g2/b e4:m g4/d | c4 a4:m g4/d d4:7 | g4 c2/g g4 | g4. s8 b4 s4 | e2:m s2 | a4.:m s8 a4/cis s4 | d1 | g4 d4/fis g4 c4/e | g2/b e4:m g4/d | c4 a4:m g4/d d4:7 | g1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Look" -- "ing" "un" -- "to" "Je" -- "sus," "Nev" -- "er" "need" "we" "yield!" "O" -- "ver" "all" "the" "ar" -- "mor," "Faith" "the" "bat" -- "tle-" -- "shield!" "Stan" -- "dard" "of" "sal" -- "va" -- "tion," "In" "our" "hearts" "un" -- "furled," "Let" "its" "e" -- "le" -- "va" -- "tion" "O" -- "ver" -- "come" "the" "world." \set stanza = "(C)" "Look" -- "ing" "un" -- "to" "Je" -- "sus," "Nev" -- "er" "need" "we" "yield!" "O" -- "ver" "all" "the" "ar" -- "mor," "Faith" "the" "bat" -- "tle-" -- "shield!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Look away to Jesus," "Look away from all!" "Then we need not stumble," "Then we shall not fall." "From each snare that lureth," "Foe or phantom grim," "Safety this ensureth," "Look away to Him." } }
      \vspace #0.88
      \line { \bold "3." \column { "Looking into Jesus," "Wond’ringly we trace" "Heights of power and glory," "Depths of love and grace." "Vistas far unfolding" "Ever stretch before," "As we gaze, beholding," "Ever more and more." } }
    }
    \left-column {
      \line { \bold "4." \column { "Looking up to Jesus" "On the emerald throne," "Faith shall pierce the heavens," "Where our King is gone." "Lord, on Thee depending," "Now, continually," "Heart and mind ascending," "Let us dwell with Thee." } }
    }
  }
}
