\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E786.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.70
  }
  system-system-spacing = #'((basic-distance . 13.50) (minimum-distance . 13.50) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.98) (minimum-distance . 14.98) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Pray to labor with the Lord"
  subtitle = "Prayer—Laboring with the Lord"
  opus = "786"
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'4 g'4 b'4. a'8 | g'4 e'4 d'2 | g'4 g'4 c''4. b'8 | a'4 g'4 fis'2 \break | a'4 b'8([ a'8)] d''4. g'8 | fis'4 c''4 b'2 | g'4 g'4 b'4. a'8 | g'4 fis'4 g'2 \bar "|."
}

harmonies = \chordmode {
  \global
  g4 s4 s4. s8 | c4 s4 g2 | g4/b s4 a4.:m e8/b | a4:m a4:7/cis d2 | d4:7/c s8 s8 g4./b s8 | d4:7 s4 g2 | e4:m s4 g4./b a8:m/c | g4/d d4:7 g2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Pray" "to" "la" -- "bor" "with" "the" "Lord," "Pray" "to" "pave" "the" "way" "for" "Him;" "Pray" "to" _ "move" "Him" "and" "be" "moved" "From" "the" "cen" -- "ter" "to" "the" "rim."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Pray to labor with the Lord," "Be identified with Him" "In His purpose and His aim" "Till His blessing floodeth in." } }
      \vspace #0.88
      \line { \bold "3." \column { "Pray to labor with the Lord;" "Self-ambition and self-will" "We must ever cast away," "All His purpose to fulfill." } }
      \vspace #0.88
      \line { \bold "4." \column { "Pray to labor with the Lord;" "Let the Lord initiate" "All the plan and all the work;" "Then thru us He’ll operate." } }
      \vspace #0.88
      \line { \bold "5." \column { "Pray to labor with the Lord" "Till the wheel begins to move;" "Pray together with the Lord" "Till the Church His pow’r shall prove." } }
    } \hspace #1.1 }
    \null
  }
}
