\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E799.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.66
  }
  system-system-spacing = #'((basic-distance . 13.03) (minimum-distance . 13.03) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "All Scripture is the very breath of God"
  subtitle = "Study of the Word—The Function of the Word"
  opus = "799"
}

global = {
  \key a \major
  \time 2/2
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  e'2 cis'4 d'4 | e'2 a'2 | a'4 gis'4 fis'4 gis'4 | a'1 \break | fis'2 fis'4 fis'4 | e'2 e'4( gis'4) | b'4 a'4 gis'4 fis'4 | e'1 \break | e'2 cis'4 d'4 | e'2 a'2 | a'4 gis'4 fis'4 gis'4 | a'1 \break | fis'2 fis'4 fis'4 | e'2 a'4( cis''4) | cis''4 b'4 a'4 gis'4 | a'1 \bar "|."
}

harmonies = \chordmode {
  \global
  a2 s4 e4:7/b | a2/cis a2 | a4/e s4 e4:7 s4 | a1 | d2 s4 s4 | a2/cis a4 s4 | e4/b s4 b4:7 s4 | e2 e2:7 | a2 s4 e4:7/b | a2/cis a2 | a4/e s4 e4:7 s4 | fis1:m | d2 s4 s4 | a2/cis d4 s4 | a4/e s4 e4:7 s4 | a1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "All" "Scrip" -- "ture" "is" "the" "ve" -- "ry" "breath" "of" "God," "And" "by" "His" "Spir" -- "it" _ "in" -- "to" "words" "was" "breathed;" "By" "god" -- "ly" "men" "the" "words" "were" "writ" -- "ten" "down," "With" "all" "God’s" "ful" -- "ness" _ "un" -- "to" "man" "be" -- "queathed."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "It is the breath of God as light to man," "With rays divine man to illuminate;" "It shines in darkness and to man reveals" "What is his truest need and actual state." } }
      \vspace #0.88
      \line { \bold "3." \column { "It is the breath of God as life to man," "Nature divine to man it doth impart;" "The dead it quickens and regenerates," "Transforms the soul-life and renews the heart." } }
      \vspace #0.88
      \line { \bold "4." \column { "It is the breath of God as wisdom too," "Knowledge divine to man it has to teach;" "Th’ eternal purpose of the Lord it shows," "And leadeth man God’s final goal to reach." } }
      \vspace #0.88
      \line { \bold "5." \column { "It is the breath of God as strength to man," "Power divine to man it doth transmit," "Strength’ning the weak, empowering the faint," "Enabling man God’s purpose full to fit." } }
      \vspace #0.88
      \line { \bold "6." \column { "It is the breath of God for us to breathe," "That as our portion God we may enjoy;" "Receiving it by spirits exercised," "Our need is met, His wealth we may employ." } }
    } \hspace #1.1 }
    \null
  }
}
