\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E876.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.75
  }
  system-system-spacing = #'((basic-distance . 12.48) (minimum-distance . 12.48) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "When war is hot and fierce"
  subtitle = "Spiritual Warfare—By Praising"
  opus = "876"
}

global = {
  \key ees \major
  \time 2/2
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  r2 bes'2 | bes'4 g'4 g'4 ees'4 | f'1 | bes'2 c''4 a'4 | bes'2 bes'2 \break | bes'4 g'4 aes'4 bes'4 | c''1 | f'2 g'4 f'4 | ees'2 r2 \bar "|."
}

harmonies = \chordmode {
  \global
  ees2 bes2:7 | ees4 s4 s4 s4 | bes1 | ees2/g f4:7 s4 | bes2:7 s2 | ees4 s4 s4 s4 | aes1 | bes2:7 s4 s4 | ees4 aes4/ees ees2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "When" "war" "is" "hot" "and" "fierce," "And" "Sa" -- "tan" "strong," "Then" "firm" -- "ly" "trust" "God’s" "Word" "And" "sing" "faith’s" "song."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "You need to shout but once," "And you will win;" "Oh, do not shut your mouth" "And lose therein." } }
      \vspace #0.88
      \line { \bold "3." \column { "If pressed your spirit is" "And powerless," "Pray thru the precious blood," "Victorious." } }
      \vspace #0.88
      \line { \bold "4." \column { "The foe though fierce, you can" "Still fight with him;" "If you will keep your stand," "You soon will win." } }
      \vspace #0.88
      \line { \bold "5." \column { "Therefore you must declare" "Christ’s victory;" "The situation dark" "Soon changed will be." } }
    } \hspace #1.1 }
    \null
  }
}
