\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E906.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.72
  }
  system-system-spacing = #'((basic-distance . 13.41) (minimum-distance . 13.41) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "How much can we do for our Savior"
  subtitle = "Service—By the Lord Within"
  opus = "906"
}

global = {
  \key f \major
  \time 6/8
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  c'8 | a'8[ bes'8 a'8] g'8[ d'8 e'8] | g'8 f'4~ f'4 c'8 | d'8[ d'8 e'8] g'8[ f'8 d'8] \break | c'4.~ c'4 c'8 | d'8.[ e'16 f'8] g'8[ f'8 d'8] | c'8 a'4~ a'4 f'8 | g'8.[ g'16 a'8] bes'8[ a'8 g'8] | a'8 c''4~ c''4 d''8 | c''8[ a'8 f'8] bes'8[ a'8 g'8] | f'4.~ f'4 r8 \bar "|."
}

harmonies = \chordmode {
  \global
  f8 | s8 s8 s8 c8:7 s8 s8 | f8 s4 f4/a s8 | bes8 s8 s8 bes8/d s8 s8 | f4. s4 s8 | bes8. s16 s8 s8 s8 s8 | f8/a s4 f4 s8 | c8. s16 s8 c8:7/e s8 s8 | f8 s4 f4/a bes8 | f8/c s8 s8 c8:7 s8 s8 | f4. s4 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "How" "much" "can" "we" "do" "for" "our" "Sav" -- "ior?" _ "How" "much" "for" "our" "dear" "fel" -- "low" _ "man?" "The" "way" "to" "do" "more" "than" "we’re" "a" -- "ble" _ "Is" "Je" -- "sus" "with" "in" "to" "en" -- "a" -- "ble;" _ "Thus" "we" "can" "do" "more" "than" "we" "can." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "How much can we be for our Savior" "In life with its brief, fleeting span?" "If Jesus within us is dwelling" "Our life and our actions infilling," "We all can do more than we can." } }
      \vspace #0.88
      \line { \bold "3." \column { "How much can we bear for our Savior?" "How much for our dear fellow man?" "If in us His love is constraining," "If ’neath us His arms are sustaining," "We all can do more than we can." } }
      \vspace #0.88
      \line { \bold "4." \column { "How much can we give for our Savior?" "To succor our dear fellow man?" "If from us His love is o’erflowing," "Our life will be ever outgoing;" "We’ll always do more than we can." } }
    } \hspace #1.1 }
    \null
  }
}
