\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E949.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.36\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 14.66) (minimum-distance . 14.66) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Christ is the hope of glory, my very life is He"
  subtitle = "Hope of Glory—Christ as the Glorification"
  opus = "949"
}

global = {
  \key aes \major
  \time 6/8
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  ees'8 | ees'4 f'8 f'4 aes'8 | aes'4. f'4 c'8 | ees'4 ees'8 f'4 f'8 | c'4.~ c'4 ees'8 | c''4 c''8 c''4 bes'8 | aes'4. f'4 g'8 | aes'4 aes'8 bes'4 c''8 \break | bes'4.~ bes'4 ees'8 | ees'4 f'8 f'4 aes'8 | aes'4. f'4 c'8 | ees'4 ees'8 f'4 f'8 | c'4.~ c'4 c'8 | bes4 c'8 d'4 ees'8 | f'8 bes'4~ bes'4 aes'8 | g'4. f'4. \break | ees'4.~ ees'4 ees'8 | c''4.~^\markup { \box \bold "Chorus" } c''4 ees'8 | c''4.~ c''4 bes'8 | aes'4 aes'8 bes'8[ aes'8 f'8] | ees'4.~ ees'4 ees'8 | ees'4 des'8 des'4 f'8 | f'4 ees'8 ees'4 aes'8 | aes'4 aes'8 f'8([ g'8) aes'8] \break | bes'4.~ bes'4 ees'8 | c''4.~ c''4 ees'8 | c''4.~ c''4 bes'8 | aes'4 aes'8 bes'4 b'8 \break | c''4.~ c''4 c''8 | c''4 c''8 des''4 c''8 | c''4 bes'8 f'4^\fermata aes'8 | ees''4^\fermata c''8 bes'4 aes'8 | aes'4.~ aes'4 r8 \bar "|."
}

harmonies = \chordmode {
  \global
  aes8 | s4 s8 des4/aes s8 | aes4. aes4/ees s8 | aes4 s8 des4/aes s8 | aes4. s4 s8 | s4 s8 c4/g s8 | f4.:m aes4/ees s8 | bes4/d s8 bes4 s8 | bes4.:m/des ees4:7 s8 | aes4 s8 des4/aes s8 | aes4. aes4/ees s8 | aes4 s8 des4/aes s8 | aes4. s4 s8 | bes4 s8 bes4/f s8 | bes8 s4 s4 s8 | bes4.:7 s4. | ees4. s4 s8 | aes4. aes4/ees s8 | aes4. aes4:7/c s8 | des4 s8 s8 s8 s8 | aes4. s4 s8 | ees4/g s8 ees4 s8 | aes4 s8 f4:m s8 | bes4 s8 s8 s8 s8 | ees4. ees4:7 s8 | aes4. aes4/ees s8 | aes4. aes4:7/c s8 | des4 s8 bes4:m s8 | c4. s4 s8 | f4 s8 f4:7 s8 | bes4 s8 s4 s8 | aes4/ees s8 ees4:7 s8 | aes4. s4 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Christ" "is" "the" "hope" "of" "glo" -- "ry," "my" "ve" -- "ry" "life" "is" "He," _ "He" "has" "re" -- "gen" -- "e" -- "rat" -- "ed" "and" "sa" -- "tur" -- "at" -- "ed" "me;" _ "He" "comes" "to" "change" "my" "bo" -- "dy" "by" "His" "sub" -- "du" -- "ing" _ "might" "Like" "to" "His" "glo" -- "rious" "bo" -- "dy" _ "in" "glo" -- "ry" "bright!" _ \set stanza = "(C)" "He" _ "comes," "He" _ "comes," "Christ" "comes" "to" "glo" -- "ri" -- "fy" "me!" _ "My" "bo" -- "dy" "He’ll" "trans" -- "fi" -- "gure," "like" "His" "own" "it" _ "then" "will" "be." _ "He" "comes," _ "He" "comes," _ "re" -- "demp" -- "tion" "to" "ap" -- "ply!" _ "As" "Hope" "of" "glo" -- "ry" "He" "will" "come," "His" "saints" "to" "glo" -- "ri" -- "fy." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Christ is the hope of glory, He is God’s mystery;" "He shares with me God’s fulness and brings God into me." "He comes to make me blended with God in every way," "That I may share His glory with Him for aye." } }
      \vspace #0.88
      \line { \bold "3." \column { "Christ is the hope of glory, redemption full is He:" "Redemption to my body, from death to set it free," "He comes to make my body a glorious one to be" "And swallow death forever in victory." } }
    }
    \left-column {
      \line { \bold "4." \column { "Christ is the hope of glory, He is my history:" "His life is my experience, for He is one with me;" "He comes to bring me into His glorious liberty," "That one with Him completely I’ll ever be." } }
    }
  }
}
