\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E97.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.67
  }
  system-system-spacing = #'((basic-distance . 13.06) (minimum-distance . 13.06) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.99) (minimum-distance . 14.99) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Thy sorrows, Savior, we retrace"
  subtitle = "Praise of the Lord—His Suffering"
  opus = "97"
}

global = {
  \key bes \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  d'4 f'8.[ g'16] f'4 bes'8([ a'8)] | g'4 bes'4 f'2 | f'4 g'8.[ d'16] ees'4. c'8 | f'4 ees'4 d'2 \break | f'4 bes'8.[ a'16] c''4. bes'8 | d''4 bes'4 g'2 | ees''4 g'8.[ fis'16] f'4. d''8 | d''4. c''8 bes'2 \bar "|."
}

harmonies = \chordmode {
  \global
  bes4 s8. s16 s4 s8 s8 | ees4 s4 bes2 | g4:7 s8. s16 c4.:m s8 | f4 s4 bes2 | bes4 s8. s16 s4. s8 | s4 s4 ees2 | c4:m s8. s16 bes4./f s8 | f4.:7 s8 bes2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Thy" "sor" -- "rows," "Sav" -- "ior," _ "we" "re" -- "trace," "And" "tears" "of" "praise" "Thy" "griefs" "com" -- "pel." "What" "love" "and" "grace" "il" -- "lume" "Thy" "face" "As" "Je" -- "sus," "as" "Im" -- "man" -- "u" -- "el!"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Amid Thy loneliness below," "What scorn and outrage Thee befell:" "Deep shame and woe, rude blow on blow," "Endured for us, Immanuel!" } }
      \vspace #0.88
      \line { \bold "3." \column { "But oh, what grief, what agony," "When wrathful judgment’s awful spell" "Burst over Thee on Calv’ry’s tree," "God’s Lamb for us, Immanuel!" } }
      \vspace #0.88
      \line { \bold "4." \column { "Arisen radiant from the dead," "Thy sorrow’s scars forever tell," "Creation’s Head is He who bled—" "Still Jesus, still Immanuel!" } }
      \vspace #0.88
      \line { \bold "5." \column { "E’en now from saints, in concord sweet," "Celestial strains of worship well;" "For, O, ’tis meet glad songs should greet" "Thy heart of love, Immanuel!" } }
      \vspace #0.88
      \line { \bold "6." \column { "But when Thy glorious face we see," "How shall the bursting paean swell!" "Our souls shall be outpoured for Thee—" "Outpoured for Thee, Immanuel!" } }
    } \hspace #1.1 }
    \null
  }
}
