\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/E997.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.90\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.67
  }
  system-system-spacing = #'((basic-distance . 14.46) (minimum-distance . 14.46) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "I hear the Savior say"
  subtitle = "Gospel—Redemption"
  opus = "997"
}

global = {
  \key d \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  d'8([ fis'8)] | a'4. b'8 a'8[ fis'8] | d'2 d'4 | e'4. e'8 d'8[ e'8] \break | fis'2 d'8[ fis'8] | a'4. b'8 a'8[ fis'8] | d'2 d'8[ e'8] | fis'4. g'8 fis'8[ e'8] | d'2. \break | a'4.^\markup { \box \bold "Chorus" } b'8 a'8[ fis'8] | d''2 r4 | a'4. b'8 a'8[ fis'8] | e'2 r4 \break | a'4. b'8 a'8[ fis'8] | d''8[ cis''8] b'4^\fermata d''4 | fis'4. g'8 fis'8[ e'8] | d'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g8 s8 | d4. s8 g8/d s8 | d2 d4/fis | e4.:m/g s8 a8:7 s8 | d2 g8/d s8 | d4. s8 a8/cis s8 | b2:m g8 s8 | d4./a s8 a8:7 s8 | d2. | d4. s8 a8:7/e s8 | d2/fis g4 | d4./a s8 b8:7 s8 | e2:m a4:7 | d4. s8 a8:7/e s8 | d8/fis a8 g4 e4:7/gis | d4./a s8 a8:7 s8 | g4/d d4 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "I" _ "hear" "the" "Sav" -- "ior" "say," "“Thy" "strength" "in" -- "deed" "is" "small," "Child" "of" "weak" -- "ness," "watch" "and" "pray," "Find" "in" "Me" "thine" "all" "in" "all.”" \set stanza = "(C)" "Je" -- "sus" "paid" "it" "all," "All" "to" "Him" "I" "owe;" "Sin" "had" "left" "a" "crim" -- "son" "stain," "He" "washed" "it" "white" "as" "snow."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Lord, now indeed I find" "Thy pow’r, and Thine alone," "Can change the leper’s spots," "And melt the heart of stone." } }
      \vspace #0.88
      \line { \bold "3." \column { "For nothing good have I" "Whereby Thy grace to claim—" "I’ll wash my garments white" "In the blood of Calv’ry’s Lamb." } }
      \vspace #0.88
      \line { \bold "4." \column { "And when, before the throne," "I stand in Him complete," "“Jesus died my soul to save," "My lips shall still repeat." } }
    } \hspace #1.1 }
    \null
  }
}
