\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS1059.svg

#(set-global-staff-size 14.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.61\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.21
  }
  system-system-spacing = #'((basic-distance . 12.82) (minimum-distance . 12.82) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Lord Jesus, In Your Presence"
  subtitle = "Longings — For Living in the Lord’s Presence"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  a'4. a'8 a'8[ g'8 f'8 e'8] | f'4. f'8 f'8[ e'8 d'8 c'8] | e'4. e'8 e'8[ d'8 c'8 bes8] | c'2. r8 c'8 \break | bes4. c'8 d'8[ e'8 f'8 g'8] | c'4. e'8 f'2 | f'4. f'8 f'8[ g'8 a'8 bes'8] | g'1 \break | a'4. a'8 a'8[ g'8 f'8 e'8] | f'4. f'8 f'8[ e'8 d'8 c'8] | e'4. e'8 e'8[ d'8 c'8 bes8] | c'2. r8 c'8 \break | bes4. c'8 d'8[ e'8 f'8 g'8] | c'4.( e'8) f'2 | f'4. f'8 f'4 e'4 | f'2. r4 \break | g'8[ a'8 bes'8 a'8] g'8[ f'8 e'8 g'8] | f'8[ e'8 f'8 e'8] c'2 | d'8[ e'8 f'8 g'8] g'8[ f'8 f'8 c'8] | d'8[ e'8 f'8 a'8] g'4. a'16[ bes'16] \break | c''8[ a'8 f'8 a'8] c''8[ a'8 f'8 a'8] | bes'8[ a'8 bes'8 c''8] d''2^\fermata | c''8[ a'8 f'8 a'8] bes'8[ g'8 f'8 e'8] | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  f4. s8 s8 s8 s8 s8 | d4.:m s8 s8 s8 s8 s8 | c4. s8 s8 s8 s8 s8 | a2.:m s8 s8 | bes4. s8 s8 s8 s8 s8 | a4.:m s8 d2:m | bes4. s8 g8:m/bes s8 s8 s8 | c2:sus4 c2 | f4. s8 s8 s8 s8 s8 | d4.:m s8 s8 s8 s8 s8 | c4. s8 s8 s8 s8 s8 | a2.:m s8 s8 | bes4. s8 s8 s8 s8 s8 | a4.:m s8 d2:m | bes4. s8 c4:7 s4 | f2. s4 | c8:7/e s8 s8 s8 a8:7/cis s8 s8 s8 | d8:m s8 s8 s8 f2/a | bes8 s8 s8 s8 a8:m s8 d8:m s8 | g8:7 s8 s8 s8 c4.:7 s16 s16 | f8 s8 s8 s8 f8:7/a s8 s8 s8 | bes8 s8 s8 s8 g2/b | f8/c s8 s8 s8 c8:7 s8 s8 s8 | f2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Lord," "how" "sweet" "when" "touch" -- "ing" "You!" "Your" "great" "love" "draws" "me" "to" "Come" "forth" "to" "seek" "for" "You." "In" "Your" "dear" "pres" -- "ence," "no" "more" "wea" -- "ri" -- "ness;" "You" "bear" "all" "my" "bur" -- "dens," "too." "Lord," "how" "joy" -- "ful," "touch" -- "ing" "You!" "Your" "love" "draws" "me" "a" -- "new" "To" "tru" -- "ly" "rest" "in" "You." "In" "Your" "bright" "pres" -- "ence," "no" "more" "dark" -- _ "ness;" "Your" "light" "guides" "me" "through." "O" "Lord" "Je" -- "sus," "Ho" -- "ly" "Spir" -- "it" "dwell" -- "ing" "now" "in" "us," "In" "Your" "pres" -- "ence" "min" -- "gled" "in" -- "to" "one" -- "ness" "now" "are" "we;" "O" -- "ver" -- "flow" -- "ing" "ev" -- "ery" "day" "with" "joy" "that" "springs" "from" "deep" "in" "us," "Now" "we" "all" "re" -- "joice" "a" -- "bun" -- "dant" -- "ly."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

