\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS10067.svg

#(set-global-staff-size 15.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.39\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.07
  }
  system-system-spacing = #'((basic-distance . 13.90) (minimum-distance . 13.90) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.98) (minimum-distance . 14.98) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "The love of Christ is now constraining me"
  subtitle = "Consecration—Constrained by the Lord’s Love"
  opus = ""
}

global = {
  \key d \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  r8 fis'8[^\markup { \box \bold "Verses 1-2" } fis'8 g'8] a'4. d'8 | e'8[ fis'8 e'8 fis'8] e'2 | r8 d'8[ d'8 d'8] d'4. d'8 | e'8[ fis'8 e'8 fis'8] e'2 \break | r8 fis'8[ fis'8 g'8] a'4. d'8 | e'8[ fis'8 e'8 fis'8] e'4 fis'8([ e'8)] | d'4 d'4 d'4. d'8 | e'8[ fis'8 e'8 fis'8] e'2 \break | r8 b'8[^\markup { \box \bold "Chorus" } b'8 b'8] b'4 b'8[ b'8] | cis''8[ ais'8~] ais'2 b'8[ cis''8] | d''4. d''8 d''4. d''8 | d''8[ b'8~] b'2 b'8[ b'8] | a'4.( g'8) fis'2 | r4 e'8[ fis'8] e'8([ d'8) cis'8 e'8] | d'1~ | d'1 \break | r4 d''4^\markup { \box \bold "Verses 3-4" } cis''4 a'4 | b'2( a'4.) g'8 | fis'8[ fis'8 fis'8 e'8] d'4. d'8 | g'8[ a'8 g'8 fis'8] e'2 \break | r4 d''4 cis''4 a'4 | b'2( a'4.) g'8 | fis'8[ fis'8 fis'8 e'8] d'4. d'8 | g'8[ a'8 g'8 fis'8] e'2 \break | r8 b'8[^\markup { \box \bold "Chorus" } b'8 b'8] b'4 b'8[ b'8] | cis''8[ ais'8~] ais'2 b'8[ cis''8] | d''4. d''8 d''4. d''8 | d''8[ b'8~] b'2 b'8[ b'8] | a'4.( g'8) fis'2 | r4 e'8[ fis'8] e'8([ d'8) cis'8 e'8] | d'1~ | d'1 \bar "|."
}

harmonies = \chordmode {
  \global
  d8 s8 s8 s8 b4.:m s8 | e8:m/g s8 s8 s8 a2 | d8 s8 s8 s8 b4.:m s8 | e8:m/g s8 s8 s8 a2 | d8 s8 s8 s8 b4.:m s8 | e8:m/g s8 s8 s8 a4 s8 s8 | b4:m s4 d4./a s8 | e8:m/g s8 s8 s8 a2 | b8:m s8 s8 s8 s4 s8 s8 | fis8 s8 s2 s8 s8 | b4.:m s8 d4./a s8 | g8 s8 s2 s8 s8 | d4. s8 b2:m | e4:m s8 s8 a8:7 s8 s8 s8 | d2 b2:m | g2 a2:7 | d4 s4 b4:m s4 | g2 a4. s8 | d8 s8 s8 s8 b4.:m s8 | g8 s8 s8 s8 a2 | d4 s4 b4:m s4 | g2 a4. s8 | d8 s8 s8 s8 b4.:m s8 | g8 s8 s8 s8 a2 | b8:m s8 s8 s8 s4 s8 s8 | fis8 s8 s2 s8 s8 | b4.:m s8 d4./a s8 | g8 s8 s2 s8 s8 | d4. s8 b2:m | e4:m s8 s8 a8:7 s8 s8 s8 | d2 b2:m | g2 a2:7 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "The" "love" "of" "Christ" "is" "now" "con" -- "strain" -- "ing" "me" "That" "I" "would" "love" "and" "love" "Him" "ut" -- "ter" -- "ly." "His" "might" -- "y" "love" "has" "touched" "me" "deep" "with" -- "in" "To" _ "con" -- "se" -- "crate" "my" "life" "and" "all" "to" "Him." \set stanza = "(C)" "This" "charm" -- "ing" "One" "so" "ex" -- "cel" -- _ "ling;" "To" "His" "touch" "I’m" "now" "res" -- "pond" -- _ "ing;" "To" "sur" -- "ren" -- _ "der," "to" "sur" -- _ "ren" -- "der" "to" "Him." _ \set stanza = "3." "The" "love" "of" "Christ" _ "Is" "now" "con" -- "strain" -- "ing" "me" "to" "love" "Him" "ut" -- "ter" -- "ly." "His" "might" -- "y" "love" _ "Has" "touched" "me" "deep" "with" -- "in" "to" "con" -- "se" -- "crate" "to" "Him." \set stanza = "(C)" "This" "charm" -- "ing" "One" "so" "ex" -- "cel" -- _ "ling;" "To" "His" "touch" "I’m" "now" "res" -- "pond" -- _ "ing;" "To" "sur" -- "ren" -- _ "der," "to" "sur" -- _ "ren" -- "der" "to" "Him." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "This tide of love has flowed to me from Him;" "Unchanging love that keeps on rushing in." "Now I’m for Him beyond my own control;" "He is now my love and my only goal." \translate #'(3.23 . -1.50) "His dying love so compelling," \translate #'(3.23 . -1.50) "And this tide has made me willing" \translate #'(3.23 . -1.50) "To love Him, I can’t help but love Him." } }
      \vspace #0.88
      \line { \bold "3." \column { "The love of Christ" "Is now constraining me to love Him utterly." "His mighty love" "Has touched me deep within to consecrate to Him." \translate #'(3.23 . -1.50) "This charming One so excelling;" \translate #'(3.23 . -1.50) "To His touch I’m now responding;" \translate #'(3.23 . -1.50) "To surrender, to surrender to Him." } }
    }
    \left-column {
      \line { \bold "4." \column { "This tide of love" "Has flowed to me from Him that keeps on rushing in." "Now I’m for Him" "Beyond my own control; He’s now my final goal." \translate #'(3.24 . -1.50) "His dying love so compelling," \translate #'(3.24 . -1.50) "And this tide has made me willing" \translate #'(3.24 . -1.50) "To love Him, I can’t help but love Him." } }
    }
  }
}
