\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS1091.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.63\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.24
  }
  system-system-spacing = #'((basic-distance . 12.33) (minimum-distance . 12.33) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "His Divine Power (2 Peter 1:3)"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key ees \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  bes'4. bes'8 bes'2 | f'4 bes'4~ bes'4 bes4 | c'4 aes'4~ aes'4 aes'4 | g'2. r4 | g'4 g'4 g'4 aes'4 \break | bes'2. bes4 | c'4 c'4 aes'4 g'4 | f'2. r4 | c''4. c''8 c''2 | bes'4 g'4~ g'4 g'4 \break | aes'4( g'4) f'4 ees'4 | c'2 d'2 | ees'4. ees'8 ees'2 | ees'4 ees'4~ ees'4 f'4 | f'4 ees'2. \break | r2 bes'4 bes'4 | c''1 | bes'4 g'4~ g'4 g'4 | f'2 g'2~ \break | g'2 bes'4 bes'4 | c''1 | bes'4 g'4~ g'4 g'4 | g'2.( aes'8[ g'8)] | f'1 \break | bes'4. bes'8 bes'2 | f'4 bes'4~ bes'4 bes4 | c'4 aes'4~ aes'4 aes'4 | g'2. r4 | g'4 g'4 g'4 aes'4 \break | bes'2. bes4 | c'4 c'4 aes'4 g'4 | f'2. r4 | c''4. c''8 c''2 | bes'4 g'4~ g'4 g'4 \break | aes'4 g'4 f'4( ees'4) | c'2 d'2 | ees'4. ees'8 ees'2 | ees'4 ees'4~ ees'4 f'4 | f'4 ees'2. \bar "|."
}

harmonies = \chordmode {
  \global
  ees4. s8 s2 | bes4 s4 s4 s4 | aes4 s4 s4 s4 | ees2. s4 | s4 s4 ees4/d s4 | c2:m c4:m/bes s4 | f4:m s4 s4 s4 | bes2. s4 | aes4. s8 s2 | ees4 s4 s4 s4 | aes4 s4 g4:m s4 | f2:m bes2 | ees4. s8 s2 | aes4 s4 s4 s4 | ees4 s2. | ees2 s4 s4 | aes1 | ees4 s4 s4 s4 | bes2 ees2 | ees2 s4 s4 | aes1 | ees4 s4 s4 s4 | f2.:m s8 s8 | bes1 | ees4. s8 s2 | bes4 s4 s4 s4 | aes4 s4 s4 s4 | ees2. s4 | s4 s4 ees4/d s4 | c2:m c4:m/bes s4 | f4:m s4 s4 s4 | bes2. s4 | aes4. s8 s2 | ees4 s4 s4 s4 | aes4 s4 g4:m s4 | f2:m bes2 | ees4. s8 s2 | aes4 s4 s4 s4 | ees4 s2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "His" "di" -- "vine" "pow" -- "er" _ "has" "giv" -- "en" _ "to" "us" "All" "things" "that" "re" -- "late" "To" "life" "and" "god" -- "li" -- "ness" "Through" "the" "full" "know" -- "ledge" _ "Of" "Him" _ "who" "has" "called" "us" "By" "His" "own" "glo" -- "ry" _ "and" "vir" -- "tue." "By" "His" "own" "glo" -- "ry" _ "and" "vir" -- "tue," _ "By" "His" "own" "glo" -- "ry" _ "and" "vir" -- _ _ "tue." "His" "di" -- "vine" "pow" -- "er" _ "has" "giv" -- "en" _ "to" "us" "All" "things" "that" "re" -- "late" "To" "life" "and" "god" -- "li" -- "ness" "Through" "the" "full" "know" -- "ledge" _ "Of" "Him" "who" "has" _ "called" "us" "By" "His" "own" "glo" -- "ry" _ "and" "vir" -- "tue."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

