\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS10081.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 12.59) (minimum-distance . 12.59) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "The greatest king on earth"
  subtitle = "Miscellaneous"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'4 | a'4 a'8[ a'8~] a'4 a'4 | a'2. c'8[ c'8] | d'2 f'4 d'4 | c'2. c'8[ c'8] | a'2 a'4 a'4 | bes'2 a'2 | g'1~ \break | g'2. c'4 | a'4 a'8[ a'8] a'4 a'8[ a'8] | a'4 f'8[ f'8~] f'4 c'8[ c'8] | d'4 f'4 f'4 d'4 | c'2. c'4 | d'4 f'8[ f'8~] f'4 d'4 | e'4 c'4 e'4 g'4~ | g'8[ f'8~] f'2. \break | f'2. f'8[ f'8] | e'2 g'4 bes'4 | bes'2. g'8[ g'8] | f'4. a'8 a'4 c''4 | c''2. a'8[ a'8] | g'4 g'4 g'4 g'4 | b'2 d''2 | c''1~ \break | c''2. c'8[ c'8] | a'4 a'8[ a'8~] a'4 a'4 | a'2. c'8[ c'8] | d'4 f'4 f'4 d'4 \break | c'2. c'4 | d'4 f'8[ f'8~] f'4 d'4 | e'4 c'4 e'4 g'4~ | g'8[ f'8~] f'2.~ | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  f4 | s4 s8 s8 s4 s4 | s2. s8 s8 | bes2 s4 s4 | f2. s8 s8 | s2 s4 s4 | d2:m s2 | g1:m | c2.:7 s4 | f4 s8 s8 s4 s8 s8 | s4 s8 s8 s4 s8 s8 | bes4 s4 s4 s4 | f2. s4 | bes4 s8 s8 s4 s4 | c4 s4 s4 s4 | bes8/f s8 s2. | f2. s8 s8 | c2 s4 s4 | c2.:7/e s8 s8 | f4. s8 s4 s4 | f2./a s8 s8 | g4 s4 s4 s4 | g2:7 s2 | c1 | c2.:7 s8 s8 | f4 s8 s8 s4 s4 | s2. s8 s8 | bes4 s4 s4 s4 | f2. s4 | g4:m7 s8 s8 s4 s4 | c4 s4 s4 s4 | bes8/f s8 s2. | f2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "The" "great" -- "est" _ "king" "on" "earth," "that" "is" "King" "So" -- "lo" -- "mon," "Fell" "in" "love" "with" "a" "coun" -- "try" "girl." _ "The" "king" "had" "to" "go" "to" "the" "coun" -- "try" _ "side" "And" "be" -- "come" "a" "coun" -- "try" "man," "To" "change" "his" "sta" -- _ "tus," "That" "he" "could" _ "court" _ "her." _ "In" "His" "court" -- "ship" "with" "her" "She" "was" "changed" "to" "be" "his" "match," "To" "be" -- "come" "his" "queen" "and" "Shu" -- "lam" -- "mite," _ "To" "be" -- "come" "his" "coun" -- _ "ter" -- "part" "And" "be" -- "come" "His" "lov" -- "ing" "bride." "This" "is" "the" "sto" -- _ "ry" "of" "the" "Song" "of" _ _ "Songs." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "The Song of Songs depicts our story with God" "Of fallen man with the King of kings." "Because of His love for us," "He became a lowly man" "To reach us and to die for our sins." "Then in resurrection He" "Regenerated me" "And now we’re daily being transformed." "To become the same as He with His life and nature" "To become His counterpart, His match and bride." } }
    } \hspace #1.1 }
    \null
  }
}
