\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS1089.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.63\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #1.16
  }
  system-system-spacing = #'((basic-distance . 13.07) (minimum-distance . 13.07) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.01) (minimum-distance . 15.01) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Unstopped, the flow from Jesus’ side"
  subtitle = "Consecration — Constrained by the Lord’s Love"
  opus = ""
}

global = {
  \key aes \major
  \time 6/8
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  ees'8 | c''4 bes'8 bes'8([ aes'8) f'8] | ees'4 f'8 ees'4 ees'8 | f'8([ g'8) aes'8] aes'8([ bes'8) c''8] \break | bes'4.~ bes'4 ees'8 | c''4 g'8 bes'8([ aes'8) f'8] | ees'4 f'8 ees'4 ees'8 | f'4 f'8 g'8([ f'8) ees'8] \break | aes'4.~ aes'4 c''8 | c''4 c'8 c'8([ d'8) e'8] | f'4 g'8 aes'4 c''8 | bes'8([ aes'8) g'8] f'8([ g'8) f'8] \break | ees'4.~ ees'4 ees'8 | c''4 g'8 bes'8([ aes'8) f'8] | ees'4 f'8 ees'4 ees'8 | f'4 f'8 g'8([ f'8) ees'8] | aes'4.~ aes'4 r8 \bar "|."
}

harmonies = \chordmode {
  \global
  aes8 | s4 s8 des8 s8 s8 | aes4 s8 s4 s8 | des8 s8 s8 bes8:7 s8 s8 | ees4. ees4:7 s8 | aes4 s8 des8 s8 s8 | c4:m s8 f4:m s8 | bes4:m s8 ees8:7 s8 s8 | aes4. s4 s8 | c4 s8 c8:7/e s8 s8 | f4:m s8 s4 s8 | ees8/bes s8 s8 bes8:7 s8 s8 | ees4. ees4:7 s8 | aes4 s8 des8 s8 s8 | c4:m s8 f4:m s8 | bes4:m s8 ees8:7 s8 s8 | des4./aes aes4 s8 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Un" -- "stopped," "the" "flow" _ "from" "Je" -- "sus’" "side," "Whose" "arms" _ "out" -- _ "stretched" "I" "see!" _ "On" "Cal" -- "vary’s" "tree," _ "what" "sac" -- "ri" -- "fice!" "He" "gave" "His" "all" _ "for" "me!" _ "Un" -- "barred," "my" "heart," _ "its" "doors" "swung" "wide," "Re" -- _ "sponds" "with" "joy" _ "com" -- "plete," _ "Sur" -- "ren" -- "dered," "un" -- _ "re" -- "serv" -- "ed" -- "ly," "Spon" -- "ta" -- "neous" "ju" -- _ "bi" -- "lee." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Agape love then bids me be" "No more for my own gain;" "For He who loved and rescued me" "Has won my life through pain." "Can one who’s loved not give his all?" "Divine love paid the cost." "A life that daily dies, then lives," "Will ne’er be counted loss." } }
      \vspace #0.88
      \line { \bold "3." \column { "To know the riches of His grace," "Old self I gladly yield;" "Emotion, mind, and will I place" "Within His hands, unsealed." "A life surrendered wholly, grows," "His image thus to shine;" "I sense His will and turn aside" "From what is not divine." } }
      \vspace #0.88
      \line { \bold "4." \column { "Through consecration’s narrow gate" "I walk and yield each choice;" "In daily steps, both small and great," "I hear my spirit’s voice." "Each time His will defeats my own," "A step ahead is won—" "Each vict’ry o’er my self-bound soul" "Leads ever to the Son." } }
    } \hspace #1.1 }
    \null
  }
}
