\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS151.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.69
  }
  system-system-spacing = #'((basic-distance . 13.94) (minimum-distance . 13.94) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "What miracle! What mystery!"
  subtitle = "Ultimate Manifestation—God’s Eternal Purpose"
  opus = ""
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'2 g'4. a'8 | b'2. d''4 | c''4( e'4) fis'4( a'4) | g'2. b4 | c'4( a'4) fis'4( d'4) | g'2 a'4( g'4) | fis'2 e'2 | d'1 \break | d'2 fis'4 g'4 | g'2 fis'4( d'4) | g'2 b'2 | a'2. d'4 | e'4( g'2) e'4 | d'4( g'2) a'4 | b'2 a'2 | g'1 \break | b'2 a'4 d'4 | g'2 a'4( b'4) | c''4( e'4) a'4( g'4) | fis'4.( e'8 d'4) d'4 | b4( d'4 g'4) d'4 | e'4( g'4 c''4) e'4 | fis'4( a'4 d''4) fis'4 | g'2. g'4 \break | b'2 b'2 | a'2. a'4 | c''2 c''2 | b'2. b'4 | e''2 e''2 | d''2 c''4( a'4) | g'2 fis'2 | g'1 \bar "|."
}

harmonies = \chordmode {
  \global
  g2 s4. s8 | s2. s4 | c4 s4 d4:7 s4 | g2. s4 | a4:m s4 d4 d4/c | g2/b d4/fis g4 | d2/a a2:7 | d1 | d2 d4:7 s4 | g2/d d4 d4/c | g2/b e2:m | d2. g4/b | c4 s2 s4 | g4/b s2 c4 | g2/d d2:7 | g1 | g2 d4 d4/c | g2/b d4/a g4 | c4 s4 a4/cis s4 | d4. s8 s4 s4 | g4 s4 s4 s4 | c4 s4 s4 s4 | d4:7 s4 s4 s4 | g2. s4 | g2 s2 | a2.:m s4 | d2:7 s2 | g2 g4:7 s4 | c2 d2/c | g2/b c4 s4 | g2/d d2:7 | g1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "What" "mir" -- "a" -- "cle!" "What" "mys" -- _ "ter" -- _ "y!" "That" "God" _ "and" _ "man" "should" _ "blend" -- "ed" "be!" "God" "be" -- "came" "man" "to" _ "make" "man" "God," "Un" -- "trace" -- _ "a" -- "ble" _ "e" -- "con" -- "o" -- "my!" "From" "His" "good" "plea" -- "sure," _ _ "heart’s" "de" -- _ "sire," _ _ "His" "high" -- _ _ "est" "goal" _ _ "at" -- _ "tained" _ "will" "be." "From" "His" "good" "plea" -- "sure," "heart’s" "de" -- "sire," "His" "high" -- "est" "goal" "at" -- _ "tained" "will" "be."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Flesh He became, the first God-man," "His pleasure that I God may be:" "In life and nature I’m God’s kind," "Though Godhead’s His exclusively." "His attributes my virtues are;" "His glorious image shines through me." } }
      \vspace #0.88
      \line { \bold "3." \column { "No longer I alone that live," "But God together lives with me." "Built with the saints in the Triune God," "His universal house we’ll be," "And His organic Body we" "For His expression corp’rately." } }
      \vspace #0.88
      \line { \bold "4." \column { "Jerusalem, the ultimate," "Of visions the totality;" "The Triune God, tripartite man—" "A loving pair eternally—" "As man yet God they coinhere," "A mutual dwelling place to be;" "God’s glory in humanity" "Shines forth in splendor radiantly!" } }
    } \hspace #1.1 }
    \null
  }
}

\markup \fill-line { \null \fontsize #-1 \italic "(Repeat the last two lines of each stanza.)" \null }
