\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS202.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.76
  }
  system-system-spacing = #'((basic-distance . 12.55) (minimum-distance . 12.55) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Lord, I love You, Lord, I need You"
  subtitle = "Longings—For Living in the Lord’s Presence"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  c'2 f'2 | g'2 a'2 | d'2 c''4( bes'4) | a'2 g'2 | c'2 a'2 | f'2. c'4 | d'2 bes'4( a'4) \break | g'2. a'4 | c'2 f'2 | g'2 a'4 c'4 | d'2 c''4( bes'4) | a'2 g'2 | a'2 f'2 | d'2. c'4 | f'2 e'4( f'4) | f'1 \break | c''2 bes'4 a'4 | f'2 c'2 | c''2 bes'4( a'4) | f'2 g'4 a'4 | bes'2 a'4 g'4 | f'2 f'8([ g'8)] a'4 | g'1~ | g'2. r4 \break | c''2 bes'4( a'4) | f'2 c'2 | c''2 bes'4 a'4 | a'2.( bes'4) | bes'2 a'4 g'4 | f'2 a'2 | g'1~ | g'2. c'4 \break | c'2 f'2 | g'2 a'4 c'4 | d'2 c''4( bes'4) | a'2 g'2 | c'2 a'2 | f'2. c'4 | d'2 bes'4( a'4) \break | g'2. a'4 | c'2 f'2 | g'2 a'4 c'4 | d'2 c''4( bes'4) | a'2 g'2 \break | a'2 f'2 | d'2. c'4 | f'2 e'2 | f'1~ | f'1 | r4 \bar "|."
}

harmonies = \chordmode {
  \global
  f2 s2 | d2:m s2 | bes2 s4 s4 | c2 s2 | a2:m s2 | d2.:m s4 | bes2 s4 s4 | c2. s4 | f2 s2 | d2:m s4 s4 | bes2 s4 s4 | c2 s2 | f2/a s2 | bes2. s4 | f2/c c4 s4 | f1 | ees2 s4 s4 | bes2/d s2 | ees2 s4 s4 | d2:m s4 s4 | g2:m s4 s4 | f2/a bes8 s8 s4 | c1 | s2. s4 | ees2 s4 s4 | bes2/d s2 | ees2 s4 s4 | d2.:m s4 | g2:m s4 s4 | f2/a bes2 | c1 | s2. s4 | f2 s2 | d2:m s4 s4 | bes2 s4 s4 | c2 s2 | a2:m s2 | d2.:m s4 | bes2 s4 s4 | c2. s4 | f2 s2 | d2:m s4 s4 | bes2 s4 s4 | c2 s2 | f2/a s2 | bes2. s4 | f2/c c2:7 | f1 | s1 | s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Lord," "I" "love" "You," "Lord," "I" _ "need" "You," "You’re" "the" "One," "the" "One" "I" _ "need," "To" "live" "this" "life," "Lord," "I" "need" "You" _ "al" -- "ways;" "By" "Your" "pre" -- "sence," "Lord," "take" _ "lead." "Lord," "look" "in" -- "to" "me," "And" "in" -- _ "fuse" "me" "To" "walk" "by" "the" "strength" "of" _ "Your" "eyes." _ "Lord" "em" -- _ "brace" "me," "Bear" "me" "in" "You," _ "Deep" "in" "Your" "love" "I" "hide." _ "And" "when" "I’m" "weak," "Lord," "and" "can’t" "go" _ "on" "more," "Lift" "my" "eyes" "to" "gaze" "on" _ "You;" "Speak" "soft" -- "ly" "to" "me," "Come" "in," "sub" -- _ "due" "me;" "In" "Your" "strength," "Lord," "take" "me" "through." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

