\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS268.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.66) (minimum-distance . 12.66) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Search me, O God, and know my heart"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  r4 g'4 g'8[ a'8~ a'8 g'8~] | g'2. c'4 | a'2. a'4 | g'1 | e'2 e'4 a'4 | g'2. e'4 | d'1~ \break | d'2 r4 g'4 | a'2 a'8 a'4. | g'2. e'8[ f'8] | g'4. g'8 e'4 d'4 | c'1 | r4 f'8[ f'8] f'4 e'8[ e'8(] | e'8[ d'8~] d'2.) \break | r4 a'8[ a'8] a'4 a'8[ a'8(] | a'8[ d'8~] d'2.) | r4 f'8[ f'8] f'4 e'8[ e'8~] | e'2 e'4. d'16([ c'16)] | d'1 | c'1 \break | r2 g'4 a'4 | g'2 e'2( | f'2) a'4 b'4 | c''2 g'2 | c''2 b'4( a'4) | a'2 g'2 | a'2 b'4( a'4) | a'2 g'2 \break | a'2 a'8 a'4. | b'2. b'4 | c''2 c''4. b'8 | a'1 | a'2 c''2 | c''2 b'2 | c''1~ | c''1 \break | a'2 c''2 | c''2 b'2 | c''1~ | c''1 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 s4 s8 s8 s8 s8 | c2./e s4 | f2. s4 | c1 | a2:m s4 s4 | e2.:m/g s4 | d1:m/f | g2 s4 s4 | f2 s8 s4. | g2. s8 s8 | c4. s8 g4/b s4 | a2:m c2/g | f4 s8 s8 s4 s8 s8 | g8 s8 s2. | a4:m s8 s8 s4 s8 s8 | d8:7 s8 s2. | f4 s8 s8 s4 s8 s8 | g2:7 s4. s16 s16 | f1/c | c1 | c2 s4 s4 | c2/e s2 | f2 s4 s4 | c2 s2 | a2:m s4 s4 | e2:m/g s2 | f2 s4 s4 | g2 s2 | f2 s8 s4. | g2. s4 | c2 s4. s8 | a1:m | f2 s2 | g2 s2 | a1:m | d1:7 | f2 s2 | g2:7 s2 | f1/c | c1 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Search" "me," "O" _ "God," _ "and" "know" "my" "heart;" "Try" "me" "and" "know" "my" "thoughts;" _ "And" "see" "if" "there" "be" "an" -- "y" "wick" -- "ed" "way" "in" "me;" "Lead" "me" "in" "the" "way," _ _ _ "lead" "me" "in" "the" "way," _ _ _ "Lead" "me" "in" "the" "way" _ "ev" -- "er" -- _ "last" -- "ing." "You" "have" "searched" "me;" _ "You" "have" "known" "me;" "My" _ "down" -- "sit" -- "ting," "my" "up" -- _ "ris" -- "ing;" "You" "un" -- "der" -- "stand" "my" "thoughts" "from" "a" -- "far;" "You" "know" "all" "my" "ways," _ "You" "know" "all" "my" "ways." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

