\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS3.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.70
  }
  system-system-spacing = #'((basic-distance . 14.36) (minimum-distance . 14.36) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "God has a dream"
  subtitle = "The Church—As God’s Dream"
  opus = ""
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  \partial 4.
}

melody = {
  \clef treble
  \global
  d'8[ b'8 a'8] | d'1~ | d'4 r8 g'8 \tuplet 3/2 { g'4 fis'4 e'4 } | g'4.( e'8) c'2~ | c'2 r8 c'8[ c''8 b'8] | e'1( | fis'4) r8 fis'8 fis'8[ fis'8 e'8 d'8] | b1~ \break | b2 r8 d'8[ b'8 a'8] | d'1~ | d'4 r8 g'8 \tuplet 3/2 { g'4 a'4 b'4 } | a'2. g'4 | e'2 r8 c''8[ b'8 a'8] | b'4.( a'8 g'4. e'8 | d'8)[ d'8 d'8 d'8] b'8([ a'8~ a'8) g'8] | g'1~ | g'2. r4 \break | d''2~ \tuplet 3/2 { d''4 b'4 a'4 } | g'2 \tuplet 3/2 { g'4 a'4 b'4 } | a'2. g'4 | e'2 fis'4 e'4 | d'4. d'8 g'4 a'4 | b'4. b'8 c''4 b'4 | a'1~ | a'2. r4 \break | d''2~ \tuplet 3/2 { d''4 b'4 a'4 } | g'4. g'8 \tuplet 3/2 { g'4 a'4 b'4 } | a'2. g'4 | e'2 r8 c''8[ b'8 a'8] | b'4.( a'8 g'4. e'8 | d'8)[ d'8 d'8 d'8] b'8([ a'8~ a'8) g'8] | g'1~ | g'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g8 s8 s8 | s1 | s4 s8 s8 \tuplet 3/2 { s4 s4 s4 } | a4.:m7 s8 s2 | s2 s8 s8 s8 s8 | c1 | d4 s8 s8 s8 s8 s8 s8 | g1 | d2:7 s8 s8 s8 s8 | g1 | g4:7 s8 s8 \tuplet 3/2 { s4 s4 s4 } | c2. s4 | a2:m s8 s8 s8 s8 | g4./d s8 e4.:m s8 | a8:m7 s8 s8 s8 d8:7 s8 s8 s8 | g2 c2/g | g2. s4 | g2 \tuplet 3/2 { s4 s4 s4 } | g2:7 \tuplet 3/2 { s4 s4 s4 } | c2. s4 | a2:m s4 s4 | g4. s8 s4 s4 | e4.:m s8 s4 s4 | a1:m7 | d2.:7 s4 | g2 \tuplet 3/2 { s4 s4 s4 } | g4.:7 s8 \tuplet 3/2 { s4 s4 s4 } | c2. s4 | a2:m s8 s8 s8 s8 | g4./d s8 e4.:m s8 | a8:m7 s8 s8 s8 d8:7 s8 s8 s8 | g2 c2/g | g2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "God" "has" "a" "dream," _ "this" "is" "what" "He’s" "want" -- _ "ing." _ "God" "has" "a" "dream," _ "and" "we" "are" "part" "of" "it." _ "God" "has" "a" _ "dream..." -- "that" "we" "may" "be" "one" "with" "Him." "God" "has" "a" _ "dream..." -- _ _ _ "real" -- "ized" "in" _ "you" _ "and" "me!" _ "God," _ "you" "and" "me..." "a" "dwell" -- "ing" "place" "to" "be." "God" "in" "man," "and" "man" "in" "God:" "one" "en" -- "ti" -- "ty." _ "Now," _ "it’s" "my" "dream..." "my" "vi" -- "sion" "and" "life" "to" "be!" "God" "has" "a" _ "dream..." -- _ _ _ "real" -- "ised" "in" _ "you" _ "and" "me!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

