\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS396.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.69
  }
  system-system-spacing = #'((basic-distance . 13.34) (minimum-distance . 13.34) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Take me Lord, and fill me with Your dear Self"
  subtitle = "Experience of Christ—Loving Him"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  a'8[ bes'8] | a'4. f'8 c'8 f'4 a'8 | g'4. e'8 cis'4. g'8 | f'4. d'8 a8 d'4 f'8 | ees'4. c'8 a4 bes8[ c'8] \break | d'4 a'4 g'4. e'8 | c'4 g'4 f'4. c'8 | bes4. f'8 \tuplet 3/2 { e'4 d'4 e'4 } | c'2. c'8[ c'8] \break | d'4 a'4 g'4. e'8 | c'4 g'4 fis'4 g'8[ a'8] | bes'2 \tuplet 3/2 { bes'4 a'4 g'4 } | f'2. r8 f'8 \break | f'4. f'8 \tuplet 3/2 { e'4 f'4 g'4 } | c'2. r8 f'8 | f'4. f'8 e'4 f'8[ g'16 a'16~] | a'2. r8 c''8 \break | d''4. bes'8 g'4. d''8 | c''4. a'8 f'4. c''8 | bes'4. f'8 e'4 bes'4 | a'2. r8 c''8 \break | d''4. bes'8 g'4. d''8 | c''4. a'8 f'4 g'8[ a'8] | bes'4. bes'8 a'8[ g'16 f'16~ f'8 e'16 f'16~] | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  f8 s8 | s4. s8 s8 s4 s8 | a4. s8 s4. s8 | d4.:m s8 s8 s4 s8 | c4.:m s8 f4:7 s8 s8 | bes4 s4 c4. s8 | a4:m s4 d4.:m s8 | g4.:m7 s8 \tuplet 3/2 { c4:7 s4 s4 } | f2 f4:7/a s8 s8 | bes4 s4 c4. s8 | a4:m s4 d4:7 s8 s8 | g2:m7 \tuplet 3/2 { c4:7 s4 s4 } | f2. s8 s8 | bes4. s8 \tuplet 3/2 { c4 s4 s4 } | f2. s8 s8 | bes4. s8 c4 s8 s16 s16 | f2. s8 s8 | bes4. s8 c4. s8 | a4.:m s8 d4.:m s8 | g4.:m7 s8 c4:7 s4 | f2 f4:7/a s8 s8 | bes4. s8 c4. s8 | a4.:m s8 d4:m s8 s8 | g4.:m7 s8 c8:7 s16 s16 s8 s16 s16 | f4 bes2/f f4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Take" "me" "Lord," "and" "fill" "me" "with" "Your" "dear" "Self," "Till" "my" "whole" "be" -- "ing" "is" "one" "with" "You." "Lord," "I’m" "will" -- "ing" "to" "o" -- "pen" "to" "You" "Eve" -- "ry" "mo" -- "ment" "in" "my" "life;" "Ful" -- "ly" "trust" -- "ing" "You," "to" "live" "Your" "dream" "For" "Your" "rest" "and" "ex" -- "pres" -- "sion." "Be" -- "side" "You" "I" "have" "no" "one" "In" "heav" -- "en" "or" "on" "the" _ "earth." "To" "You," "dear" "Lord," "I" "give" "my" "all." "I" "will" "not" "let" "You" "go." "Make" "Your" "de" -- "sire" "my" "heart’s" "de" -- "sire" "For" "our" "goal," "the" "New" "Je" -- "ru" -- _ "sa" -- "lem." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

