\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS406.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.88
  }
  system-system-spacing = #'((basic-distance . 12.64) (minimum-distance . 12.64) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "But God commends His own love to us"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key c \major
  \time 3/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  g'4 | g'2 g'4 | a'4 g'4 g'4 | e'2 e'4 | f'2 f'4 | g'2 g'4 \break | g'4 f'4 e'4 | d'8[ e'8~(] e'2~ | e'2.) | f'2. | f'2 e'4 | d'2.~ \break | d'2 g'4 | g'2 g'4 | a'4 g'4 g'4 | e'4 e'8 e'4. | f'4 f'4 f'4 | g'2 g'4 \break | g'4( f'4) e'4 | d'8([ e'8~] e'2~ | e'2.) | f'2 f'4 | f'2 e'8[ d'8~] | d'2.~ \break | d'2 g'4 | a'2 a'4 | a'2 c''4 | c''8[ b'8] a'2~ | a'4 a'4 a'4 | g'8[ f'8] e'2~ | e'2 g'4 | g'2.~ \break | g'2 g'4 | a'2. | a'2~ a'8[ c''8] | c''4 b'4 a'4 | a'2 a'4 | g'2.~ | g'2 g'4 | e'2.( | f'2.) \break | f'4 f'4 f'4 | f'8[ e'8] e'2 | f'2 f'8[ e'8] | d'2 c'8[ b8] | c'2.~ | c'2 r4 \break | f'2 f'8[ e'8] | d'2 c'8[ b8] | c'2.~ | c'2 r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 | s2 s4 | g4/b s4 s4 | a2:m s4 | f2 s4 | c2 s4 | c4 s4 s4 | a8:m s8 s2 | s2. | f2. | d2:m7 s4 | g2. | g2:7 s4 | c2 s4 | g4/b s4 s4 | a4:m s8 s4. | f4 s4 s4 | c2 s4 | c4 s4 s4 | a8:m s8 s2 | s2. | f2 s4 | d2:m7 s8 s8 | g2. | g2 s4 | a2:m s4 | s2 s4 | f8 s8 s2 | s4 s4 s4 | c8 s8 s2 | s2 s4 | g2. | g2 s4 | a2.:m | s2 s8 s8 | f4 s4 s4 | s2 s4 | c2. | s2 s4 | a2.:m | f2. | f4 s4 s4 | c8 s8 s2 | f2 s8 s8 | g2:7 s8 s8 | c2. | a2:m s4 | f2 s8 s8 | g2:7 s8 s8 | c2 f4/c | c2 s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "But" "God" "com" -- "mends" "His" "own" "love" "to" "us" "in" "that" "while" "we" "were" "yet" "sin" -- _ "ners," _ "Christ" "died" "for" "us." _ "Much" "more" "then," "hav" -- "ing" "been" "jus" -- "ti" -- "fied" "now" "in" "His" "blood," "we" "shall" _ "be" _ "saved" _ _ "through" "Him" "from" "the" "wrath." _ _ "For" "if," "while" "we" "were" "en" -- "e" -- "mies," _ "we" "were" "re" -- "con" -- "ciled" _ "to" "God," _ "to" "God" "through" _ "the" "death" "of" "His" "Son," "much" "more," _ "much" "more," _ "hav" -- "ing" "been" "re" -- "con" -- "ciled," "we" "shall" "be" "saved" "in" "His" "life." _ "We" "shall" "be" "saved" "in" "His" "life." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

