\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS419.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 13.13) (minimum-distance . 13.13) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "And we have the prophetic word"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 8
}

melody = {
  \clef treble
  \global
  c'8 | a'8 a'4 a'8~ a'4. f'8 | g'8 g'4 g'8~ g'4. f'8( | g'8) g'4 g'8~ g'4. a'8 | g'8 f'4 f'8~ f'8 g'4. \break | a'8 a'4 a'8~ a'4. f'8 | g'8 g'4 g'8~ g'2 | g'8 g'4 g'8~ g'4 a'8[ g'8~] | g'8 f'4.~ f'4. c'8 \break | c''8 c''4 c''8( c''8 a'4) g'8~ | g'2. g'8[ a'8] | bes'8 bes'4 bes'8~ bes'4. bes'8~ | bes'8 a'4 f'8~ f'8 g'4 f'8 \break | c''8 c''4 c''8( c''8 a'4) g'8~ | g'2. g'8[ a'8] | bes'8 bes'4 bes'8~ bes'4. bes'8~ | bes'8 a'4 f'8~ f'8 g'4. | f'1~ | f'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  f8 | s8 s4 s8 s4. s8 | c8 s4 s8 s4. s8 | g8:m s4 s8 s4. s8 | bes8 s4 s8 s8 s4. | f8 s4 s8 s4. s8 | c8 s4 s8 s2 | g8:m s4 s8 s4 s8 s8 | bes8 s4. s4. s8 | f8 s4 s8 s8 s4 s8 | c2. s8 s8 | g8:m s4 s8 s4. s8 | bes8 s4 s8 c8:7 s4 s8 | f8 s4 s8 s8 s4 s8 | c2. s8 s8 | g8:m s4 s8 s4. s8 | bes8 s4 s8 c8:7 s4. | f1 | s2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "And" "we" "have" "the" _ "pro" -- "phet" -- "ic" _ "word" "made" _ "more" _ "firm," "to" "which" "you" "do" _ "well" "to" "give" "heed" _ "as" "to" "a" "lamp" _ "shin" -- "ing" "in" _ "a" "dark" _ "place," _ "un" -- "til" "the" "day" _ _ "dawns" _ "and" "the" "morn" -- "ing" "star" _ "ris" -- _ "es" "in" _ "your" "hearts." "til" "the" "day" _ _ _ "dawns" "and" "the" "morn" -- "ing" "star" _ "ris" -- _ "es" "in" _ "your" "hearts." _
}

verseTwo = \lyricmode {
  \set ignoreMelismata = ##t _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ "un" -- _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
    \addlyrics { \verseTwo }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

