\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS445.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.87
  }
  system-system-spacing = #'((basic-distance . 14.35) (minimum-distance . 14.35) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Hebrews 1:3"
  subtitle = "Scriptures for Singing"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'4 | \tuplet 3/2 { g'4 g'4 g'4 } \tuplet 3/2 { g'4 f'4 e'4 } | c'4. c'8 \tuplet 3/2 { c'4( d'4) e'4 } | \tuplet 3/2 { f'4 f'4 e'4 } \tuplet 3/2 { d'4 c'4 d'4 } | e'4.( g'8) g'4. c'8 \break | \tuplet 3/2 { g'4 g'4 g'8[ g'8] } \tuplet 3/2 { g'4 f'4 e'4 } | c'2 \tuplet 3/2 { c'4( d'4) e'4 } | f'2 f'4. g'8 | g'2. a'8[ b'8] \break | c''2 \tuplet 3/2 { b'4 a'4 g'4 } | \tuplet 3/2 { a'4 g'4 f'4 } g'2 | r4 c'4 c'4 c'8[ c'8] | f'4.( e'8) d'4. d'8 \break | g'4.( f'8) e'2 | f'2. f'8([ g'8)] | g'2 b4 b8[ d'8] | c'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c4 | \tuplet 3/2 { s4 s4 s4 } \tuplet 3/2 { g4 s4 s4 } | a4.:m s8 \tuplet 3/2 { c4/e s4 s4 } | \tuplet 3/2 { f4 s4 s4 } \tuplet 3/2 { g4 s4 s4 } | c4. s8 g4. s8 | \tuplet 3/2 { c4 s4 s8 s8 } \tuplet 3/2 { g4 s4 s4 } | a2:m \tuplet 3/2 { c4/e s4 s4 } | f2 d4.:m7 s8 | g2:sus4 g4 s8 s8 | c2 \tuplet 3/2 { e4:m s4 s4 } | \tuplet 3/2 { f4 s4 s4 } c2 | a4:m s4 c4/e s8 s8 | f4. s8 g4. s8 | c4. s8 a2:m | f2 d4:m7 s8 s8 | g2 g4:7 s8 s8 | c2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t "Who," "be" -- "ing" "the" "ef" -- "ful" -- "gence" "of" "His" "glo" -- _ "ry" "and" "the" "im" -- "press" "of" "His" "sub" -- _ "stance" "and" "up" -- "hold" -- "ing" "and" "bear" -- "ing" "all" "things" "by" _ "the" "word" "of" "His" "power," "hav" -- "ing" "made" "pu" -- "ri" -- "fi" -- "ca" -- "tion" "of" "sins," "sat" "down" "on" "the" "right" _ "hand," "the" "right" _ "hand" "of" "the" _ "Ma" -- "jes" -- "ty" "on" "high."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

