\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS441.svg

#(set-global-staff-size 15.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 6.39\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.70
  }
  system-system-spacing = #'((basic-distance . 13.04) (minimum-distance . 13.04) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.96) (minimum-distance . 14.96) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "The secret of the universe"
  subtitle = "Ultimate Manifestation—The Spirit and the Bride"
  opus = ""
}

global = {
  \key c \major
  \time 3/4
  \autoBeamOff
  \partial 4.
}

melody = {
  \clef treble
  \global
  c'8 c'8.[ d'16] | e'4. g'8 a'8.[ g'16] | g'4( e'8)[ g'8] g'8.[ e'16] | d'4. f'8 e'8.[ d'16] \break | e'4. c'8 c'8.[ d'16] | e'4. g'8 a'8.[ g'16] | g'4( e'8)[ g'8] g'8.[ e'16] | d'4. f'8 e'8.[ d'16] \break | c'4. c''8 c''8.[ c''16] | a'4. c''8 c''8.[ c''16] | g'4( e'8)[ g'8] g'8.[ a'16] | g'4( d'4) f'4 \break | e'4. c''8 c''8.[ c''16] | a'4. c''8 c''8.[ c''16] | g'4( e'8)[ g'8] g'8.[ a'16] | g'4( d'4) e'4 \break | c'4. c''8^\markup { \box \bold "Chorus" } c''8.[ c''16] | c''4. c''8 b'8.[ a'16] | g'4( e'8)[ g'8] g'8.[ a'16] | g'4( d'4) a'4 \break | g'4. c''8 c''8.[ c''16] | c''4. c''8 b'8.[ a'16] | g'4( e'8)[ g'8] g'8.[ a'16] | g'4( d'4) e'4 | c'4. r4. \bar "|."
}

harmonies = \chordmode {
  \global
  c8 s8. s16 | s4. s8 f8. s16 | e4:m s8 s8 a8.:m s16 | f4. s8 g8.:7 s16 | c4. s8 g8. s16 | c4. s8 g8./d s16 | c4/e s8 s8 a8.:m s16 | f4. s8 g8.:7 s16 | c4. s8 c8.:7 s16 | f4. s8 s8. s16 | c4 s8 s8 s8. s16 | d4:m s4 g4 | c4. s8 c8.:7 s16 | f4. s8 s8. s16 | c4 s8 s8 s8. s16 | d4:m s4 g4 | c4. s8 s8. s16 | f4. s8 s8. s16 | e4:m s8 s8 a8.:m s16 | d4:m s4 g4 | c4. s8 c8.:7 s16 | f4. s8 s8. s16 | e4:m s8 s8 a8.:m s16 | d4:m s4 g4 | c4. s4. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "The" "se" -- "cret" "of" "the" "u" -- "ni" -- "verse" _ "In" "ag" -- "es" "past" "a" "mys" -- "ter" -- "y" "Hid" -- "den" "in" "God" "but" "now" "made" "known" _ "By" "rev" -- "e" -- "la" -- "tion’s" "six" -- "fold" "key," "Which" "o" -- "pens" "and" "un" -- "locks" "the" "plan" _ "Of" "His" "e" -- "con" -- _ "o" -- "my" "To" "gain" "a" "wife," "His" "coun" -- "ter" -- "part," _ "And" "match" "e" -- "ter" -- _ "nal" -- "ly." \set stanza = "(C)" "The" "Tri" -- "une" "God," "tri" -- "par" -- "tite" "man;" _ "A" "u" -- "ni" -- "ver" -- _ "sal" "pair." "The" "Spir" -- "it" "pro" -- "cessed," "bride" "trans" -- "formed;" _ "One" "mar" -- "ried" "na" -- _ "ture" "share."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Creation is the lovely platform" "Of this divine romance sublime" "Between a creature and Creator" "Upon the bridge of space and time;" "For this the heavens were stretched forth" "The earth’s foundations laid" "Tripartite man, made to contain Him," "Was with a spirit made." } }
      \vspace #0.88
      \line { \bold "3." \column { "God became man through incarnation" "Man’s empty virtues to imbue," "In Christ fulfilling His intention" "Creation old becoming new;" "God’s attributes so bountiful" "In human virtues shown" "Uplifted, filled, enriched, and strengthened;" "Love, life, and light—made known." } }
    }
    \left-column {
      \line { \bold "4." \column { "Though man became usurped by Satan" "God gave His Son man’s life to win;" "The Olive Tree was cut and wounded" "So sinners could be grafted in" "Transferred from Adam into Christ," "Brought out of death into life;" "Forgiveness kissing man’s repentance" "Hath sealed them Husband and wife." } }
      \vspace #0.88
      \line { \bold "5." \column { "God became man to make man God;" "The King became a countryman" "Through incarnation, human living" "The cross and resurrection’s plan;" "A country girl to be His queen" "Presented as His bride," "Fully redeemed, regenerated" "Transformed and glorified." } }
    }
    \left-column {
      \line { \bold "6." \column { "Christ and the church a perfect match" "And universal loving pair" "The Spirit and the bride in union" "One mingled life and living share;" "The Husband is the processed God" "The man the transformed wife" "To be the New Jerusalem" "Living a marriage life." } }
    }
  }
}
