\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS627.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.91\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.74
  }
  system-system-spacing = #'((basic-distance . 13.33) (minimum-distance . 13.33) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.00) (minimum-distance . 15.00) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Make my hands full, I pray, dear Lord"
  subtitle = "Consecration — Christ as Our Burnt Offering"
  opus = ""
}

global = {
  \key f \major
  \time 3/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  a'4 a'4 a'4 | c''2 f'4 | g'2 g'4 | a'2. | c''4 c''4 c''4 | bes'2 c''4 | a'2 bes'4 | g'2. \break | g'4 g'4 g'4 | g'2 g'4 | b'2 b'4 | c''2. | a'4 a'4 a'4 | a'4( g'4) f'4 | f'2 e'4 | f'2. \bar "|."
}

harmonies = \chordmode {
  \global
  f4 s4 s4 | f2/a s4 | bes2 c4 | f2. | f4/a s4 s4 | c2/g s4 | f2 bes4/d | c2. | c4 s4 s4 | g2 s4 | g2:7 s4 | c2 c4/e | f4 s4 f4:7 | bes4 s4 s4 | f2/c c4:7 | f2. |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Make" "my" "hands" "full," "I" "pray," "dear" "Lord;" "Full" "of" "the" "Christ" "en" -- "joyed" "each" "day." "E’en" "now" "I" "come" "to" "You" "for" "more," "Emp" -- "ty" "for" "You;" _ "fill" "me" "to" -- "day."
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \left-column {
      \line { \bold "2." \column { "Make my hands full today, O Lord." "You lived a life all absolute." "I lay my hands upon You, Lord," "In union, grafted, one with You." } }
      \vspace #0.88
      \line { \bold "3." \column { "Make my hands full right now, O Lord," "That I’d partake of You today." "By eating of Your living Word," "My old self would be purged away." } }
      \vspace #0.88
      \line { \bold "4." \column { "Make my hands full, my Savior Lord." "You were made sin and judged by God," "That all my sins may be no more." "I would, each day, apply Your blood." } }
    }
    \left-column {
      \line { \bold "5." \column { "Make my hands full; You are my peace." "In everything, I’d talk to You," "With God no longer enemies," "Enjoying peace with all saints, too." } }
      \vspace #0.88
      \line { \bold "6." \column { "Make my hands full; this is my prayer." "Remind me, Lord, how rich are You." "I’d on Thee labor, to prepare," "To offer Christ in worship true." } }
      \vspace #0.88
      \line { \bold "7." \column { "Make my hands full with only You;" "Nothing of self, but all of Christ." "Savor so sweet and fragrant, too," "Rises to God, now satisfied." } }
    }
  }
}
