\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS777.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 9.03\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.84
  }
  system-system-spacing = #'((basic-distance . 12.27) (minimum-distance . 12.27) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 14.95) (minimum-distance . 14.95) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Eat God"
  subtitle = "Experience of Christ — As Food"
  opus = ""
}

global = {
  \key f \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'4 | a'8[ a'8] a'4~ a'4 c''4 | g'2 f'4 e'4 | f'2. a'4 \break | e'2. c'4 | d'4 f'4 f'2~ | f'4 f'4 f'4 g'4 | g'1 \break | r2 f'4 g'4 | a'4 a'4 a'4 c''4 | g'4 g'4~ g'4 a'4 | f'4 f'4 f'4 a'4 \break | e'4 e'4 e'4 c'4 | d'4 f'4 f'2 | r4 f'4 f'4 g'4 | g'1 \break | r2 a'4(^\markup { \box \bold "Chorus" } g'4) | f'2 f'4 a'4 | c''2 a'4 c''4 | d''4 c''4 bes'4 a'4 \break | g'2 a'4 g'4 | f'2 f'4 a'4 | c''4 a'4 a'2 | r4 bes'8[ bes'8] bes'4 a'4 \break | g'2 a'4 g'4 | f'2 f'4 a'4 | c''2 a'4 c''4 | d''4 c''4 bes'4 a'4 \break | g'2 a'4 g'4 | f'2 f'4 a'4 | g'4 f'4 e'2 | f'1~ | f'2 r2 \bar "|."
}

harmonies = \chordmode {
  \global
  f4 | s8 s8 s4 s4 s4 | c2/e s4 s4 | d2.:m s4 | a2.:m/c s4 | bes4 s4 s2 | g4:m7 s4 s4 s4 | c1 | c2:7 s4 s4 | f4 s4 s4 s4 | c4/e s4 s4 s4 | d4:m s4 s4 s4 | a4:m/c s4 s4 s4 | bes4 s4 s2 | g4:m7 s4 s4 s4 | c1 | c2:7 s4 s4 | f2 s4 s4 | c2/e s4 s4 | bes4/d s4 s4 s4 | c2 s4 s4 | f2 s4 s4 | a4:m s4 s2 | g4:m7 s8 s8 s4 s4 | c2 s4 s4 | f2 s4 s4 | c2/e s4 s4 | bes4/d s4 s4 s4 | c2 s4 s4 | bes2 s4 s4 | c4:7 s4 s2 | f1 | s2 s2 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "In" "Ge" -- "ne" -- "sis" _ "we" "see," "God’s" "de" -- "si" -- "re" "being" "For" "man" "to" "eat" _ "the" "tree" "of" "life." "Af" -- "ter" "Ad" -- "am" "was" "cre" -- "at" -- "ed," _ "the" "first" "thing" "that" "God" "want" -- "ed" "Was" "for" "him" "to" "eat" "but" "to" "eat" "what?" \set stanza = "(C)" "Eat" _ "God," "eat" "the" "Lord," "eat" "Him" "in" "the" "Ho" -- "ly" "Word." "He’s" "the" "Lamb" "who" "re" -- "duced" "Him" -- "self," "and" "the" "tree" "of" "life." "Leave" "your" "con" -- "cepts" "be" -- "hind" "and" "God’s" "con" -- "cept" "you" "will" "find:" "All" "He" "wants" "is" "for" "you" "to" "eat" "Him." _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "In Exodus we see, God’s desire being" "For man to eat the Lamb." "As a creature so small, He’s approachable to all;" "This Lamb is God Himself." } }
    } \hspace #1.1 }
    \null
  }
}
