\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS853.svg

#(set-global-staff-size 16.000)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 9.03\mm
  bottom-margin = 12.5\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.86
  }
  system-system-spacing = #'((basic-distance . 12.48) (minimum-distance . 12.48) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.03) (minimum-distance . 15.03) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "True Worshippers"
  subtitle = "Worship of the Father — General"
  opus = ""
}

global = {
  \key g \major
  \time 4/4
  \autoBeamOff
  
}

melody = {
  \clef treble
  \global
  g'4.( d'8) d'2~ | d'4 r4 g'4 a'4 | c''4.( b'8) b'2~ | b'4 r4 g'4 a'8([ g'8)] \break | b'2 a'2 | g'2 \tuplet 3/2 { g'4 a'4 b'4 } | b'4.( a'8) a'2~ | a'2 r2 \break | g'4.( d'8) d'2~ | d'4 r4 g'4 a'4 | c''4.( b'8) b'2~ | b'4 r4 g'4 a'8([ g'8)] \break | b'2 a'2 | g'2 \tuplet 3/2 { g'4( a'4) b'4 } | b'4.( a'8) a'2~ | a'2 r4 b'8[ c''8] \break | b'2. fis'8[ a'8] | g'2. b'8[ c''8] | b'2. fis'8[ a'8] | g'4. b'8 a'4 b'8[ c''8] \break | d''2. fis'8[ a'8] | g'2. e'8[ fis'8] | g'4 g'4~ g'4 g'8[ b'8] | a'2 g'4 fis'4 \break | g'1~ | g'4 r8 g'8 g'4 fis'4 | g'1( | fis'4) r4 g'4 fis'4 | g'1~ | g'2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  g4. s8 s2 | c4 s4 s4 s4 | g4. s8 s2 | c4 s4 s4 s8 s8 | g2 d2/fis | e2:m \tuplet 3/2 { s4 s4 s4 } | d4.:sus4 s8 d2 | d2:sus4 d2 | g4. s8 s2 | c4 s4 s4 s4 | g4. s8 s2 | c4 s4 s4 s8 s8 | g2 d2/fis | e2:m \tuplet 3/2 { s4 s4 s4 } | d4.:sus4 s8 d2 | d2:sus4 d4 s8 s8 | b2.:m s8 s8 | e2.:m s8 s8 | b2.:m s8 s8 | c4. s8 d4 s8 s8 | b2.:m s8 s8 | e2.:m s8 s8 | c4 s4 s4 s8 s8 | d2 s4 s4 | c1 | d4 s8 s8 s4 s4 | c1 | d4 s4 s4 s4 | g1 | c2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Fa" -- _ "ther," _ "how" "we" "love" _ "You," _ "How" "we" _ "wor" -- "ship" "You" "in" "Your" "dis" -- "pens" -- _ "ing." _ "Fa" -- _ "ther," _ "how" "we" "love" _ "You," _ "How" "we" _ "wor" -- "ship" "You" "in" _ "Your" "son" -- _ "ship." _ "Lord," "we" "hon" -- "or" "Your" "Son" "By" "our" "liv" -- "ing" "in" "truth" -- "ful" -- "ness," "And" "we" "wor" -- "ship" "You," "God," "Ho" -- "ly" "Fa" -- "ther," _ "as" "Your" "true" "wor" -- "ship" -- "pers...." _ "True" "wor" -- "ship" -- "pers...." _ "Fa" -- "ther" "God!" _
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Father, how we love You," "How we worship You in Your one Body;" "Father, how we love You," "How we worship You in our feasting;" "By our eating this bread," "And our drinking of this one cup," "We do worship You, God," "Holy Father, as Your true worshippers...." "True worshippers.... Father God!" } }
    } \hspace #1.1 }
    \null
  }
}
