\version "2.24.3"

% Generated by svg-to-lilypond from pianoSvg/NS923.svg

#(set-global-staff-size 14.500)

\paper {
  #(set-paper-size "letter")
  left-margin = 12.7\mm
  right-margin = 8.89\mm
  top-margin = 8.67\mm
  bottom-margin = 12.50\mm
  indent = 0
  #(define fonts
     (set-global-fonts
       #:roman "Century Schoolbook L"
       #:sans "sans-serif"
       #:factor (/ staff-height pt 20)))
  bookTitleMarkup = \markup \column {
    \fill-line {
      \null
      \override #'(baseline-skip . 3.5) \center-column {
        \fontsize #3 \bold \fromproperty #'header:title
        \bold \fromproperty #'header:subtitle
      }
      \raise #-8.1 \fontsize #8.5 \fromproperty #'header:opus
    }
    \vspace #0.70
  }
  system-system-spacing = #'((basic-distance . 12.41) (minimum-distance . 12.41) (padding . 0) (stretchability . 0))
  score-markup-spacing = #'((basic-distance . 15.06) (minimum-distance . 15.06) (padding . 0) (stretchability . 0))
  scoreTitleMarkup = ##f
  tagline = \markup \line { \hspace #1.84 \override #'(font-name . "Trebuchet MS") "www.hymnal.net" }
}

\header {
  title = "Come and Sing Songs of Zion With Me"
  subtitle = "The Church — As God’s City"
  opus = ""
}

global = {
  \key c \major
  \time 4/4
  \autoBeamOff
  \partial 4
}

melody = {
  \clef treble
  \global
  c'8[ d'8] | e'4 e'8[ d'8] e'8[ f'8~ f'8 g'8] | g'2 r8 e'8[ e'8 g'8] | a'4. a'8 g'4 d'4 \break | e'2 r8 c'8[ e'8 g'8] | a'4 a'4 b'4. a'8 | g'8[ c'8] c'4~ c'8[ c'8 d'8 e'8] | f'8[ f'8~ f'8 e'8] d'4 c'8[ d'8] \break | c'2. c'8[ d'8] | e'4 e'8[ d'8] e'8[ f'8~ f'8 g'8] | g'2 r8 e'8[ e'8 g'8] | a'4. a'8 g'4. d'8 \break | e'2 r8 c'8[ e'8 g'8] | a'4 a'4 b'4. a'8 | g'8[ c''8] c''4~ c''8[ c'8 d'8 e'8] | f'4. c''8 b'4. a'8 \break | g'2. g'8[ g'8]^\markup { \box \bold "Chorus" } | c''2 c''8[ b'8~ b'8 e'8] | g'2. a'8[ b'8] | c''2 d''8[ c''8~ c''8 a'8] \break | g'2. e'8[ g'8] | a'8[ a'8~ a'8 a'8] b'4. a'8 | g'4 c'4~ c'8[ c'8 d'8 e'8] | f'4 f'8[ g'8] a'4 c''8([ d''8)] \break | d''2. g'4 | c''8[ c''8~ c''8 c''8] d''8[ c''8~ c''8 e''8] | g'2. a'8[ b'8] | c''8[ c''8~ c''8 c''8] d''8[ c''8~ c''8 a'8] \break | g'2. e'8[ g'8] | a'4 a'8[ a'8] b'4 a'4 | g'8[ c''8] c''4~ c''8[ c'8 d'8 e'8] | f'4. c''8 b'4 a'8([ b'8)] | c''2. r4 \bar "|."
}

harmonies = \chordmode {
  \global
  c8 s8 | s4 s8 s8 s8 s8 s8 s8 | c2:maj7 s8 s8 s8 s8 | f4. s8 g4 s4 | c2 s8 s8 s8 s8 | f4 s4 g4. s8 | a8:m s8 s4 s8 s8 s8 s8 | f8 s8 s8 s8 g4 s8 s8 | c2. s8 s8 | s4 s8 s8 s8 s8 s8 s8 | c2:maj7 s8 s8 s8 s8 | f4. s8 g4. s8 | c2 s8 s8 s8 s8 | f4 s4 g4. s8 | a8:m s8 s4 s8 s8 s8 s8 | f4. s8 d4.:m s8 | g2. s8 s8 | c2 s8 s8 s8 s8 | c2.:maj7 s8 s8 | f2 g8 s8 s8 s8 | c2. s8 s8 | f8 s8 s8 s8 g4. s8 | a4:m s4 s8 s8 s8 s8 | f4 s8 s8 s4 s8 s8 | g2. s4 | c8 s8 s8 s8 s8 s8 s8 s8 | c2.:maj7 s8 s8 | f8 s8 s8 s8 s8 s8 s8 s8 | c2. s8 s8 | f4 s8 s8 g4 s4 | a8:m s8 s4 s8 s8 s8 s8 | f4. s8 g4 s8 s8 | c2. s4 |
}

verseOne = \lyricmode {
  \set ignoreMelismata = ##t \set stanza = "1." "Come" "and" "sing" "songs" "of" "Zi" -- "on" _ "with" "me;" "My" "heart" "finds" "joy" "no" "oth" -- "er" "way;" "Thoughts" "of" "God’s" "king" -- "dom" "well" "up" "in" -- "stant" -- "ly," _ "Thoughts" "of" "the" "dwell" -- "ing" _ "He" "chose" "for" "His" "name." "With" "com" -- "pan" -- "ions," "glad" "mu" -- "sic" _ "we" "raised," "En" -- "tered" "in" -- "to" "His" "courts" "with" "praise;" "With" "joy" "in" "one" "ac" -- "cord" "we" "kept" "the" "feast," _ "And" "all" "our" "vows" "to" "Him" "we" "paid." \set stanza = "(C)" "My" "whole" "heart" "fac" -- "es" _ "God’s" "throne;" "My" "eyes" "see" "Zi" -- "on" _ "a" -- "lone." "I’ll" "live" "as" "a" _ "so" -- "journ" -- "er" "glad" -- "ly," _ "For" "Zi" -- "on’s" "now" "ev" -- "ery" -- "thing" "to" _ "me." "The" "High" -- "est" _ "is" "call" -- "ing" _ "to" "me;" "He" "is" "count" -- "ing" _ "His" "own," "one" _ "by" "one." "Sing" -- "ing," "danc" -- "ing," "we" "all" "shout" "joy" -- "ful" -- "ly," _ "“All" "of" "our" "springs" "are" "found" "in" _ "thee.”"
}

\score {
  <<
    \new ChordNames \with {
      \override ChordName.font-size = #-1
      majorSevenSymbol = \markup { "maj7" }
    } \harmonies
    \new Staff { \melody }
    \addlyrics { \verseOne }
  >>
  \layout {
    \context {
      \Score
      \override RehearsalMark.font-size = #0
      \override RehearsalMark.font-series = #'medium
      \override RehearsalMark.self-alignment-X = #CENTER
    }
    \context {
      \Staff
      \override TextScript.self-alignment-X = #CENTER
    }
    \context {
      \Lyrics
      \override LyricHyphen.minimum-distance = #0.6
      \override LyricSpace.minimum-distance = #2.5
    }
    \context {
      \Score
      % line breaks come only from the explicit break marks (one per original system)
      \override NonMusicalPaperColumn.line-break-permission = ##f
    }
  }
}

\markup {
  \fill-line {
    \null
    \line { \left-column {
      \line { \bold "2." \column { "Come and sing songs of Zion with me," "Sing of salvation’s rich outflow;" "Highways to Zion taking corporately," "Leave, long-forgotten, all trials and woe." "How I love, Lord, Your temple, Your home," "Your dwelling place, in glory bright;" "We dance with tambourines before Your throne," "In goodness of Your house delight." } }
    } \hspace #1.1 }
    \null
  }
}
